import { z } from 'zod';
import { getDatabase } from '../db/builtin-sqlite.js';
import * as artifactsModule from '../artifacts/index.js';

// 动态导入避免循环依赖
async function logAudit(params: { category: string; action: string; target: string; result: 'success' | 'failed' | 'partial'; detail?: Record<string, any> }) {
  try {
    const audit = await import('../audit/index.js');
    return await audit.logAudit(params);
  } catch {
    // 审计模块不可用时静默忽略
  }
}

function generateId() {
  return crypto.randomUUID();
}

function now() {
  return new Date().toISOString();
}

function parseJsonField(val: string | undefined | null, fieldName: string) {
  if (!val) return {};
  try {
    return JSON.parse(val);
  } catch {
    throw new Error(`Invalid JSON in ${fieldName}`);
  }
}

// ── Schemas ──────────────────────────────────────────────────────────────────

const createPackageSchema = z.object({
  model_id: z.string().min(1, 'model_id is required'),
  package_name: z.string().min(1, 'package_name is required'),
  package_version: z.string().default('1.0.0'),
  artifact_ids: z.array(z.string()).default([]),
  release_note: z.string().default(''),
  storage_path: z.string().default(''),
});

const updatePackageSchema = z.object({
  package_name: z.string().optional(),
  package_version: z.string().optional(),
  status: z.enum(['draft', 'building', 'ready', 'published', 'archived', 'failed']).optional(),
  artifact_ids: z.array(z.string()).optional(),
  release_note: z.string().optional(),
  storage_path: z.string().optional(),
});

// ── Helper: Generate Manifest ───────────────────────────────────────────────

function generateManifest(pkg: any, artifacts: any[]): object {
  return {
    package: {
      id: pkg.id,
      name: pkg.package_name,
      version: pkg.package_version,
      model_id: pkg.model_id,
      created_at: pkg.created_at,
    },
    artifacts: artifacts.map((a) => ({
      id: a.id,
      name: a.name,
      type: a.artifact_type,
      role: a.role || 'primary',
      path: a.relative_path || a.path || '',
      size: a.file_size_bytes || 0,
      checksum: a.checksum || '',
    })),
    metadata: {
      generated_at: now(),
      generator: 'AegisFlow Intelligence Platform v1.5.0',
    },
  };
}

// ── Helper: Generate Release Note ───────────────────────────────────────────

function generateReleaseNoteFull(pkg: any, artifacts: any[], model: any): string {
  const lines: string[] = [];
  lines.push(`# ${pkg.package_name} v${pkg.package_version}`);
  lines.push('');
  lines.push(`**Model:** ${model?.name || 'Unknown'} (${model?.version || 'N/A'})`);
  lines.push(`**Created:** ${fmt(pkg.created_at)}`);
  lines.push('');
  lines.push('## Contents');
  lines.push('');
  artifacts.forEach((a, i) => {
    lines.push(`${i + 1}. **${a.name}** (${a.artifact_type})`);
    if (a.file_size_bytes) {
      lines.push(`   - Size: ${formatBytes(a.file_size_bytes)}`);
    }
  });
  lines.push('');
  lines.push('---');
  lines.push(`*Generated by AegisFlow Intelligence Platform*`);
  return lines.join('\n');
}

function formatBytes(bytes?: number | null) {
  if (!bytes) return '—';
  if (bytes < 1024) return bytes + ' B';
  if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB';
  if (bytes < 1024 * 1024 * 1024) return (bytes / (1024 * 1024)).toFixed(1) + ' MB';
  return (bytes / (1024 * 1024 * 1024)).toFixed(2) + ' GB';
}

function fmt(s?: string | null) {
  if (!s) return '—';
  try { return new Date(s).toLocaleString('zh-CN'); } catch { return s; }
}

// ── List ─────────────────────────────────────────────────────────────────────

export async function listPackages(query: any) {
  const dbInstance = getDatabase();
  const { model_id, status, q } = query;

  let sql = 'SELECT * FROM model_packages WHERE 1=1';
  const params: any[] = [];

  if (model_id) {
    sql += ' AND model_id = ?';
    params.push(model_id);
  }
  if (status) {
    sql += ' AND status = ?';
    params.push(status);
  }
  if (q) {
    sql += ' AND (package_name LIKE ? OR package_version LIKE ?)';
    params.push(`%${q}%`, `%${q}%`);
  }

  sql += ' ORDER BY created_at DESC';

  const rows = dbInstance.prepare(sql).all(...params);
  return {
    ok: true,
    packages: rows.map((r: any) => ({
      ...r,
      artifact_ids_json: parseJsonField(r.artifact_ids_json, 'artifact_ids_json'),
      manifest_json: parseJsonField(r.manifest_json, 'manifest_json'),
    })),
    total: rows.length,
  };
}

// ── Get One ──────────────────────────────────────────────────────────────────

export async function getPackageById(id: string) {
  const dbInstance = getDatabase();
  const pkg = dbInstance.prepare('SELECT * FROM model_packages WHERE id = ?').get(id) as any;
  if (!pkg) {
    return { ok: false, error: `Package ${id} not found` };
  }
  return {
    ok: true,
    package: {
      ...pkg,
      artifact_ids_json: parseJsonField(pkg.artifact_ids_json, 'artifact_ids_json'),
      manifest_json: parseJsonField(pkg.manifest_json, 'manifest_json'),
    },
  };
}

// ── Create ───────────────────────────────────────────────────────────────────

export async function createPackage(body: any) {
  const dbInstance = getDatabase();
  const validation = createPackageSchema.safeParse(body);
  if (!validation.success) {
    return { ok: false, error: validation.error.message };
  }
  const data = validation.data;
  const id = generateId();
  const nowStr = now();

  // Verify model exists
  const model = dbInstance.prepare('SELECT * FROM models WHERE model_id = ?').get(data.model_id);
  if (!model) {
    return { ok: false, error: `Model ${data.model_id} not found` };
  }

  // Fetch artifacts
  let artifacts: any[] = [];
  let totalSize = 0;
  if (data.artifact_ids && data.artifact_ids.length > 0) {
    for (const artId of data.artifact_ids) {
      const art = dbInstance.prepare('SELECT * FROM artifacts WHERE id = ?').get(artId);
      if (art) {
        artifacts.push(art);
        totalSize += (art as any).file_size_bytes || 0;
      }
    }
  }

  // Generate manifest
  const manifest = generateManifest(
    { id, package_name: data.package_name, package_version: data.package_version, model_id: data.model_id, created_at: nowStr },
    artifacts.map((a) => ({
      id: a.id,
      name: a.name,
      artifact_type: a.artifact_type,
      path: a.path,
      file_size_bytes: a.file_size_bytes,
    }))
  );

  // Generate release note
  const releaseNote = generateReleaseNoteFull(
    { id, package_name: data.package_name, package_version: data.package_version, created_at: nowStr },
    artifacts,
    model
  );

  // Insert package
  dbInstance.prepare(`
    INSERT INTO model_packages (
      id, model_id, package_name, package_version, status,
      artifact_ids_json, manifest_json, release_note, storage_path,
      file_size_bytes, created_at, updated_at
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `).run(
    id, data.model_id, data.package_name, data.package_version, 'draft',
    JSON.stringify(data.artifact_ids || []), JSON.stringify(manifest),
    data.release_note || releaseNote, data.storage_path,
    totalSize, nowStr, nowStr
  );

  // Insert package-artifact links
  for (const art of artifacts) {
    const linkId = generateId();
    dbInstance.prepare(`
      INSERT INTO model_package_artifacts (
        id, package_id, artifact_id, artifact_role, relative_path,
        checksum, file_size_bytes, created_at
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    `).run(
      linkId, id, art.id, 'primary', art.path || '',
      '', art.file_size_bytes || 0, nowStr
    );
  }

  return {
    ok: true,
    package: {
      id,
      model_id: data.model_id,
      package_name: data.package_name,
      package_version: data.package_version,
      status: 'draft',
      artifact_ids_json: data.artifact_ids || [],
      manifest_json: manifest,
      release_note: data.release_note || releaseNote,
      file_size_bytes: totalSize,
      created_at: nowStr,
    },
  };
}

// ── Update ───────────────────────────────────────────────────────────────────

export async function updatePackage(id: string, body: any) {
  const dbInstance = getDatabase();
  const existing = dbInstance.prepare('SELECT * FROM model_packages WHERE id = ?').get(id);
  if (!existing) {
    return { ok: false, error: `Package ${id} not found` };
  }

  const validation = updatePackageSchema.safeParse(body);
  if (!validation.success) {
    return { ok: false, error: validation.error.message };
  }
  const data = validation.data;

  const fields: string[] = [];
  const values: any[] = [];

  if (data.package_name !== undefined) { fields.push('package_name = ?'); values.push(data.package_name); }
  if (data.package_version !== undefined) { fields.push('package_version = ?'); values.push(data.package_version); }
  if (data.status !== undefined) { fields.push('status = ?'); values.push(data.status); }
  if (data.release_note !== undefined) { fields.push('release_note = ?'); values.push(data.release_note); }
  if (data.storage_path !== undefined) { fields.push('storage_path = ?'); values.push(data.storage_path); }

  if (data.artifact_ids !== undefined) {
    fields.push('artifact_ids_json = ?');
    values.push(JSON.stringify(data.artifact_ids));

    // Update package-artifact links
    dbInstance.prepare('DELETE FROM model_package_artifacts WHERE package_id = ?').run(id);
    for (const artId of data.artifact_ids) {
      const art = dbInstance.prepare('SELECT * FROM artifacts WHERE id = ?').get(artId);
      if (art) {
        const linkId = generateId();
        dbInstance.prepare(`
          INSERT INTO model_package_artifacts (
            id, package_id, artifact_id, artifact_role, relative_path,
            checksum, file_size_bytes, created_at
          ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        `).run(
          linkId, id, artId, 'primary', (art as any).path || '',
          '', (art as any).file_size_bytes || 0, now()
        );
      }
    }

    // Regenerate manifest
    const pkg = existing as any;
    const artifacts = data.artifact_ids.map((aid: string) => {
      const a = dbInstance.prepare('SELECT * FROM artifacts WHERE id = ?').get(aid);
      return a || { id: aid, name: 'Unknown', artifact_type: 'unknown' };
    });
    const manifest = generateManifest(pkg, artifacts);
    fields.push('manifest_json = ?');
    values.push(JSON.stringify(manifest));
  }

  if (fields.length === 0) {
    return { ok: true, package: existing };
  }

  fields.push('updated_at = ?');
  values.push(now());
  values.push(id);
  dbInstance.prepare(`UPDATE model_packages SET ${fields.join(', ')} WHERE id = ?`).run(...values);

  const updated = dbInstance.prepare('SELECT * FROM model_packages WHERE id = ?').get(id);
  return {
    ok: true,
    package: {
      ...updated,
      artifact_ids_json: parseJsonField((updated as any).artifact_ids_json, 'artifact_ids_json'),
      manifest_json: parseJsonField((updated as any).manifest_json, 'manifest_json'),
    },
  };
}

// ── Delete ───────────────────────────────────────────────────────────────────

export async function deletePackage(id: string) {
  const dbInstance = getDatabase();
  const existing = dbInstance.prepare('SELECT * FROM model_packages WHERE id = ?').get(id);
  if (!existing) {
    return { ok: false, error: `Package ${id} not found` };
  }

  // Delete package-artifact links first
  dbInstance.prepare('DELETE FROM model_package_artifacts WHERE package_id = ?').run(id);
  dbInstance.prepare('DELETE FROM model_packages WHERE id = ?').run(id);
  return { ok: true, deleted: id };
}

// ── Get Package Artifacts ────────────────────────────────────────────────────

export async function getPackageArtifacts(id: string) {
  const dbInstance = getDatabase();
  const pkg = dbInstance.prepare('SELECT * FROM model_packages WHERE id = ?').get(id);
  if (!pkg) {
    return { ok: false, error: `Package ${id} not found` };
  }

  const links = dbInstance.prepare(`
    SELECT mpa.*, a.name, a.artifact_type, a.status, a.path, a.file_size_bytes
    FROM model_package_artifacts mpa
    LEFT JOIN artifacts a ON mpa.artifact_id = a.id
    WHERE mpa.package_id = ?
    ORDER BY mpa.created_at
  `).all(id);

  return {
    ok: true,
    package_id: id,
    artifacts: links,
    total: links.length,
  };
}

// ── Get Package Manifest ─────────────────────────────────────────────────────

export async function getPackageManifest(id: string) {
  const result = await getPackageById(id);
  if (!result.ok) {
    return result;
  }
  return {
    ok: true,
    package_id: id,
    manifest: result.package.manifest_json,
  };
}

// ── Get Package Release Note ────────────────────────────────────────────────

export async function getPackageReleaseNote(id: string) {
  const dbInstance = getDatabase();
  const pkg = dbInstance.prepare('SELECT release_note FROM model_packages WHERE id = ?').get(id) as any;
  if (!pkg) {
    return { ok: false, error: `Package ${id} not found` };
  }
  return {
    ok: true,
    package_id: id,
    release_note: pkg.release_note || '',
  };
}

// ── Detail with Relations ────────────────────────────────────────────────────

export async function getPackageDetail(id: string) {
  const result = await getPackageById(id);
  if (!result.ok) {
    return result;
  }

  const dbInstance = getDatabase();

  // Get model info
  const model = dbInstance.prepare('SELECT model_id, name, version FROM models WHERE model_id = ?').get(result.package.model_id);

  // Get artifacts
  const artifactsResult = await getPackageArtifacts(id);

  return {
    ok: true,
    package: result.package,
    model,
    artifacts: artifactsResult.artifacts,
    stats: {
      artifact_count: artifactsResult.artifacts.length,
      total_size: result.package.file_size_bytes || 0,
    },
  };
}

// ── Build Package (change status to building -> ready) ──────────────────────

export async function buildPackage(id: string) {
  const dbInstance = getDatabase();
  const pkg = dbInstance.prepare('SELECT * FROM model_packages WHERE id = ?').get(id) as any;
  if (!pkg) {
    return { ok: false, error: `Package ${id} not found` };
  }

  if (pkg.status !== 'draft') {
    return { ok: false, error: `Package must be in draft status to build (current: ${pkg.status})` };
  }

  // Update status to building
  dbInstance.prepare('UPDATE model_packages SET status = ?, updated_at = ? WHERE id = ?').run('building', now(), id);

  try {
    // Get artifacts
    const artifactIds = parseJsonField(pkg.artifact_ids_json, 'artifact_ids_json') as string[];
    const artifacts: any[] = [];
    let totalSize = 0;

    for (const artId of artifactIds) {
      const art = dbInstance.prepare('SELECT * FROM artifacts WHERE id = ?').get(artId) as any;
      if (art) {
        artifacts.push(art);
        totalSize += art.file_size_bytes || 0;
      }
    }

    // Generate manifest
    const manifest = {
      package: {
        id: pkg.id,
        name: pkg.package_name,
        version: pkg.package_version,
        model_id: pkg.model_id,
        created_at: pkg.created_at,
      },
      artifacts: artifacts.map((a: any) => ({
        id: a.id,
        name: a.name,
        type: a.artifact_type,
        format: a.format,
        framework: a.framework,
        path: a.path,
        size_bytes: a.file_size_bytes,
        size_mb: a.file_size_bytes ? Math.round(a.file_size_bytes / 1024 / 1024 * 100) / 100 : 0,
      })),
      metadata: {
        generated_at: now(),
        generator: 'AGI Factory v1.6.0',
        total_size_bytes: totalSize,
        total_size_mb: Math.round(totalSize / 1024 / 1024 * 100) / 100,
        artifact_count: artifacts.length,
      },
    };

    // Generate release note
    const releaseNote = generateReleaseNote(pkg, artifacts);

    // Create staging directory
    const fs = await import('fs/promises');
    const path = await import('path');
    const crypto = await import('crypto');

    const stagingDir = path.join(process.cwd(), 'packages', 'storage', 'staging', id);
    const releaseDir = path.join(process.cwd(), 'packages', 'storage', 'releases', id);

    // Ensure directories exist
    await fs.mkdir(stagingDir, { recursive: true });
    await fs.mkdir(releaseDir, { recursive: true });

    // Write manifest.json
    const manifestPath = path.join(releaseDir, 'manifest.json');
    await fs.writeFile(manifestPath, JSON.stringify(manifest, null, 2), 'utf-8');

    // Write release-note.md
    const releaseNotePath = path.join(releaseDir, 'release-note.md');
    await fs.writeFile(releaseNotePath, releaseNote, 'utf-8');

    // Generate checksums
    const checksums: { file: string; sha256: string; size: number }[] = [];

    // Add manifest checksum
    const manifestContent = await fs.readFile(manifestPath);
    const manifestHash = crypto.createHash('sha256').update(manifestContent).digest('hex');
    checksums.push({ file: 'manifest.json', sha256: manifestHash, size: manifestContent.length });

    // Add release note checksum
    const rnContent = await fs.readFile(releaseNotePath);
    const rnHash = crypto.createHash('sha256').update(rnContent).digest('hex');
    checksums.push({ file: 'release-note.md', sha256: rnHash, size: rnContent.length });

    // Process artifacts (copy/link files if they exist)
    const artifactsDir = path.join(releaseDir, 'artifacts');
    await fs.mkdir(artifactsDir, { recursive: true });

    for (const art of artifacts) {
      if (art.path) {
        // Try to find the actual file
        const possiblePaths = [
          art.path,
          path.join(process.cwd(), art.path),
          path.join(process.cwd(), 'models', art.path),
          path.join(process.cwd(), 'output', art.path),
        ];

        let sourceFile: string | null = null;
        for (const p of possiblePaths) {
          try {
            await fs.access(p);
            sourceFile = p;
            break;
          } catch {
            // File not found at this path
          }
        }

        if (sourceFile) {
          // Copy file to release directory
          const destPath = path.join(artifactsDir, `${art.name.replace(/[^a-zA-Z0-9._-]/g, '_')}.${art.format || 'bin'}`);
          await fs.copyFile(sourceFile, destPath);

          // Calculate checksum
          const fileContent = await fs.readFile(destPath);
          const fileHash = crypto.createHash('sha256').update(fileContent).digest('hex');
          checksums.push({
            file: path.basename(destPath),
            sha256: fileHash,
            size: fileContent.length,
          });

          // Update artifact link with checksum
          dbInstance.prepare(`
            UPDATE model_package_artifacts 
            SET checksum = ?, file_size_bytes = ?, relative_path = ?
            WHERE package_id = ? AND artifact_id = ?
          `).run(fileHash, fileContent.length, path.basename(destPath), id, art.id);
        }
      }
    }

    // Write checksums.json
    const checksumsPath = path.join(releaseDir, 'checksums.json');
    await fs.writeFile(checksumsPath, JSON.stringify(checksums, null, 2), 'utf-8');

    // Calculate overall package checksum
    const packageHash = crypto.createHash('sha256')
      .update(JSON.stringify(checksums))
      .digest('hex');

    // Update package in database
    const storagePath = `apps/local-api/packages/storage/releases/${id}`;
    dbInstance.prepare(`
      UPDATE model_packages 
      SET status = ?, manifest_json = ?, release_note = ?, storage_path = ?,
          file_size_bytes = ?, checksum = ?, updated_at = ?
      WHERE id = ?
    `).run(
      'ready',
      JSON.stringify(manifest),
      releaseNote,
      storagePath,
      totalSize,
      packageHash,
      now(),
      id
    );

    // Audit: build success
    await logAudit({
      category: 'package',
      action: 'build',
      target: `${pkg.package_name}@${pkg.package_version}`,
      result: 'success',
      detail: {
        package_id: id,
        model_id: pkg.model_id,
        files: checksums.length,
        total_size_mb: Math.round(totalSize / 1024 / 1024 * 100) / 100,
        files_created: ['manifest.json', 'release-note.md', 'checksums.json']
      }
    });

    const updated = dbInstance.prepare('SELECT * FROM model_packages WHERE id = ?').get(id);
    return {
      ok: true,
      package: {
        ...updated,
        artifact_ids_json: parseJsonField((updated as any).artifact_ids_json, 'artifact_ids_json'),
        manifest_json: parseJsonField((updated as any).manifest_json, 'manifest_json'),
      },
      build_result: {
        storage_path: storagePath,
        files: checksums,
        total_size_bytes: totalSize,
        total_size_mb: Math.round(totalSize / 1024 / 1024 * 100) / 100,
      },
    };
  } catch (error: any) {
    // Mark as failed
    dbInstance.prepare('UPDATE model_packages SET status = ?, updated_at = ? WHERE id = ?').run('failed', now(), id);
    await logAudit({
      category: 'package',
      action: 'build',
      target: `${pkg.package_name}@${pkg.package_version}`,
      result: 'failed',
      detail: { package_id: id, error: error.message }
    });
    return {
      ok: false,
      error: `Build failed: ${error.message}`,
      package: pkg,
    };
  }
}

// ── Publish Package ──────────────────────────────────────────────────────────

export async function publishPackage(id: string) {
  const dbInstance = getDatabase();
  const pkg = dbInstance.prepare('SELECT * FROM model_packages WHERE id = ?').get(id) as any;
  if (!pkg) {
    return { ok: false, error: `Package ${id} not found` };
  }

  if (pkg.status !== 'ready') {
    return { ok: false, error: `Package must be built (status=ready) before publishing (current: ${pkg.status})` };
  }

  try {
    const fs = await import('fs/promises');
    const path = await import('path');

    // Verify release files exist
    const releaseDir = path.join(process.cwd(), 'packages', 'storage', 'releases', id);
    const manifestPath = path.join(releaseDir, 'manifest.json');
    const checksumsPath = path.join(releaseDir, 'checksums.json');

    try {
      await fs.access(manifestPath);
      await fs.access(checksumsPath);
    } catch {
      return { ok: false, error: 'Release files not found. Please rebuild the package.' };
    }

    // Verify checksums
    const checksumsContent = await fs.readFile(checksumsPath, 'utf-8');
    const checksums = JSON.parse(checksumsContent);

    const verifiedFiles: string[] = [];
    const failedFiles: string[] = [];

    for (const entry of checksums) {
      const filePath = path.join(releaseDir, entry.file);
      try {
        await fs.access(filePath);
        verifiedFiles.push(entry.file);
      } catch {
        failedFiles.push(entry.file);
      }
    }

    if (failedFiles.length > 0) {
      await logAudit({
        category: 'package',
        action: 'publish',
        target: `${pkg.package_name}@${pkg.package_version}`,
        result: 'failed',
        detail: { package_id: id, reason: 'missing_files', files: failedFiles }
      });
      return {
        ok: false,
        error: `Missing files: ${failedFiles.join(', ')}`,
      };
    }

    // Update status to published
    const publishedAt = now();
    dbInstance.prepare(`
      UPDATE model_packages 
      SET status = ?, updated_at = ?
      WHERE id = ?
    `).run('published', publishedAt, id);

    // Write publish record
    const publishRecord = {
      package_id: id,
      published_at: publishedAt,
      verified_files: verifiedFiles,
      checksum_count: checksums.length,
    };

    const publishRecordPath = path.join(releaseDir, 'publish-record.json');
    await fs.writeFile(publishRecordPath, JSON.stringify(publishRecord, null, 2), 'utf-8');

    // Audit: publish success
    await logAudit({
      category: 'package',
      action: 'publish',
      target: `${pkg.package_name}@${pkg.package_version}`,
      result: 'success',
      detail: {
        package_id: id,
        model_id: pkg.model_id,
        verified_files: verifiedFiles.length,
        consistency_check: {
          manifest_json: true,
          checksums_json: true,
          all_artifacts: verifiedFiles.length === checksums.length
        },
        published_at: publishedAt,
        storage_path: pkg.storage_path
      }
    });

    const updated = dbInstance.prepare('SELECT * FROM model_packages WHERE id = ?').get(id);
    return {
      ok: true,
      package: {
        ...updated,
        artifact_ids_json: parseJsonField((updated as any).artifact_ids_json, 'artifact_ids_json'),
        manifest_json: parseJsonField((updated as any).manifest_json, 'manifest_json'),
      },
      publish_result: {
        published_at: publishedAt,
        verified_files: verifiedFiles.length,
        storage_path: pkg.storage_path,
      },
    };
  } catch (error: any) {
    await logAudit({
      category: 'package',
      action: 'publish',
      target: `${pkg.package_name}@${pkg.package_version}`,
      result: 'failed',
      detail: { package_id: id, error: error.message }
    });
    return {
      ok: false,
      error: `Publish failed: ${error.message}`,
    };
  }
}

// ── Helper: Generate Release Note (2-param, for buildPackage) ─────────────────

function generateReleaseNote(pkg: any, artifacts: any[]): string {
  const lines: string[] = [];
  const totalSize = artifacts.reduce((sum, a) => sum + (a.file_size_bytes || 0), 0);

  lines.push(`# ${pkg.package_name} v${pkg.package_version}`);
  lines.push('');
  lines.push(`**Published:** ${now()}`);
  lines.push(`**Model ID:** ${pkg.model_id}`);
  lines.push(`**Total Size:** ${Math.round(totalSize / 1024 / 1024 * 100) / 100} MB`);
  lines.push('');
  lines.push('## Contents');
  lines.push('');

  artifacts.forEach((a: any, i: number) => {
    lines.push(`${i + 1}. **${a.name}** (${a.artifact_type})`);
    if (a.framework) lines.push(`   - Framework: ${a.framework}`);
    if (a.format) lines.push(`   - Format: ${a.format}`);
    if (a.file_size_bytes) {
      lines.push(`   - Size: ${Math.round(a.file_size_bytes / 1024 / 1024 * 100) / 100} MB`);
    }
    lines.push('');
  });

  lines.push('## Checksums');
  lines.push('');
  lines.push('See `checksums.json` for SHA256 hashes of all files.');
  lines.push('');
  lines.push('---');
  lines.push('*Generated by AGI Factory*');

  return lines.join('\n');
}

// ── Retry Operations ─────────────────────────────────────────────────────────

export async function retryPackageBuild(id: string): Promise<any> {
  const dbInstance = getDatabase();
  const pkg = dbInstance.prepare('SELECT * FROM model_packages WHERE id = ?').get(id) as any;
  if (!pkg) return { ok: false, error: `Package ${id} not found` };

  const lastFailure = dbInstance.prepare(
    `SELECT * FROM audit_logs WHERE category = 'package' AND action = 'build' AND target LIKE ? AND result = 'failed' ORDER BY created_at DESC LIMIT 1`
  ).get(`%${pkg.package_name}%`);

  const retryId = await logAudit({
    category: 'package',
    action: 'retry_build',
    target: `${pkg.package_name}@${pkg.package_version}`,
    result: 'partial',
    detail: {
      package_id: id,
      model_id: pkg.model_id,
      original_failure: lastFailure ? {
        at: lastFailure.created_at,
        error: lastFailure.detail_json ? JSON.parse(String(lastFailure.detail_json)).error : 'unknown'
      } : null
    }
  });

  const result = await buildPackage(id);

  const detailUpdate = {
    ...(lastFailure ? { original_failure: JSON.parse(String(lastFailure.detail_json || '{}')) } : {}),
    retry_result: result.ok ? 'build succeeded' : result.error
  };
  dbInstance.prepare(
    `UPDATE audit_logs SET result = ?, detail_json = ? WHERE id = ?`
  ).run(result.ok ? 'success' : 'failed', JSON.stringify(detailUpdate), retryId);

  return result;
}

export async function retryPackagePublish(id: string): Promise<any> {
  const dbInstance = getDatabase();
  const pkg = dbInstance.prepare('SELECT * FROM model_packages WHERE id = ?').get(id) as any;
  if (!pkg) return { ok: false, error: `Package ${id} not found` };

  const lastFailure = dbInstance.prepare(
    `SELECT * FROM audit_logs WHERE category = 'package' AND action = 'publish' AND target LIKE ? AND result = 'failed' ORDER BY created_at DESC LIMIT 1`
  ).get(`%${pkg.package_name}%`);

  const retryId = await logAudit({
    category: 'package',
    action: 'retry_publish',
    target: `${pkg.package_name}@${pkg.package_version}`,
    result: 'partial',
    detail: {
      package_id: id,
      original_failure: lastFailure ? {
        at: lastFailure.created_at,
        error: lastFailure.detail_json ? JSON.parse(String(lastFailure.detail_json)).error : 'unknown'
      } : null
    }
  });

  const result = await publishPackage(id);

  const detailUpdate = {
    ...(lastFailure ? { original_failure: JSON.parse(String(lastFailure.detail_json || '{}')) } : {}),
    retry_result: result.ok ? 'publish succeeded' : result.error
  };
  dbInstance.prepare(
    `UPDATE audit_logs SET result = ?, detail_json = ? WHERE id = ?`
  ).run(result.ok ? 'success' : 'failed', JSON.stringify(detailUpdate), retryId);

  return result;
}
