#!/usr/bin/env python3
"""
Evaluation Report Builder for AGI Model Factory
v3.4.0

Generates:
- metrics.json
- eval_summary.md
- eval_manifest.json
"""

import json
import os
from datetime import datetime
from pathlib import Path

def generate_metrics_json(metrics, output_dir):
    """Generate metrics.json"""
    metrics_data = {
        'timestamp': datetime.now().isoformat(),
        'version': '3.4.0',
        'overall': {
            'precision': float(metrics.get('precision', 0)),
            'recall': float(metrics.get('recall', 0)),
            'map50': float(metrics.get('map50', 0)),
            'map50_95': float(metrics.get('map50_95', 0)),
            'fitness': float(metrics.get('fitness', 0)),
        },
        'per_class': [],
        'curves': {},
    }
    
    # Per-class metrics
    if metrics.get('per_class'):
        for cls_name, cls_metrics in metrics['per_class'].items():
            metrics_data['per_class'].append({
                'class_name': cls_name,
                'precision': float(cls_metrics.get('precision', 0)),
                'recall': float(cls_metrics.get('recall', 0)),
                'ap50': float(cls_metrics.get('ap50', 0)),
                'ap50_95': float(cls_metrics.get('ap50_95', 0)),
            })
    
    output_path = os.path.join(output_dir, 'metrics.json')
    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
    with open(output_path, 'w') as f:
        json.dump(metrics_data, f, indent=2)
    
    return output_path

def generate_eval_summary(metrics, config, output_dir):
    """Generate eval_summary.md"""
    
    overall = metrics.get('overall', {})
    per_class = metrics.get('per_class', {})
    
    summary = f"""# YOLO Evaluation Summary

**Generated**: {datetime.now().isoformat()}
**Version**: 3.4.0

## Configuration

| Parameter | Value |
|-----------|-------|
| Dataset | {config.get('dataset_yaml', 'N/A')} |
| Model | {config.get('weights', 'N/A')} |
| Image Size | {config.get('imgsz', 640)} |
| Batch Size | {config.get('batch', 16)} |
| Device | {config.get('device', 'N/A')} |

## Overall Metrics

| Metric | Value |
|--------|-------|
| Precision | {overall.get('precision', 0):.4f} |
| Recall | {overall.get('recall', 0):.4f} |
| mAP@0.5 | {overall.get('map50', 0):.4f} |
| mAP@0.5:0.95 | {overall.get('map50_95', 0):.4f} |
| Fitness | {overall.get('fitness', 0):.4f} |

## Per-Class Metrics

| Class | Precision | Recall | AP@0.5 | AP@0.5:0.95 |
|-------|-----------|--------|--------|-------------|
"""
    
    for cls_name, cls_metrics in per_class.items():
        summary += f"| {cls_name} | {cls_metrics.get('precision', 0):.4f} | {cls_metrics.get('recall', 0):.4f} | {cls_metrics.get('ap50', 0):.4f} | {cls_metrics.get('ap50_95', 0):.4f} |\n"
    
    if not per_class:
        summary += "| — | — | — | — | — |\n"
    
    summary += f"""
## Artifacts

- Metrics: `metrics.json`
- Manifest: `eval_manifest.json`

---
*Generated by AGI Model Factory v3.4.0*
"""
    
    output_path = os.path.join(output_dir, 'eval_summary.md')
    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(summary)
    
    return output_path

def generate_eval_manifest(config, metrics, output_dir, eval_time=None, sample_count=0, class_count=0):
    """Generate eval_manifest.json"""
    
    manifest = {
        'timestamp': datetime.now().isoformat(),
        'version': '3.4.0',
        'config': config,
        'metrics': {
            'precision': float(metrics.get('precision', 0)),
            'recall': float(metrics.get('recall', 0)),
            'map50': float(metrics.get('map50', 0)),
            'map50_95': float(metrics.get('map50_95', 0)),
            'fitness': float(metrics.get('fitness', 0)),
            'sample_count': int(sample_count),
            'class_count': int(class_count),
        },
        'artifacts': {
            'metrics_json': 'metrics.json',
            'eval_summary': 'eval_summary.md',
        },
        'eval_time_seconds': float(eval_time or 0),
    }
    
    output_path = os.path.join(output_dir, 'eval_manifest.json')
    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
    with open(output_path, 'w') as f:
        json.dump(manifest, f, indent=2, default=str)
    
    return output_path

def build_reports(metrics, config, output_dir, eval_time=None, sample_count=0, class_count=0):
    """Build all evaluation reports"""
    
    # metrics.json
    metrics_path = generate_metrics_json(metrics, output_dir)
    
    # eval_summary.md
    summary_path = generate_eval_summary(metrics, config, output_dir)
    
    # eval_manifest.json
    manifest_path = generate_eval_manifest(config, metrics, output_dir, eval_time, sample_count, class_count)
    
    return {
        'metrics_json': metrics_path,
        'eval_summary': summary_path,
        'eval_manifest': manifest_path,
    }

def main():
    import argparse
    parser = argparse.ArgumentParser(description='Build evaluation reports')
    parser.add_argument('--metrics', type=str, required=True, help='JSON string or path to metrics')
    parser.add_argument('--config', type=str, required=True, help='JSON string or path to config')
    parser.add_argument('--output-dir', type=str, required=True, help='Output directory')
    parser.add_argument('--eval-time', type=float, help='Evaluation time in seconds')
    parser.add_argument('--sample-count', type=int, default=0, help='Number of samples')
    parser.add_argument('--class-count', type=int, default=0, help='Number of classes')
    args = parser.parse_args()
    
    # Parse metrics (file path or JSON string)
    if os.path.exists(args.metrics):
        with open(args.metrics) as f:
            metrics = json.load(f)
    else:
        metrics = json.loads(args.metrics)
    
    # Parse config (file path or JSON string)
    if os.path.exists(args.config):
        with open(args.config) as f:
            config = json.load(f)
    else:
        config = json.loads(args.config)
    
    reports = build_reports(
        metrics=metrics,
        config=config,
        output_dir=args.output_dir,
        eval_time=args.eval_time,
        sample_count=args.sample_count,
        class_count=args.class_count,
    )
    
    print(json.dumps(reports, indent=2))
    return reports

if __name__ == '__main__':
    main()
