export type EvidenceType =
  | 'registry_snapshot'
  | 'validator_summary'
  | 'dry_run_plan'
  | 'audit_preview'
  | 'approval_request'
  | 'human_note'
  | 'report_path'
  | 'git_commit'
  | 'screenshot'
  | 'validation_output'
  | 'rollback_plan'
  | 'stage_gate_state';

export type EvidenceSource =
  | 'runtime_registry'
  | 'dry_run_plan'
  | 'audit_log'
  | 'human_approval'
  | 'governance_state'
  | 'permission_evaluator'
  | 'connector_center'
  | 'validation_gate'
  | 'git'
  | 'human_operator';

export type EvidenceSensitivity =
  | 'public_metadata'
  | 'internal_status'
  | 'redacted_sensitive'
  | 'forbidden_secret';

export type EvidenceRetention =
  | 'preview_only'
  | 'report_reference'
  | 'future_audit_store'
  | 'forbidden_no_store';

export type EvidenceRisk = 'low' | 'medium' | 'high' | 'critical';

export interface EvidenceSchemaItem {
  id: string;
  label: string;
  evidenceType: EvidenceType;
  source: EvidenceSource;
  sensitivity: EvidenceSensitivity;
  retention: EvidenceRetention;
  risk: EvidenceRisk;
  allowedNow: boolean;
  captureNow: boolean;
  writeNow: boolean;
  requiresRedaction: boolean;
  requiresHumanReview: boolean;
  requiresStageC: boolean;
  requiresDbWrite: boolean;
  containsSecretMaterial: boolean;
  containsTokenLikeMaterial: boolean;
  allowedFields: string[];
  forbiddenFields: string[];
  redactionRules: string[];
  attestationFields: string[];
  relatedApprovalItem?: string;
  relatedGovernanceTransition?: string;
  relatedAuditItem?: string;
  relatedRollbackItem?: string;
  gates: string[];
  blockedActions: string[];
  reason: string;
  nextAction: string;
}

const EVIDENCE_SCHEMA_ITEMS: EvidenceSchemaItem[] = [
  {
    id: 'runtime-registry-snapshot',
    label: 'Runtime Registry Snapshot',
    evidenceType: 'registry_snapshot',
    source: 'runtime_registry',
    sensitivity: 'internal_status',
    retention: 'preview_only',
    risk: 'low',
    allowedNow: true,
    captureNow: false,
    writeNow: false,
    requiresRedaction: false,
    requiresHumanReview: false,
    requiresStageC: false,
    requiresDbWrite: false,
    containsSecretMaterial: false,
    containsTokenLikeMaterial: false,
    allowedFields: ['id', 'label', 'risk', 'allowedNow', 'gates', 'blockedActions', 'reason', 'nextAction'],
    forbiddenFields: ['token', 'apiKey', 'password', 'privateKey', 'credential', 'secret'],
    redactionRules: ['No redaction needed — public metadata only'],
    attestationFields: ['id', 'label', 'risk', 'allowedNow'],
    gates: ['readonly_only'],
    blockedActions: ['capture', 'write', 'submit'],
    reason: 'Runtime registry preview is a readonly metadata view',
    nextAction: 'View runtime registry preview page for details',
  },
  {
    id: 'runtime-validator-summary',
    label: 'Runtime Validator Summary',
    evidenceType: 'validator_summary',
    source: 'runtime_registry',
    sensitivity: 'internal_status',
    retention: 'preview_only',
    risk: 'low',
    allowedNow: true,
    captureNow: false,
    writeNow: false,
    requiresRedaction: false,
    requiresHumanReview: false,
    requiresStageC: false,
    requiresDbWrite: false,
    containsSecretMaterial: false,
    containsTokenLikeMaterial: false,
    allowedFields: ['blocking', 'warning', 'info', 'pass'],
    forbiddenFields: ['token', 'apiKey', 'password', 'privateKey', 'credential'],
    redactionRules: ['No redaction needed — validation summary only'],
    attestationFields: ['blocking', 'pass'],
    gates: ['readonly_only'],
    blockedActions: ['capture', 'write', 'submit'],
    reason: 'Validator summary is derived from static registry data',
    nextAction: 'View runtime registry validator for details',
  },
  {
    id: 'dry-run-plan-preview-evidence',
    label: 'Dry-Run Plan Preview Evidence',
    evidenceType: 'dry_run_plan',
    source: 'dry_run_plan',
    sensitivity: 'internal_status',
    retention: 'preview_only',
    risk: 'low',
    allowedNow: true,
    captureNow: false,
    writeNow: false,
    requiresRedaction: false,
    requiresHumanReview: false,
    requiresStageC: false,
    requiresDbWrite: false,
    containsSecretMaterial: false,
    containsTokenLikeMaterial: false,
    allowedFields: ['id', 'planType', 'risk', 'allowedNow', 'gates', 'blockedActions'],
    forbiddenFields: ['token', 'apiKey', 'password', 'privateKey', 'credential', 'secret'],
    redactionRules: ['No redaction needed — plan metadata only'],
    attestationFields: ['id', 'planType', 'risk'],
    gates: ['readonly_only', 'no_dry_run_execution'],
    blockedActions: ['execute_dry_run', 'capture', 'write'],
    reason: 'Dry-run plan preview is a readonly metadata view',
    nextAction: 'View dry-run plan preview page for details',
  },
  {
    id: 'dry-run-validator-summary',
    label: 'Dry-Run Validator Summary',
    evidenceType: 'validator_summary',
    source: 'dry_run_plan',
    sensitivity: 'internal_status',
    retention: 'preview_only',
    risk: 'low',
    allowedNow: true,
    captureNow: false,
    writeNow: false,
    requiresRedaction: false,
    requiresHumanReview: false,
    requiresStageC: false,
    requiresDbWrite: false,
    containsSecretMaterial: false,
    containsTokenLikeMaterial: false,
    allowedFields: ['blocking', 'warning', 'info', 'pass'],
    forbiddenFields: ['token', 'apiKey', 'password', 'privateKey', 'credential'],
    redactionRules: ['No redaction needed — validation summary only'],
    attestationFields: ['blocking', 'pass'],
    gates: ['readonly_only'],
    blockedActions: ['capture', 'write', 'submit'],
    reason: 'Dry-run validator summary is derived from static plan data',
    nextAction: 'View dry-run plan validator for details',
  },
  {
    id: 'audit-log-preview-evidence',
    label: 'Audit Log Preview Evidence',
    evidenceType: 'audit_preview',
    source: 'audit_log',
    sensitivity: 'redacted_sensitive',
    retention: 'preview_only',
    risk: 'medium',
    allowedNow: true,
    captureNow: false,
    writeNow: false,
    requiresRedaction: true,
    requiresHumanReview: false,
    requiresStageC: false,
    requiresDbWrite: false,
    containsSecretMaterial: false,
    containsTokenLikeMaterial: false,
    allowedFields: ['id', 'action', 'entityType', 'entityId', 'timestamp', 'severity', 'category', 'summary'],
    forbiddenFields: ['fullPayload', 'token', 'apiKey', 'password', 'privateKey', 'credential', 'rawInput', 'rawOutput', 'secret'],
    redactionRules: ['Redact full payload — show summary only', 'Redact raw input/output — show metadata only'],
    attestationFields: ['id', 'action', 'entityType', 'timestamp', 'severity'],
    gates: ['readonly_only', 'redaction_required'],
    blockedActions: ['view_full_payload', 'capture_raw', 'write', 'submit'],
    reason: 'Audit log preview shows redacted metadata — full payload requires future_audit_store',
    nextAction: 'View audit log preview page for redacted details',
  },
  {
    id: 'audit-validator-summary',
    label: 'Audit Log Validator Summary',
    evidenceType: 'validator_summary',
    source: 'audit_log',
    sensitivity: 'internal_status',
    retention: 'preview_only',
    risk: 'low',
    allowedNow: true,
    captureNow: false,
    writeNow: false,
    requiresRedaction: false,
    requiresHumanReview: false,
    requiresStageC: false,
    requiresDbWrite: false,
    containsSecretMaterial: false,
    containsTokenLikeMaterial: false,
    allowedFields: ['blocking', 'warning', 'info', 'pass'],
    forbiddenFields: ['token', 'apiKey', 'password', 'privateKey', 'credential'],
    redactionRules: ['No redaction needed — validation summary only'],
    attestationFields: ['blocking', 'pass'],
    gates: ['readonly_only'],
    blockedActions: ['capture', 'write', 'submit'],
    reason: 'Audit validator summary is derived from static audit data',
    nextAction: 'View audit log validator for details',
  },
  {
    id: 'human-approval-request-preview',
    label: 'Human Approval Request Preview',
    evidenceType: 'approval_request',
    source: 'human_approval',
    sensitivity: 'redacted_sensitive',
    retention: 'preview_only',
    risk: 'medium',
    allowedNow: true,
    captureNow: false,
    writeNow: false,
    requiresRedaction: true,
    requiresHumanReview: true,
    requiresStageC: false,
    requiresDbWrite: false,
    containsSecretMaterial: false,
    containsTokenLikeMaterial: false,
    allowedFields: ['id', 'requestKind', 'state', 'decision', 'risk', 'allowedNow', 'gates', 'blockedActions'],
    forbiddenFields: ['token', 'apiKey', 'password', 'privateKey', 'credential', 'secret', 'fullEvidence'],
    redactionRules: ['Redact full evidence chain — show summary only', 'Redact human reviewer identity if present'],
    attestationFields: ['id', 'requestKind', 'state', 'decision', 'risk'],
    relatedApprovalItem: 'request-human-review-preview',
    gates: ['readonly_only', 'redaction_required', 'no_approval_queue'],
    blockedActions: ['approve', 'reject', 'archive', 'write_evidence', 'capture_evidence'],
    reason: 'Approval request preview shows redacted workflow state — no queue creation, no candidate processing',
    nextAction: 'View human approval workflow preview page for details',
  },
  {
    id: 'human-approval-validator-summary',
    label: 'Human Approval Validator Summary',
    evidenceType: 'validator_summary',
    source: 'human_approval',
    sensitivity: 'internal_status',
    retention: 'preview_only',
    risk: 'low',
    allowedNow: true,
    captureNow: false,
    writeNow: false,
    requiresRedaction: false,
    requiresHumanReview: false,
    requiresStageC: false,
    requiresDbWrite: false,
    containsSecretMaterial: false,
    containsTokenLikeMaterial: false,
    allowedFields: ['blocking', 'warning', 'info', 'pass'],
    forbiddenFields: ['token', 'apiKey', 'password', 'privateKey', 'credential'],
    redactionRules: ['No redaction needed — validation summary only'],
    attestationFields: ['blocking', 'pass'],
    gates: ['readonly_only'],
    blockedActions: ['capture', 'write', 'submit'],
    reason: 'Human approval validator summary is derived from static registry data',
    nextAction: 'View human approval validator for details',
  },
  {
    id: 'governance-state-snapshot',
    label: 'Governance State Snapshot',
    evidenceType: 'stage_gate_state',
    source: 'governance_state',
    sensitivity: 'internal_status',
    retention: 'preview_only',
    risk: 'medium',
    allowedNow: true,
    captureNow: false,
    writeNow: false,
    requiresRedaction: false,
    requiresHumanReview: false,
    requiresStageC: false,
    requiresDbWrite: false,
    containsSecretMaterial: false,
    containsTokenLikeMaterial: false,
    allowedFields: ['id', 'state', 'risk', 'transitions', 'allowedNow', 'gates', 'blockedActions'],
    forbiddenFields: ['token', 'apiKey', 'password', 'privateKey', 'credential'],
    redactionRules: ['No redaction needed — state machine metadata only'],
    attestationFields: ['id', 'state', 'risk', 'transitions'],
    relatedGovernanceTransition: 'governance-state-machine-preview',
    gates: ['readonly_only', 'no_state_transition'],
    blockedActions: ['execute_transition', 'capture', 'write'],
    reason: 'Governance state snapshot is a readonly state machine view',
    nextAction: 'View governance state machine preview page for details',
  },
  {
    id: 'governance-state-validator-summary',
    label: 'Governance State Validator Summary',
    evidenceType: 'validator_summary',
    source: 'governance_state',
    sensitivity: 'internal_status',
    retention: 'preview_only',
    risk: 'low',
    allowedNow: true,
    captureNow: false,
    writeNow: false,
    requiresRedaction: false,
    requiresHumanReview: false,
    requiresStageC: false,
    requiresDbWrite: false,
    containsSecretMaterial: false,
    containsTokenLikeMaterial: false,
    allowedFields: ['blocking', 'warning', 'info', 'pass'],
    forbiddenFields: ['token', 'apiKey', 'password', 'privateKey', 'credential'],
    redactionRules: ['No redaction needed — validation summary only'],
    attestationFields: ['blocking', 'pass'],
    gates: ['readonly_only'],
    blockedActions: ['capture', 'write', 'submit'],
    reason: 'Governance state validator summary is derived from static state data',
    nextAction: 'View governance state validator for details',
  },
  {
    id: 'permission-evaluator-summary',
    label: 'Permission Evaluator Summary',
    evidenceType: 'validation_output',
    source: 'permission_evaluator',
    sensitivity: 'internal_status',
    retention: 'preview_only',
    risk: 'low',
    allowedNow: true,
    captureNow: false,
    writeNow: false,
    requiresRedaction: false,
    requiresHumanReview: false,
    requiresStageC: false,
    requiresDbWrite: false,
    containsSecretMaterial: false,
    containsTokenLikeMaterial: false,
    allowedFields: ['blocking', 'warning', 'info', 'pass', 'ruleCount', 'denyCount'],
    forbiddenFields: ['token', 'apiKey', 'password', 'privateKey', 'credential'],
    redactionRules: ['No redaction needed — evaluator summary only'],
    attestationFields: ['blocking', 'pass', 'ruleCount'],
    gates: ['readonly_only'],
    blockedActions: ['capture', 'write', 'submit'],
    reason: 'Permission evaluator summary is derived from static rule data',
    nextAction: 'View permission evaluator preview page for details',
  },
  {
    id: 'connector-center-readiness-snapshot',
    label: 'Connector Center Readiness Snapshot',
    evidenceType: 'registry_snapshot',
    source: 'connector_center',
    sensitivity: 'internal_status',
    retention: 'preview_only',
    risk: 'low',
    allowedNow: true,
    captureNow: false,
    writeNow: false,
    requiresRedaction: false,
    requiresHumanReview: false,
    requiresStageC: false,
    requiresDbWrite: false,
    containsSecretMaterial: false,
    containsTokenLikeMaterial: false,
    allowedFields: ['id', 'connectorType', 'readiness', 'gates', 'blockedActions'],
    forbiddenFields: ['token', 'apiKey', 'password', 'privateKey', 'credential', 'connectionString'],
    redactionRules: ['No redaction needed — readiness metadata only'],
    attestationFields: ['id', 'connectorType', 'readiness'],
    gates: ['readonly_only'],
    blockedActions: ['capture', 'write', 'connect', 'submit'],
    reason: 'Connector readiness snapshot is a readonly metadata view',
    nextAction: 'View connector center page for details',
  },
  {
    id: 'report-path-reference',
    label: 'Report Path Reference',
    evidenceType: 'report_path',
    source: 'validation_gate',
    sensitivity: 'public_metadata',
    retention: 'report_reference',
    risk: 'low',
    allowedNow: true,
    captureNow: false,
    writeNow: false,
    requiresRedaction: false,
    requiresHumanReview: false,
    requiresStageC: false,
    requiresDbWrite: false,
    containsSecretMaterial: false,
    containsTokenLikeMaterial: false,
    allowedFields: ['path', 'type', 'createdAt'],
    forbiddenFields: ['token', 'apiKey', 'password', 'privateKey', 'credential', 'secret'],
    redactionRules: ['No redaction needed — file path only'],
    attestationFields: ['path', 'type'],
    gates: ['readonly_only'],
    blockedActions: ['capture', 'write', 'submit'],
    reason: 'Report path reference is public metadata',
    nextAction: 'Navigate to the referenced report path',
  },
  {
    id: 'git-commit-reference',
    label: 'Git Commit Reference',
    evidenceType: 'git_commit',
    source: 'git',
    sensitivity: 'public_metadata',
    retention: 'report_reference',
    risk: 'low',
    allowedNow: true,
    captureNow: false,
    writeNow: false,
    requiresRedaction: false,
    requiresHumanReview: false,
    requiresStageC: false,
    requiresDbWrite: false,
    containsSecretMaterial: false,
    containsTokenLikeMaterial: false,
    allowedFields: ['hash', 'message', 'author', 'date'],
    forbiddenFields: ['token', 'apiKey', 'password', 'privateKey', 'credential', 'secret'],
    redactionRules: ['No redaction needed — commit metadata only'],
    attestationFields: ['hash', 'message'],
    gates: ['readonly_only'],
    blockedActions: ['capture', 'write', 'submit'],
    reason: 'Git commit reference is public metadata',
    nextAction: 'View the commit for details',
  },
  {
    id: 'validation-output-reference',
    label: 'Validation Output Reference',
    evidenceType: 'validation_output',
    source: 'validation_gate',
    sensitivity: 'internal_status',
    retention: 'report_reference',
    risk: 'low',
    allowedNow: true,
    captureNow: false,
    writeNow: false,
    requiresRedaction: false,
    requiresHumanReview: false,
    requiresStageC: false,
    requiresDbWrite: false,
    containsSecretMaterial: false,
    containsTokenLikeMaterial: false,
    allowedFields: ['gate', 'result', 'blocking', 'warning', 'info'],
    forbiddenFields: ['token', 'apiKey', 'password', 'privateKey', 'credential', 'secret'],
    redactionRules: ['No redaction needed — validation result only'],
    attestationFields: ['gate', 'result', 'blocking'],
    gates: ['readonly_only'],
    blockedActions: ['capture', 'write', 'submit'],
    reason: 'Validation output reference is a static summary',
    nextAction: 'View the validation report for details',
  },
  {
    id: 'screenshot-reference',
    label: 'Screenshot Reference',
    evidenceType: 'screenshot',
    source: 'human_operator',
    sensitivity: 'redacted_sensitive',
    retention: 'report_reference',
    risk: 'medium',
    allowedNow: true,
    captureNow: false,
    writeNow: false,
    requiresRedaction: true,
    requiresHumanReview: false,
    requiresStageC: false,
    requiresDbWrite: false,
    containsSecretMaterial: false,
    containsTokenLikeMaterial: false,
    allowedFields: ['path', 'description', 'capturedAt'],
    forbiddenFields: ['token', 'apiKey', 'password', 'privateKey', 'credential', 'secret', 'fullImageData'],
    redactionRules: ['Redact full image data — store path only', 'Redact any visible secrets in screenshot', 'Do not store screenshot binary in registry'],
    attestationFields: ['path', 'description'],
    gates: ['readonly_only', 'redaction_required'],
    blockedActions: ['capture_screenshot', 'upload_screenshot', 'write_image_data', 'submit'],
    reason: 'Screenshot reference stores path only — no image data in registry',
    nextAction: 'Reference the screenshot file directly',
  },
  {
    id: 'human-note-preview',
    label: 'Human Note Preview',
    evidenceType: 'human_note',
    source: 'human_operator',
    sensitivity: 'redacted_sensitive',
    retention: 'preview_only',
    risk: 'medium',
    allowedNow: true,
    captureNow: false,
    writeNow: false,
    requiresRedaction: true,
    requiresHumanReview: true,
    requiresStageC: false,
    requiresDbWrite: false,
    containsSecretMaterial: false,
    containsTokenLikeMaterial: false,
    allowedFields: ['author', 'timestamp', 'category', 'summaryText'],
    forbiddenFields: ['token', 'apiKey', 'password', 'privateKey', 'credential', 'secret', 'fullNoteBody', 'internalReference'],
    redactionRules: ['Redact full note body — show summary only', 'Redact internal references', 'Redact reviewer identity if sensitive'],
    attestationFields: ['author', 'timestamp', 'category'],
    gates: ['readonly_only', 'redaction_required'],
    blockedActions: ['capture', 'write', 'submit', 'edit_note'],
    reason: 'Human note preview shows redacted summary — full note body requires future_audit_store',
    nextAction: 'Contact the note author for full context',
  },
  {
    id: 'rollback-plan-preview',
    label: 'Rollback Plan Preview',
    evidenceType: 'rollback_plan',
    source: 'runtime_registry',
    sensitivity: 'internal_status',
    retention: 'preview_only',
    risk: 'medium',
    allowedNow: true,
    captureNow: false,
    writeNow: false,
    requiresRedaction: false,
    requiresHumanReview: false,
    requiresStageC: false,
    requiresDbWrite: false,
    containsSecretMaterial: false,
    containsTokenLikeMaterial: false,
    allowedFields: ['id', 'planType', 'risk', 'steps', 'rollbackStrategy', 'gates', 'blockedActions'],
    forbiddenFields: ['token', 'apiKey', 'password', 'privateKey', 'credential', 'secret'],
    redactionRules: ['No redaction needed — plan metadata only'],
    attestationFields: ['id', 'planType', 'risk'],
    relatedRollbackItem: 'rollback-plan-preview',
    gates: ['readonly_only', 'no_execution'],
    blockedActions: ['execute_rollback', 'capture', 'write'],
    reason: 'Rollback plan preview is a readonly plan view',
    nextAction: 'View rollback plan details when implemented',
  },
  {
    id: 'stage-gate-state-preview',
    label: 'Stage Gate State Preview',
    evidenceType: 'stage_gate_state',
    source: 'governance_state',
    sensitivity: 'internal_status',
    retention: 'preview_only',
    risk: 'medium',
    allowedNow: true,
    captureNow: false,
    writeNow: false,
    requiresRedaction: false,
    requiresHumanReview: false,
    requiresStageC: false,
    requiresDbWrite: false,
    containsSecretMaterial: false,
    containsTokenLikeMaterial: false,
    allowedFields: ['id', 'gate', 'state', 'risk', 'blockedActions'],
    forbiddenFields: ['token', 'apiKey', 'password', 'privateKey', 'credential', 'secret'],
    redactionRules: ['No redaction needed — gate state metadata only'],
    attestationFields: ['id', 'gate', 'state'],
    gates: ['readonly_only', 'no_state_transition', 'stage_c_disabled'],
    blockedActions: ['transition_gate', 'capture', 'write', 'enable_stage_c'],
    reason: 'Stage gate state preview shows current gate status — Stage C permanently disabled',
    nextAction: 'View governance state machine preview for details',
  },
  {
    id: 'token-secret-material-forbidden',
    label: 'Token/Secret Material — Forbidden',
    evidenceType: 'validation_output',
    source: 'validation_gate',
    sensitivity: 'forbidden_secret',
    retention: 'forbidden_no_store',
    risk: 'critical',
    allowedNow: false,
    captureNow: false,
    writeNow: false,
    requiresRedaction: true,
    requiresHumanReview: true,
    requiresStageC: false,
    requiresDbWrite: false,
    containsSecretMaterial: true,
    containsTokenLikeMaterial: false,
    allowedFields: [],
    forbiddenFields: ['token', 'secret', 'credential', 'all'],
    redactionRules: ['NEVER capture — forbidden secret category', 'If detected in scan, report path only', 'No token value ever stored in registry'],
    attestationFields: ['detected', 'source', 'severity'],
    gates: ['readonly_only', 'no_secret_storage', 'no_evidence_capture', 'forbidden_secret_category'],
    blockedActions: ['capture', 'write', 'store', 'submit', 'view_raw', 'export'],
    reason: 'Token/secret material is NEVER captured or stored in evidence schema',
    nextAction: 'Run secret scan to detect and remove any leaked tokens',
  },
  {
    id: 'api-key-material-forbidden',
    label: 'API Key Material — Forbidden',
    evidenceType: 'validation_output',
    source: 'validation_gate',
    sensitivity: 'forbidden_secret',
    retention: 'forbidden_no_store',
    risk: 'critical',
    allowedNow: false,
    captureNow: false,
    writeNow: false,
    requiresRedaction: true,
    requiresHumanReview: true,
    requiresStageC: false,
    requiresDbWrite: false,
    containsSecretMaterial: false,
    containsTokenLikeMaterial: true,
    allowedFields: [],
    forbiddenFields: ['apiKey', 'api_key', 'apikey', 'secret', 'credential', 'token', 'all'],
    redactionRules: ['NEVER capture — forbidden API key category', 'If detected in scan, report path only', 'No API key value ever stored in registry'],
    attestationFields: ['detected', 'source', 'severity'],
    gates: ['readonly_only', 'no_secret_storage', 'no_evidence_capture', 'forbidden_secret_category'],
    blockedActions: ['capture', 'write', 'store', 'submit', 'view_raw', 'export'],
    reason: 'API key material is NEVER captured or stored in evidence schema',
    nextAction: 'Rotate any exposed API keys immediately',
  },
  {
    id: 'raw-password-material-forbidden',
    label: 'Raw Password Material — Forbidden',
    evidenceType: 'validation_output',
    source: 'validation_gate',
    sensitivity: 'forbidden_secret',
    retention: 'forbidden_no_store',
    risk: 'critical',
    allowedNow: false,
    captureNow: false,
    writeNow: false,
    requiresRedaction: true,
    requiresHumanReview: true,
    requiresStageC: false,
    requiresDbWrite: false,
    containsSecretMaterial: true,
    containsTokenLikeMaterial: true,
    allowedFields: [],
    forbiddenFields: ['password', 'passwd', 'pwd', 'secret', 'credential', 'privateKey', 'all'],
    redactionRules: ['NEVER capture — forbidden password category', 'If detected in scan, report path only', 'No password value ever stored in registry'],
    attestationFields: ['detected', 'source', 'severity'],
    gates: ['readonly_only', 'no_secret_storage', 'no_evidence_capture', 'forbidden_secret_category'],
    blockedActions: ['capture', 'write', 'store', 'submit', 'view_raw', 'export'],
    reason: 'Raw password material is NEVER captured or stored in evidence schema',
    nextAction: 'Rotate any exposed passwords immediately',
  },
];

export function getEvidenceSchemaItems(): EvidenceSchemaItem[] {
  return EVIDENCE_SCHEMA_ITEMS;
}

export function getEvidenceSchemaSummary() {
  const items = EVIDENCE_SCHEMA_ITEMS;
  return {
    total: items.length,
    allowedNow: items.filter(i => i.allowedNow).length,
    captureNow: items.filter(i => i.captureNow).length,
    writeNow: items.filter(i => i.writeNow).length,
    requiresRedaction: items.filter(i => i.requiresRedaction).length,
    requiresHumanReview: items.filter(i => i.requiresHumanReview).length,
    requiresStageC: items.filter(i => i.requiresStageC).length,
    requiresDbWrite: items.filter(i => i.requiresDbWrite).length,
    forbiddenSecrets: items.filter(i => i.sensitivity === 'forbidden_secret').length,
    highOrCritical: items.filter(i => i.risk === 'high' || i.risk === 'critical').length,
  };
}

export function getEvidenceItemsByType(type: EvidenceType): EvidenceSchemaItem[] {
  return EVIDENCE_SCHEMA_ITEMS.filter(i => i.evidenceType === type);
}

export function getEvidenceItemsBySource(source: EvidenceSource): EvidenceSchemaItem[] {
  return EVIDENCE_SCHEMA_ITEMS.filter(i => i.source === source);
}

export function getEvidenceItemsBySensitivity(sensitivity: EvidenceSensitivity): EvidenceSchemaItem[] {
  return EVIDENCE_SCHEMA_ITEMS.filter(i => i.sensitivity === sensitivity);
}

export function getEvidenceItemsByRetention(retention: EvidenceRetention): EvidenceSchemaItem[] {
  return EVIDENCE_SCHEMA_ITEMS.filter(i => i.retention === retention);
}

export function getBlockedEvidenceItems(): EvidenceSchemaItem[] {
  return EVIDENCE_SCHEMA_ITEMS.filter(i => !i.allowedNow);
}

export function getRedactionRequiredEvidenceItems(): EvidenceSchemaItem[] {
  return EVIDENCE_SCHEMA_ITEMS.filter(i => i.requiresRedaction);
}
