export type ConsoleDecisionType =
  | 'continue_preview'
  | 'run_final_seal_recheck'
  | 'hold_for_human_review'
  | 'generate_report_preview'
  | 'blocked'
  | 'future_stage_c_only'
  | 'documentation_polish'
  | 'readiness_audit';

export type ConsoleDecisionRisk = 'low' | 'medium' | 'high' | 'critical';

export interface GovernanceConsoleDecisionItem {
  id: string;
  label: string;
  decisionType: ConsoleDecisionType;
  risk: ConsoleDecisionRisk;
  recommendedNow: boolean;
  allowedNow: boolean;
  executesAction: boolean;
  mutatesRegistry: boolean;
  writesDb: boolean;
  controlsExternalTool: boolean;
  requiresHumanApproval: boolean;
  requiresStageC: boolean;
  requiresEvidence: boolean;
  requiresRollback: boolean;
  sourceRisks: string[];
  linkedRoutes: string[];
  linkedDocs: string[];
  decisionRationale: string;
  blockedActions: string[];
  gates: string[];
  reason: string;
  nextAction: string;
}

const DECISION_ITEMS: GovernanceConsoleDecisionItem[] = [
  {
    id: 'continue-risk-dashboard-preview',
    label: 'Continue Risk Dashboard Preview',
    decisionType: 'continue_preview',
    risk: 'low',
    recommendedNow: true,
    allowedNow: true,
    executesAction: false,
    mutatesRegistry: false,
    writesDb: false,
    controlsExternalTool: false,
    requiresHumanApproval: false,
    requiresStageC: false,
    requiresEvidence: false,
    requiresRollback: false,
    sourceRisks: [],
    linkedRoutes: ['/governance-console-risk-dashboard-preview'],
    linkedDocs: ['AIP_GOVERNANCE_CONSOLE_RISK_DASHBOARD_PREVIEW.md'],
    decisionRationale: 'Risk Dashboard is a readonly preview. No blocking conditions. Safe to continue preview.',
    blockedActions: ['execute_gate', 'change_registry', 'write_database'],
    gates: ['readonly_only', 'no_gate_execution'],
    reason: 'No blocking risks detected across all registries.',
    nextAction: 'Continue readonly preview. Do not implement risk gate execution.',
  },
  {
    id: 'continue-decision-panel-preview',
    label: 'Continue Decision Panel Preview',
    decisionType: 'continue_preview',
    risk: 'low',
    recommendedNow: true,
    allowedNow: true,
    executesAction: false,
    mutatesRegistry: false,
    writesDb: false,
    controlsExternalTool: false,
    requiresHumanApproval: false,
    requiresStageC: false,
    requiresEvidence: false,
    requiresRollback: false,
    sourceRisks: [],
    linkedRoutes: ['/governance-console-decision-panel-preview'],
    linkedDocs: ['AIP_GOVERNANCE_CONSOLE_DECISION_PANEL_PREVIEW.md'],
    decisionRationale: 'Decision Panel is a readonly preview. No blocking conditions. Safe to continue preview.',
    blockedActions: ['approve', 'reject', 'execute', 'apply'],
    gates: ['readonly_only', 'no_approval'],
    reason: 'No blocking decisions detected.',
    nextAction: 'Continue readonly preview. Do not implement decision execution.',
  },
  {
    id: 'continue-report-pack-preview',
    label: 'Continue Report Pack Preview',
    decisionType: 'continue_preview',
    risk: 'low',
    recommendedNow: true,
    allowedNow: true,
    executesAction: false,
    mutatesRegistry: false,
    writesDb: false,
    controlsExternalTool: false,
    requiresHumanApproval: false,
    requiresStageC: false,
    requiresEvidence: false,
    requiresRollback: false,
    sourceRisks: [],
    linkedRoutes: ['/governance-console-report-pack-preview'],
    linkedDocs: ['AIP_GOVERNANCE_CONSOLE_REPORT_PACK_PREVIEW.md'],
    decisionRationale: 'Report Pack is a readonly preview. No blocking conditions. Safe to continue preview.',
    blockedActions: ['export_file', 'write_database', 'store_report'],
    gates: ['readonly_only', 'no_report_store'],
    reason: 'No blocking report conditions detected.',
    nextAction: 'Continue readonly preview. Do not implement report generation.',
  },
  {
    id: 'run-v7-29-final-seal-recheck',
    label: 'Run v7.29 Final Seal Recheck',
    decisionType: 'run_final_seal_recheck',
    risk: 'low',
    recommendedNow: true,
    allowedNow: true,
    executesAction: false,
    mutatesRegistry: false,
    writesDb: false,
    controlsExternalTool: false,
    requiresHumanApproval: false,
    requiresStageC: false,
    requiresEvidence: false,
    requiresRollback: false,
    sourceRisks: [],
    linkedRoutes: [],
    linkedDocs: ['AIP_V7_28_FINAL_SEAL_RECHECK.md'],
    decisionRationale: 'P2/P3/P4 acceleration is complete. Recommended to run full v7.29 Final Seal Recheck to confirm all previews are clean.',
    blockedActions: [],
    gates: [],
    reason: 'All P1-P4 phases complete. v7.29 roadmap on track.',
    nextAction: 'Run v7.29 Final Seal Recheck after P2/P3/P4 acceleration pack commit.',
  },
  {
    id: 'hold-for-human-review-before-runtime',
    label: 'Hold for Human Review Before Runtime',
    decisionType: 'hold_for_human_review',
    risk: 'high',
    recommendedNow: false,
    allowedNow: true,
    executesAction: false,
    mutatesRegistry: false,
    writesDb: false,
    controlsExternalTool: false,
    requiresHumanApproval: true,
    requiresStageC: false,
    requiresEvidence: true,
    requiresRollback: false,
    sourceRisks: ['runtime-execution-blocked-risk', 'approval-queue-blocked-risk', 'evidence-store-blocked-risk', 'rollback-executor-blocked-risk'],
    linkedRoutes: [],
    linkedDocs: ['AIP_RUNTIME_IMPLEMENTATION_READINESS_AUDIT.md'],
    decisionRationale: 'Runtime implementation requires human approval. 4 blocking risks must be reviewed before any runtime implementation.',
    blockedActions: ['implement_runtime', 'enable_stage_c', 'write_database', 'control_external'],
    gates: ['hold_for_human_review'],
    reason: 'Runtime implementation is a major governance decision that requires human approval.',
    nextAction: 'Present risks to human reviewer. Do not implement runtime without explicit approval.',
  },
  {
    id: 'generate-console-report-pack-preview',
    label: 'Generate Console Report Pack Preview',
    decisionType: 'generate_report_preview',
    risk: 'low',
    recommendedNow: true,
    allowedNow: true,
    executesAction: false,
    mutatesRegistry: false,
    writesDb: false,
    controlsExternalTool: false,
    requiresHumanApproval: false,
    requiresStageC: false,
    requiresEvidence: false,
    requiresRollback: false,
    sourceRisks: [],
    linkedRoutes: ['/governance-console-report-pack-preview'],
    linkedDocs: ['AIP_GOVERNANCE_CONSOLE_REPORT_PACK_PREVIEW.md'],
    decisionRationale: 'Report Pack preview is available. Can view report structure and fields.',
    blockedActions: ['export_file', 'write_database'],
    gates: ['readonly_only', 'no_report_store'],
    reason: 'Report Pack is a readonly preview of future report structure.',
    nextAction: 'View report pack preview. Do not generate real report files.',
  },
  {
    id: 'documentation-polish',
    label: 'Documentation Polish',
    decisionType: 'documentation_polish',
    risk: 'low',
    recommendedNow: true,
    allowedNow: true,
    executesAction: false,
    mutatesRegistry: false,
    writesDb: false,
    controlsExternalTool: false,
    requiresHumanApproval: false,
    requiresStageC: false,
    requiresEvidence: false,
    requiresRollback: false,
    sourceRisks: [],
    linkedRoutes: [],
    linkedDocs: [],
    decisionRationale: 'All phases have documentation. Can polish existing docs for consistency.',
    blockedActions: [],
    gates: [],
    reason: 'Documentation is complete but can always be improved.',
    nextAction: 'Polish documentation as needed. No blocking issues.',
  },
  {
    id: 'runtime-implementation-readiness-audit',
    label: 'Runtime Implementation Readiness Audit',
    decisionType: 'readiness_audit',
    risk: 'low',
    recommendedNow: true,
    allowedNow: true,
    executesAction: false,
    mutatesRegistry: false,
    writesDb: false,
    controlsExternalTool: false,
    requiresHumanApproval: false,
    requiresStageC: false,
    requiresEvidence: false,
    requiresRollback: false,
    sourceRisks: ['runtime-execution-blocked-risk'],
    linkedRoutes: [],
    linkedDocs: ['AIP_RUNTIME_IMPLEMENTATION_READINESS_AUDIT.md'],
    decisionRationale: 'Runtime implementation readiness audit is available as a design reference.',
    blockedActions: [],
    gates: [],
    reason: 'Readiness audit is a design document, not an implementation plan.',
    nextAction: 'Reference readiness audit for future planning. Do not implement runtime.',
  },
  {
    id: 'blocked-enable-stage-c',
    label: 'Blocked: Enable Stage C',
    decisionType: 'blocked',
    risk: 'critical',
    recommendedNow: false,
    allowedNow: false,
    executesAction: false,
    mutatesRegistry: true,
    writesDb: true,
    controlsExternalTool: true,
    requiresHumanApproval: true,
    requiresStageC: true,
    requiresEvidence: true,
    requiresRollback: true,
    sourceRisks: ['stage-c-disabled-risk'],
    linkedRoutes: [],
    linkedDocs: ['AIP_STAGE_C_READINESS_CHECKLIST.md'],
    decisionRationale: 'Stage C is permanently disabled. Enabling Stage C would require mutating registries, writing DB, controlling external tools, human approval, evidence, and rollback capability.',
    blockedActions: ['enable_stage_c', 'transition_stage', 'write_database', 'control_external', 'execute_action'],
    gates: ['stage_c_disabled', 'irreversible_action', 'hold_for_human_review'],
    reason: 'Stage C is permanently disabled across all preview systems.',
    nextAction: 'Keep Stage C permanently disabled. Do not design Stage C implementation.',
  },
  {
    id: 'blocked-db-write',
    label: 'Blocked: Database Write',
    decisionType: 'blocked',
    risk: 'critical',
    recommendedNow: false,
    allowedNow: false,
    executesAction: false,
    mutatesRegistry: true,
    writesDb: true,
    controlsExternalTool: false,
    requiresHumanApproval: true,
    requiresStageC: true,
    requiresEvidence: false,
    requiresRollback: false,
    sourceRisks: ['db-write-blocked-risk'],
    linkedRoutes: [],
    linkedDocs: [],
    decisionRationale: 'Database write is blocked. No DB schema or write service exists.',
    blockedActions: ['write_database', 'write_audit_log', 'write_evidence', 'write_report'],
    gates: ['stage_c_disabled', 'readonly_only'],
    reason: 'Database write is blocked. Requires Stage C and human approval.',
    nextAction: 'Keep DB write blocked. Do not implement DB writes.',
  },
  {
    id: 'blocked-external-control',
    label: 'Blocked: External Control',
    decisionType: 'blocked',
    risk: 'critical',
    recommendedNow: false,
    allowedNow: false,
    executesAction: false,
    mutatesRegistry: false,
    writesDb: false,
    controlsExternalTool: true,
    requiresHumanApproval: true,
    requiresStageC: true,
    requiresEvidence: false,
    requiresRollback: true,
    sourceRisks: ['external-control-blocked-risk'],
    linkedRoutes: [],
    linkedDocs: [],
    decisionRationale: 'External control is blocked. No connector endpoints or execution service.',
    blockedActions: ['control_external', 'connect', 'execute_action'],
    gates: ['stage_c_disabled', 'readonly_only'],
    reason: 'External control is blocked. Requires Stage C and human approval.',
    nextAction: 'Keep external control blocked. Do not implement external tool control.',
  },
  {
    id: 'blocked-approval-queue',
    label: 'Blocked: Approval Queue',
    decisionType: 'blocked',
    risk: 'high',
    recommendedNow: false,
    allowedNow: false,
    executesAction: false,
    mutatesRegistry: false,
    writesDb: false,
    controlsExternalTool: false,
    requiresHumanApproval: true,
    requiresStageC: false,
    requiresEvidence: true,
    requiresRollback: false,
    sourceRisks: ['approval-queue-blocked-risk'],
    linkedRoutes: ['/human-approval-workflow-preview'],
    linkedDocs: ['AIP_HUMAN_APPROVAL_WORKFLOW_SPEC.md'],
    decisionRationale: 'Approval queue is blocked. No approval service or candidate processing.',
    blockedActions: ['approve', 'reject', 'archive', 'process_candidate'],
    gates: ['readonly_only', 'no_approval_queue'],
    reason: 'Approval queue is blocked. Requires human approval infrastructure.',
    nextAction: 'Keep approval queue blocked. Do not implement approval service.',
  },
  {
    id: 'blocked-rollback-executor',
    label: 'Blocked: Rollback Executor',
    decisionType: 'blocked',
    risk: 'critical',
    recommendedNow: false,
    allowedNow: false,
    executesAction: true,
    mutatesRegistry: false,
    writesDb: false,
    controlsExternalTool: true,
    requiresHumanApproval: true,
    requiresStageC: true,
    requiresEvidence: true,
    requiresRollback: true,
    sourceRisks: ['rollback-executor-blocked-risk', 'file-restore-blocked-risk', 'git-tag-release-blocked-risk'],
    linkedRoutes: ['/rollback-preview'],
    linkedDocs: ['AIP_ROLLBACK_PREVIEW.md'],
    decisionRationale: 'Rollback executor is blocked. Requires Stage C and external control.',
    blockedActions: ['execute_rollback', 'restore_file', 'git_reset', 'git_revert', 'git_tag', 'git_release'],
    gates: ['readonly_only', 'no_rollback_execution', 'stage_c_disabled'],
    reason: 'Rollback executor is blocked. Requires Stage C and human approval.',
    nextAction: 'Keep rollback executor blocked. Do not implement rollback engine.',
  },
  {
    id: 'future-stage-c-only-runtime-implementation',
    label: 'Future Stage C Only: Runtime Implementation',
    decisionType: 'future_stage_c_only',
    risk: 'high',
    recommendedNow: false,
    allowedNow: false,
    executesAction: false,
    mutatesRegistry: false,
    writesDb: false,
    controlsExternalTool: false,
    requiresHumanApproval: true,
    requiresStageC: true,
    requiresEvidence: true,
    requiresRollback: true,
    sourceRisks: ['runtime-execution-blocked-risk', 'stage-c-disabled-risk'],
    linkedRoutes: [],
    linkedDocs: ['AIP_RUNTIME_IMPLEMENTATION_READINESS_AUDIT.md'],
    decisionRationale: 'Runtime implementation is future Stage C only. 13 of 14 capabilities cannot be implemented now.',
    blockedActions: ['implement_runtime', 'execute_action', 'write_database', 'control_external', 'enable_stage_c'],
    gates: ['stage_c_disabled', 'hold_for_human_review'],
    reason: 'Runtime implementation requires Stage C, which is permanently disabled.',
    nextAction: 'Keep runtime implementation as future consideration. Do not implement until Stage C is enabled.',
  },
];

export function getGovernanceConsoleDecisionItems(): GovernanceConsoleDecisionItem[] {
  return DECISION_ITEMS;
}

export function getGovernanceConsoleDecisionSummary() {
  const items = DECISION_ITEMS;
  return {
    total: items.length,
    recommendedNow: items.filter(i => i.recommendedNow).length,
    blocked: items.filter(i => i.decisionType === 'blocked').length,
    highOrCritical: items.filter(i => i.risk === 'high' || i.risk === 'critical').length,
    executesAction: items.filter(i => i.executesAction).length,
    mutatesRegistry: items.filter(i => i.mutatesRegistry).length,
    writesDb: items.filter(i => i.writesDb).length,
    controlsExternalTool: items.filter(i => i.controlsExternalTool).length,
    requiresHumanApproval: items.filter(i => i.requiresHumanApproval).length,
    requiresStageC: items.filter(i => i.requiresStageC).length,
  };
}

export function getGovernanceConsoleDecisionsByType(type: ConsoleDecisionType): GovernanceConsoleDecisionItem[] {
  return DECISION_ITEMS.filter(i => i.decisionType === type);
}

export function getGovernanceConsoleDecisionsByRisk(risk: ConsoleDecisionRisk): GovernanceConsoleDecisionItem[] {
  return DECISION_ITEMS.filter(i => i.risk === risk);
}

export function getRecommendedGovernanceConsoleDecisions(): GovernanceConsoleDecisionItem[] {
  return DECISION_ITEMS.filter(i => i.recommendedNow);
}

export function getBlockedGovernanceConsoleDecisions(): GovernanceConsoleDecisionItem[] {
  return DECISION_ITEMS.filter(i => i.decisionType === 'blocked');
}
