export type ConsoleRiskSource =
  | 'permission_evaluator'
  | 'runtime_registry'
  | 'dry_run_plan'
  | 'audit_log'
  | 'governance_state'
  | 'human_approval'
  | 'evidence_schema'
  | 'rollback'
  | 'navigation'
  | 'center_access'
  | 'stage_c'
  | 'database'
  | 'external_control';

export type ConsoleRiskCategory =
  | 'blocked_action'
  | 'stage_c_gate'
  | 'db_write_gate'
  | 'external_control_gate'
  | 'human_approval_gate'
  | 'evidence_required'
  | 'rollback_required'
  | 'sidebar_exposure'
  | 'secret_handling'
  | 'execution_capability';

export type ConsoleRiskSeverity = 'low' | 'medium' | 'high' | 'critical';

export interface GovernanceConsoleRiskItem {
  id: string;
  label: string;
  source: ConsoleRiskSource;
  category: ConsoleRiskCategory;
  severity: ConsoleRiskSeverity;
  count: number;
  allowedNow: boolean;
  blocked: boolean;
  requiresStageC: boolean;
  requiresDbWrite: boolean;
  requiresExternalControl: boolean;
  requiresHumanApproval: boolean;
  requiresEvidence: boolean;
  requiresRollback: boolean;
  affectedRoutes: string[];
  affectedRegistries: string[];
  linkedDocs: string[];
  gates: string[];
  blockedActions: string[];
  reason: string;
  nextAction: string;
}

const RISK_ITEMS: GovernanceConsoleRiskItem[] = [
  {
    id: 'stage-c-disabled-risk',
    label: 'Stage C Disabled',
    source: 'stage_c',
    category: 'stage_c_gate',
    severity: 'critical',
    count: 3,
    allowedNow: false,
    blocked: true,
    requiresStageC: true,
    requiresDbWrite: true,
    requiresExternalControl: true,
    requiresHumanApproval: true,
    requiresEvidence: false,
    requiresRollback: true,
    affectedRoutes: [],
    affectedRegistries: ['governance-state-registry', 'rollback-registry', 'permission-evaluator-registry'],
    linkedDocs: ['AIP_STAGE_C_READINESS_CHECKLIST.md'],
    gates: ['stage_c_disabled', 'irreversible_action'],
    blockedActions: ['enable_stage_c', 'transition_stage', 'execute_action', 'write_database', 'control_external'],
    reason: 'Stage C is permanently disabled across all preview systems. 3 registries reference Stage C requirements.',
    nextAction: 'Keep Stage C permanently disabled. Do not design Stage C rollback.',
  },
  {
    id: 'db-write-blocked-risk',
    label: 'Database Write Blocked',
    source: 'database',
    category: 'db_write_gate',
    severity: 'critical',
    count: 3,
    allowedNow: false,
    blocked: true,
    requiresStageC: true,
    requiresDbWrite: true,
    requiresExternalControl: false,
    requiresHumanApproval: true,
    requiresEvidence: false,
    requiresRollback: false,
    affectedRoutes: [],
    affectedRegistries: ['governance-state-registry', 'rollback-registry', 'audit-log-registry'],
    linkedDocs: [],
    gates: ['stage_c_disabled', 'readonly_only'],
    blockedActions: ['write_database', 'write_audit_log', 'write_evidence'],
    reason: 'Database write is blocked across all registries. No DB schema or write service exists.',
    nextAction: 'Keep DB write blocked. Do not implement DB writes.',
  },
  {
    id: 'external-control-blocked-risk',
    label: 'External Control Blocked',
    source: 'external_control',
    category: 'external_control_gate',
    severity: 'critical',
    count: 3,
    allowedNow: false,
    blocked: true,
    requiresStageC: true,
    requiresDbWrite: false,
    requiresExternalControl: true,
    requiresHumanApproval: true,
    requiresEvidence: false,
    requiresRollback: true,
    affectedRoutes: [],
    affectedRegistries: ['connector-registry', 'rollback-registry', 'dry-run-plan-registry'],
    linkedDocs: [],
    gates: ['stage_c_disabled', 'readonly_only'],
    blockedActions: ['control_external', 'connect', 'execute_action', 'write_database'],
    reason: 'External control is blocked. No connector endpoints or execution service.',
    nextAction: 'Keep external control blocked. Do not implement external tool control.',
  },
  {
    id: 'runtime-execution-blocked-risk',
    label: 'Runtime Execution Blocked',
    source: 'runtime_registry',
    category: 'execution_capability',
    severity: 'high',
    count: 1,
    allowedNow: false,
    blocked: true,
    requiresStageC: true,
    requiresDbWrite: true,
    requiresExternalControl: true,
    requiresHumanApproval: true,
    requiresEvidence: true,
    requiresRollback: true,
    affectedRoutes: ['/runtime-registry-preview'],
    affectedRegistries: ['runtime-registry'],
    linkedDocs: [],
    gates: ['readonly_only', 'no_runtime_implementation'],
    blockedActions: ['execute_action', 'start_service', 'stop_service'],
    reason: 'Runtime execution is blocked. No runtime executor or service management.',
    nextAction: 'Keep runtime execution blocked. Do not implement runtime executor.',
  },
  {
    id: 'dry-run-execution-blocked-risk',
    label: 'Dry-run Execution Blocked',
    source: 'dry_run_plan',
    category: 'execution_capability',
    severity: 'high',
    count: 1,
    allowedNow: false,
    blocked: true,
    requiresStageC: false,
    requiresDbWrite: false,
    requiresExternalControl: true,
    requiresHumanApproval: true,
    requiresEvidence: true,
    requiresRollback: false,
    affectedRoutes: ['/dry-run-plan-preview'],
    affectedRegistries: ['dry-run-plan-registry'],
    linkedDocs: [],
    gates: ['readonly_only', 'no_dry_run_executor'],
    blockedActions: ['execute_dry_run', 'write_database', 'control_external'],
    reason: 'Dry-run execution is blocked. No dry-run executor or plan execution.',
    nextAction: 'Keep dry-run execution blocked. Do not implement dry-run executor.',
  },
  {
    id: 'audit-write-blocked-risk',
    label: 'Audit Log Write Blocked',
    source: 'audit_log',
    category: 'blocked_action',
    severity: 'high',
    count: 1,
    allowedNow: false,
    blocked: true,
    requiresStageC: false,
    requiresDbWrite: true,
    requiresExternalControl: false,
    requiresHumanApproval: true,
    requiresEvidence: false,
    requiresRollback: false,
    affectedRoutes: ['/audit-log-preview'],
    affectedRegistries: ['audit-log-registry'],
    linkedDocs: [],
    gates: ['readonly_only', 'no_audit_write'],
    blockedActions: ['write_audit_log', 'write_database'],
    reason: 'Audit log write is blocked. No audit logger or DB write.',
    nextAction: 'Keep audit write blocked. Do not implement audit logger.',
  },
  {
    id: 'approval-queue-blocked-risk',
    label: 'Approval Queue Blocked',
    source: 'human_approval',
    category: 'blocked_action',
    severity: 'high',
    count: 1,
    allowedNow: false,
    blocked: true,
    requiresStageC: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    requiresHumanApproval: true,
    requiresEvidence: true,
    requiresRollback: false,
    affectedRoutes: ['/human-approval-workflow-preview'],
    affectedRegistries: ['human-approval-registry'],
    linkedDocs: [],
    gates: ['readonly_only', 'no_approval_queue'],
    blockedActions: ['approve', 'reject', 'archive', 'write_database', 'process_candidate'],
    reason: 'Approval queue is blocked. No approval service or candidate processing.',
    nextAction: 'Keep approval queue blocked. Do not implement approval service.',
  },
  {
    id: 'candidate-processing-blocked-risk',
    label: 'Candidate Processing Blocked',
    source: 'human_approval',
    category: 'blocked_action',
    severity: 'high',
    count: 1,
    allowedNow: false,
    blocked: true,
    requiresStageC: true,
    requiresDbWrite: true,
    requiresExternalControl: false,
    requiresHumanApproval: true,
    requiresEvidence: true,
    requiresRollback: false,
    affectedRoutes: [],
    affectedRegistries: ['human-approval-registry'],
    linkedDocs: [],
    gates: ['readonly_only', 'stage_c_disabled'],
    blockedActions: ['process_candidate', 'write_database', 'approve'],
    reason: 'Candidate processing is blocked. Requires Stage C and DB write.',
    nextAction: 'Keep candidate processing blocked. Requires Stage C implementation.',
  },
  {
    id: 'evidence-store-blocked-risk',
    label: 'Evidence Store Blocked',
    source: 'evidence_schema',
    category: 'blocked_action',
    severity: 'high',
    count: 1,
    allowedNow: false,
    blocked: true,
    requiresStageC: false,
    requiresDbWrite: true,
    requiresExternalControl: false,
    requiresHumanApproval: false,
    requiresEvidence: true,
    requiresRollback: false,
    affectedRoutes: ['/evidence-schema-preview'],
    affectedRegistries: ['evidence-schema-registry'],
    linkedDocs: [],
    gates: ['readonly_only', 'no_evidence_capture'],
    blockedActions: ['capture_evidence', 'store_evidence', 'write_database'],
    reason: 'Evidence store is blocked. No evidence writer or storage backend.',
    nextAction: 'Keep evidence store blocked. Do not implement evidence store.',
  },
  {
    id: 'secret-capture-blocked-risk',
    label: 'Secret Capture Blocked',
    source: 'evidence_schema',
    category: 'secret_handling',
    severity: 'critical',
    count: 3,
    allowedNow: false,
    blocked: true,
    requiresStageC: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    requiresHumanApproval: true,
    requiresEvidence: false,
    requiresRollback: false,
    affectedRoutes: ['/evidence-schema-preview'],
    affectedRegistries: ['evidence-schema-registry'],
    linkedDocs: [],
    gates: ['readonly_only', 'no_secret_capture'],
    blockedActions: ['capture_token', 'capture_api_key', 'capture_password', 'capture_private_key'],
    reason: 'Secret capture is blocked. 3 evidence items (token, API key, password) are forbidden.',
    nextAction: 'Keep secret capture permanently blocked.',
  },
  {
    id: 'rollback-executor-blocked-risk',
    label: 'Rollback Executor Blocked',
    source: 'rollback',
    category: 'blocked_action',
    severity: 'critical',
    count: 1,
    allowedNow: false,
    blocked: true,
    requiresStageC: true,
    requiresDbWrite: true,
    requiresExternalControl: true,
    requiresHumanApproval: true,
    requiresEvidence: true,
    requiresRollback: true,
    affectedRoutes: ['/rollback-preview'],
    affectedRegistries: ['rollback-registry'],
    linkedDocs: ['AIP_ROLLBACK_PREVIEW.md'],
    gates: ['readonly_only', 'no_rollback_execution', 'stage_c_disabled'],
    blockedActions: ['execute_rollback', 'restore_file', 'git_reset', 'git_revert', 'git_tag', 'git_release', 'write_database'],
    reason: 'Rollback executor is blocked. No rollback engine or file restore service.',
    nextAction: 'Keep rollback executor blocked. Do not implement rollback engine.',
  },
  {
    id: 'file-restore-blocked-risk',
    label: 'File Restore Blocked',
    source: 'rollback',
    category: 'blocked_action',
    severity: 'high',
    count: 1,
    allowedNow: false,
    blocked: true,
    requiresStageC: true,
    requiresDbWrite: false,
    requiresExternalControl: false,
    requiresHumanApproval: true,
    requiresEvidence: true,
    requiresRollback: true,
    affectedRoutes: ['/rollback-preview'],
    affectedRegistries: ['rollback-registry'],
    linkedDocs: [],
    gates: ['readonly_only', 'no_file_restore', 'stage_c_disabled'],
    blockedActions: ['restore_file', 'overwrite_file', 'recover_file'],
    reason: 'File restore is blocked. No file restore service.',
    nextAction: 'Keep file restore blocked. Do not implement file restore.',
  },
  {
    id: 'git-tag-release-blocked-risk',
    label: 'Git Tag/Release Blocked',
    source: 'rollback',
    category: 'blocked_action',
    severity: 'critical',
    count: 2,
    allowedNow: false,
    blocked: true,
    requiresStageC: true,
    requiresDbWrite: false,
    requiresExternalControl: true,
    requiresHumanApproval: true,
    requiresEvidence: true,
    requiresRollback: true,
    affectedRoutes: ['/rollback-preview'],
    affectedRegistries: ['rollback-registry'],
    linkedDocs: [],
    gates: ['readonly_only', 'no_git_mutation', 'stage_c_disabled'],
    blockedActions: ['git_tag', 'git_release', 'git_reset', 'git_revert'],
    reason: 'Git tag/release is blocked. No git mutation service.',
    nextAction: 'Keep git tag/release blocked. Do not implement git mutation.',
  },
  {
    id: 'hidden-preview-sidebar-risk',
    label: 'Hidden Preview Sidebar Exposure',
    source: 'navigation',
    category: 'sidebar_exposure',
    severity: 'low',
    count: 8,
    allowedNow: true,
    blocked: false,
    requiresStageC: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    requiresHumanApproval: false,
    requiresEvidence: false,
    requiresRollback: false,
    affectedRoutes: ['/runtime-registry-preview', '/dry-run-plan-preview', '/audit-log-preview', '/governance-state-machine-preview', '/human-approval-workflow-preview', '/evidence-schema-preview', '/rollback-preview', '/permission-evaluator-preview'],
    affectedRegistries: ['navigation-exposure-registry', 'center-access-registry'],
    linkedDocs: [],
    gates: [],
    blockedActions: [],
    reason: '8 hidden preview routes are correctly not in sidebar. Low risk.',
    nextAction: 'Maintain hidden direct status. Do not add to sidebar.',
  },
  {
    id: 'governance-console-sidebar-risk',
    label: 'Governance Console Sidebar Exposure',
    source: 'navigation',
    category: 'sidebar_exposure',
    severity: 'low',
    count: 4,
    allowedNow: true,
    blocked: false,
    requiresStageC: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    requiresHumanApproval: false,
    requiresEvidence: false,
    requiresRollback: false,
    affectedRoutes: ['/governance-console-preview', '/governance-console-risk-dashboard-preview', '/governance-console-decision-panel-preview', '/governance-console-report-pack-preview'],
    affectedRegistries: ['navigation-exposure-registry', 'center-access-registry'],
    linkedDocs: [],
    gates: [],
    blockedActions: [],
    reason: '4 governance console routes are correctly hidden direct. Low risk.',
    nextAction: 'Maintain hidden direct status. Do not add console to sidebar.',
  },
  {
    id: 'permission-deny-risk',
    label: 'Permission Deny Risk',
    source: 'permission_evaluator',
    category: 'blocked_action',
    severity: 'medium',
    count: 5,
    allowedNow: true,
    blocked: false,
    requiresStageC: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    requiresHumanApproval: false,
    requiresEvidence: false,
    requiresRollback: false,
    affectedRoutes: [],
    affectedRegistries: ['permission-evaluator-registry'],
    linkedDocs: [],
    gates: ['readonly_only'],
    blockedActions: ['execute_action', 'write_database', 'control_external'],
    reason: 'Permission evaluator has deny rules for 5 actions. This is expected for readonly preview.',
    nextAction: 'Maintain deny rules. Do not enable permission execution.',
  },
  {
    id: 'human-approval-required-risk',
    label: 'Human Approval Required Risk',
    source: 'human_approval',
    category: 'human_approval_gate',
    severity: 'medium',
    count: 10,
    allowedNow: true,
    blocked: false,
    requiresStageC: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    requiresHumanApproval: true,
    requiresEvidence: false,
    requiresRollback: false,
    affectedRoutes: ['/human-approval-workflow-preview'],
    affectedRegistries: ['human-approval-registry'],
    linkedDocs: ['AIP_HUMAN_APPROVAL_WORKFLOW_SPEC.md'],
    gates: ['readonly_only', 'no_approval_queue'],
    blockedActions: ['approve', 'reject', 'archive'],
    reason: '10 items require human approval. Approval queue is not implemented.',
    nextAction: 'Keep approval requirements as design reference. Do not implement approval queue.',
  },
  {
    id: 'evidence-required-risk',
    label: 'Evidence Required Risk',
    source: 'evidence_schema',
    category: 'evidence_required',
    severity: 'medium',
    count: 10,
    allowedNow: true,
    blocked: false,
    requiresStageC: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    requiresHumanApproval: false,
    requiresEvidence: true,
    requiresRollback: false,
    affectedRoutes: ['/evidence-schema-preview'],
    affectedRegistries: ['evidence-schema-registry', 'rollback-registry', 'human-approval-registry'],
    linkedDocs: ['AIP_EVIDENCE_SCHEMA_PREVIEW.md'],
    gates: ['readonly_only', 'no_evidence_capture'],
    blockedActions: ['capture_evidence', 'store_evidence'],
    reason: '10 items across registries require evidence. Evidence store is not implemented.',
    nextAction: 'Keep evidence requirements as design reference. Do not implement evidence store.',
  },
  {
    id: 'rollback-required-risk',
    label: 'Rollback Required Risk',
    source: 'rollback',
    category: 'rollback_required',
    severity: 'medium',
    count: 10,
    allowedNow: true,
    blocked: false,
    requiresStageC: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    requiresHumanApproval: false,
    requiresEvidence: false,
    requiresRollback: true,
    affectedRoutes: ['/rollback-preview'],
    affectedRegistries: ['rollback-registry'],
    linkedDocs: ['AIP_ROLLBACK_PREVIEW.md'],
    gates: ['readonly_only', 'no_rollback_execution'],
    blockedActions: ['execute_rollback', 'restore_file', 'git_reset'],
    reason: '10 items require rollback readiness. Rollback executor is not implemented.',
    nextAction: 'Keep rollback requirements as design reference. Do not implement rollback executor.',
  },
  {
    id: 'validation-script-not-defined-risk',
    label: 'Validation Script Not Defined',
    source: 'center_access',
    category: 'blocked_action',
    severity: 'low',
    count: 3,
    allowedNow: true,
    blocked: false,
    requiresStageC: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    requiresHumanApproval: false,
    requiresEvidence: false,
    requiresRollback: false,
    affectedRoutes: [],
    affectedRegistries: [],
    linkedDocs: [],
    gates: [],
    blockedActions: [],
    reason: 'db:doctor, secret:scan, smoke test scripts are not defined in package.json. Expected for preview phase.',
    nextAction: 'Define scripts when runtime infrastructure is available.',
  },
];

export function getGovernanceConsoleRiskItems(): GovernanceConsoleRiskItem[] {
  return RISK_ITEMS;
}

export function getGovernanceConsoleRiskSummary() {
  const items = RISK_ITEMS;
  return {
    total: items.length,
    blocked: items.filter(i => i.blocked).length,
    highOrCritical: items.filter(i => i.severity === 'high' || i.severity === 'critical').length,
    requiresStageC: items.filter(i => i.requiresStageC).length,
    requiresDbWrite: items.filter(i => i.requiresDbWrite).length,
    requiresExternalControl: items.filter(i => i.requiresExternalControl).length,
    requiresHumanApproval: items.filter(i => i.requiresHumanApproval).length,
    requiresEvidence: items.filter(i => i.requiresEvidence).length,
    requiresRollback: items.filter(i => i.requiresRollback).length,
  };
}

export function getGovernanceConsoleRiskItemsBySource(source: ConsoleRiskSource): GovernanceConsoleRiskItem[] {
  return RISK_ITEMS.filter(i => i.source === source);
}

export function getGovernanceConsoleRiskItemsByCategory(category: ConsoleRiskCategory): GovernanceConsoleRiskItem[] {
  return RISK_ITEMS.filter(i => i.category === category);
}

export function getGovernanceConsoleRiskItemsBySeverity(severity: ConsoleRiskSeverity): GovernanceConsoleRiskItem[] {
  return RISK_ITEMS.filter(i => i.severity === severity);
}

export function getGovernanceConsoleCriticalRisks(): GovernanceConsoleRiskItem[] {
  return RISK_ITEMS.filter(i => i.severity === 'critical');
}

export function getGovernanceConsoleBlockedRisks(): GovernanceConsoleRiskItem[] {
  return RISK_ITEMS.filter(i => i.blocked);
}
