export type ConsoleRegistryDomain =
  | 'permission'
  | 'runtime'
  | 'dry_run'
  | 'audit'
  | 'governance_state'
  | 'human_approval'
  | 'evidence'
  | 'rollback'
  | 'navigation'
  | 'center_access';

export type ConsoleRegistryReadiness =
  | 'ready_preview'
  | 'ready_with_notes'
  | 'blocked'
  | 'future_stage_c'
  | 'design_only';

export type ConsoleRiskLevel = 'low' | 'medium' | 'high' | 'critical';

export type ConsoleExposure =
  | 'sidebar'
  | 'hidden_direct'
  | 'docs_only'
  | 'internal_registry'
  | 'blocked';

export interface GovernanceConsoleRegistryItem {
  id: string;
  label: string;
  domain: ConsoleRegistryDomain;
  sourceRegistry: string;
  previewRoute?: string;
  validatorName?: string;
  exposure: ConsoleExposure;
  readiness: ConsoleRegistryReadiness;
  risk: ConsoleRiskLevel;
  allowedNow: boolean;
  inSidebar: boolean;
  requiresStageC: boolean;
  requiresDbWrite: boolean;
  requiresExternalControl: boolean;
  supportsExecution: boolean;
  writesData: boolean;
  summaryFields: string[];
  riskFields: string[];
  traceFields: string[];
  linkedDocs: string[];
  gates: string[];
  blockedActions: string[];
  reason: string;
  nextAction: string;
}

const GOVERNANCE_CONSOLE_REGISTRY: GovernanceConsoleRegistryItem[] = [
  {
    id: 'permission-evaluator',
    label: 'Permission Evaluator',
    domain: 'permission',
    sourceRegistry: 'permission-evaluator-registry.ts',
    previewRoute: '/permission-evaluator-preview',
    validatorName: 'Inline (permission-evaluator-registry.ts)',
    exposure: 'hidden_direct',
    readiness: 'ready_preview',
    risk: 'low',
    allowedNow: true,
    inSidebar: false,
    requiresStageC: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    supportsExecution: false,
    writesData: false,
    summaryFields: ['permission_rules', 'gates', 'blocking_conditions'],
    riskFields: ['severity', 'risk'],
    traceFields: ['targetId', 'targetKind', 'enforcementStage'],
    linkedDocs: [],
    gates: ['readonly_only'],
    blockedActions: ['execute_action', 'write_database', 'control_external'],
    reason: 'Permission Evaluator preview is readonly. No permission execution or gate transition.',
    nextAction: 'Keep readonly preview. Do not enable permission execution.',
  },
  {
    id: 'runtime-registry',
    label: 'Runtime Registry',
    domain: 'runtime',
    sourceRegistry: 'runtime-registry.ts',
    previewRoute: '/runtime-registry-preview',
    validatorName: 'runtime-registry-validator.ts',
    exposure: 'hidden_direct',
    readiness: 'ready_preview',
    risk: 'low',
    allowedNow: true,
    inSidebar: false,
    requiresStageC: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    supportsExecution: false,
    writesData: false,
    summaryFields: ['capabilities', 'readiness', 'dependencies'],
    riskFields: ['risk', 'requiresStageC', 'requiresDbWrite'],
    traceFields: ['allowedNow', 'gates', 'blockedActions'],
    linkedDocs: [],
    gates: ['readonly_only', 'no_runtime_implementation'],
    blockedActions: ['execute_action', 'write_database', 'control_external', 'start_service', 'stop_service'],
    reason: 'Runtime Registry preview is readonly. No runtime executor or service management.',
    nextAction: 'Keep readonly preview. Do not implement runtime executor.',
  },
  {
    id: 'dry-run-plan',
    label: 'Dry-run Plan',
    domain: 'dry_run',
    sourceRegistry: 'dry-run-plan-registry.ts',
    previewRoute: '/dry-run-plan-preview',
    validatorName: 'dry-run-plan-validator.ts',
    exposure: 'hidden_direct',
    readiness: 'ready_preview',
    risk: 'low',
    allowedNow: true,
    inSidebar: false,
    requiresStageC: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    supportsExecution: false,
    writesData: false,
    summaryFields: ['plan_items', 'readiness', 'blocked_actions'],
    riskFields: ['risk', 'requiresStageC', 'requiresExternalControl'],
    traceFields: ['allowedNow', 'gates', 'executesAction'],
    linkedDocs: [],
    gates: ['readonly_only', 'no_dry_run_executor'],
    blockedActions: ['execute_dry_run', 'write_database', 'control_external'],
    reason: 'Dry-run Plan preview is readonly. No dry-run executor or plan execution.',
    nextAction: 'Keep readonly preview. Do not implement dry-run executor.',
  },
  {
    id: 'audit-log',
    label: 'Audit Log',
    domain: 'audit',
    sourceRegistry: 'audit-log-registry.ts',
    previewRoute: '/audit-log-preview',
    validatorName: 'audit-log-validator.ts',
    exposure: 'hidden_direct',
    readiness: 'ready_preview',
    risk: 'low',
    allowedNow: true,
    inSidebar: false,
    requiresStageC: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    supportsExecution: false,
    writesData: false,
    summaryFields: ['event_types', 'sources', 'severity_levels'],
    riskFields: ['risk', 'severity'],
    traceFields: ['allowedNow', 'gates'],
    linkedDocs: [],
    gates: ['readonly_only', 'no_audit_write'],
    blockedActions: ['write_audit_log', 'write_database'],
    reason: 'Audit Log preview is readonly. No audit log writer or DB write.',
    nextAction: 'Keep readonly preview. Do not implement audit logger.',
  },
  {
    id: 'governance-state',
    label: 'Governance State Machine',
    domain: 'governance_state',
    sourceRegistry: 'governance-state-registry.ts',
    previewRoute: '/governance-state-machine-preview',
    validatorName: 'governance-state-validator.ts',
    exposure: 'hidden_direct',
    readiness: 'ready_preview',
    risk: 'low',
    allowedNow: true,
    inSidebar: false,
    requiresStageC: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    supportsExecution: false,
    writesData: false,
    summaryFields: ['states', 'transitions', 'readiness'],
    riskFields: ['risk', 'requiresStageC', 'requiresDbWrite', 'requiresExternalControl'],
    traceFields: ['allowedNow', 'gates', 'blockedActions'],
    linkedDocs: ['AIP_GOVERNANCE_STATE_MACHINE_PREVIEW.md'],
    gates: ['readonly_only', 'no_state_transition'],
    blockedActions: ['transition_state', 'write_database', 'control_external', 'enable_stage_c'],
    reason: 'Governance State Machine preview is readonly. No state transitions or mutations.',
    nextAction: 'Keep readonly preview. Do not implement state machine executor.',
  },
  {
    id: 'human-approval',
    label: 'Human Approval Workflow',
    domain: 'human_approval',
    sourceRegistry: 'human-approval-registry.ts',
    previewRoute: '/human-approval-workflow-preview',
    validatorName: 'human-approval-validator.ts',
    exposure: 'hidden_direct',
    readiness: 'ready_preview',
    risk: 'low',
    allowedNow: true,
    inSidebar: false,
    requiresStageC: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    supportsExecution: false,
    writesData: false,
    summaryFields: ['request_kinds', 'states', 'decision_matrix'],
    riskFields: ['risk', 'requiresStageC'],
    traceFields: ['allowedNow', 'gates', 'requiresHumanApproval'],
    linkedDocs: ['AIP_HUMAN_APPROVAL_WORKFLOW_SPEC.md', 'AIP_HUMAN_APPROVAL_WORKFLOW_PREVIEW.md'],
    gates: ['readonly_only', 'no_approval_queue'],
    blockedActions: ['approve', 'reject', 'archive', 'write_database', 'process_candidate'],
    reason: 'Human Approval Workflow preview is readonly. No approval queue or candidate processing.',
    nextAction: 'Keep readonly preview. Do not implement approval queue.',
  },
  {
    id: 'evidence-schema',
    label: 'Evidence Schema',
    domain: 'evidence',
    sourceRegistry: 'evidence-schema-registry.ts',
    previewRoute: '/evidence-schema-preview',
    validatorName: 'evidence-schema-validator.ts',
    exposure: 'hidden_direct',
    readiness: 'ready_preview',
    risk: 'low',
    allowedNow: true,
    inSidebar: false,
    requiresStageC: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    supportsExecution: false,
    writesData: false,
    summaryFields: ['types', 'sources', 'sensitivity_levels', 'retention_policies'],
    riskFields: ['sensitivity', 'retention', 'requiresRedaction'],
    traceFields: ['allowedNow', 'gates'],
    linkedDocs: ['AIP_EVIDENCE_SCHEMA_PREVIEW.md'],
    gates: ['readonly_only', 'no_evidence_capture'],
    blockedActions: ['capture_evidence', 'store_evidence', 'write_database', 'capture_secret'],
    reason: 'Evidence Schema preview is readonly. No evidence capture or secret storage.',
    nextAction: 'Keep readonly preview. Do not implement evidence store.',
  },
  {
    id: 'rollback',
    label: 'Rollback Preview',
    domain: 'rollback',
    sourceRegistry: 'rollback-registry.ts',
    previewRoute: '/rollback-preview',
    validatorName: 'rollback-validator.ts',
    exposure: 'hidden_direct',
    readiness: 'ready_preview',
    risk: 'low',
    allowedNow: true,
    inSidebar: false,
    requiresStageC: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    supportsExecution: false,
    writesData: false,
    summaryFields: ['targets', 'rollback_types', 'preconditions', 'evidence_requirements'],
    riskFields: ['risk', 'requiresStageC', 'requiresDbWrite', 'requiresExternalControl', 'executesRollback'],
    traceFields: ['allowedNow', 'gates', 'irreversible', 'idempotencyKeyRequired'],
    linkedDocs: ['AIP_ROLLBACK_PREVIEW.md'],
    gates: ['readonly_only', 'no_rollback_execution'],
    blockedActions: ['execute_rollback', 'restore_file', 'git_reset', 'git_revert', 'git_tag', 'git_release', 'write_database'],
    reason: 'Rollback Preview is readonly. No rollback executor or file restore.',
    nextAction: 'Keep readonly preview. Do not implement rollback executor.',
  },
  {
    id: 'navigation-exposure',
    label: 'Navigation Exposure Registry',
    domain: 'navigation',
    sourceRegistry: 'navigation-exposure-registry.ts',
    previewRoute: undefined,
    validatorName: 'Inline (navigation-exposure-registry.ts)',
    exposure: 'internal_registry',
    readiness: 'ready_preview',
    risk: 'low',
    allowedNow: true,
    inSidebar: false,
    requiresStageC: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    supportsExecution: false,
    writesData: false,
    summaryFields: ['routes', 'exposure_levels', 'gates'],
    riskFields: ['risk'],
    traceFields: ['allowedNow', 'gates', 'reason'],
    linkedDocs: [],
    gates: [],
    blockedActions: ['add_sidebar_entry'],
    reason: 'Navigation Exposure Registry is an internal configuration registry. No execution.',
    nextAction: 'Keep internal registry. Do not expose as preview.',
  },
  {
    id: 'center-access',
    label: 'Center Access Registry',
    domain: 'center_access',
    sourceRegistry: 'center-access-registry.ts',
    previewRoute: undefined,
    validatorName: 'Inline (center-access-registry.ts)',
    exposure: 'internal_registry',
    readiness: 'ready_preview',
    risk: 'low',
    allowedNow: true,
    inSidebar: false,
    requiresStageC: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    supportsExecution: false,
    writesData: false,
    summaryFields: ['centers', 'status', 'visibility'],
    riskFields: ['risk'],
    traceFields: ['status', 'visibleInSidebar', 'allowedNow'],
    linkedDocs: [],
    gates: [],
    blockedActions: ['change_sidebar_visibility', 'change_exposure'],
    reason: 'Center Access Registry is an internal configuration registry. No execution.',
    nextAction: 'Keep internal registry. Do not expose as preview.',
  },
  {
    id: 'advanced-mode',
    label: 'Advanced Mode Preview',
    domain: 'center_access',
    sourceRegistry: 'center-access-registry.ts (advanced entry)',
    previewRoute: '/advanced-mode-readonly',
    validatorName: 'Inline (center-access-registry.ts)',
    exposure: 'sidebar',
    readiness: 'ready_preview',
    risk: 'low',
    allowedNow: true,
    inSidebar: true,
    requiresStageC: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    supportsExecution: false,
    writesData: false,
    summaryFields: ['system_overview', 'safety_boundary', 'capability_status'],
    riskFields: [],
    traceFields: [],
    linkedDocs: [],
    gates: ['readonly_only'],
    blockedActions: ['modify_system', 'write_database', 'control_external', 'enable_stage_c'],
    reason: 'Advanced Mode Preview is in sidebar but is readonly. No system configuration modification.',
    nextAction: 'Keep readonly preview. Do not add system controls.',
  },
  {
    id: 'connector-center',
    label: 'Connector Center',
    domain: 'center_access',
    sourceRegistry: 'center-access-registry.ts (connector entry)',
    previewRoute: '/connector-center-readonly',
    validatorName: 'Inline (center-access-registry.ts)',
    exposure: 'sidebar',
    readiness: 'ready_preview',
    risk: 'low',
    allowedNow: true,
    inSidebar: true,
    requiresStageC: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    supportsExecution: false,
    writesData: false,
    summaryFields: ['connector_readiness', 'connection_status', 'capabilities'],
    riskFields: ['risk'],
    traceFields: ['allowedNow', 'gates'],
    linkedDocs: [],
    gates: ['readonly_only'],
    blockedActions: ['connect', 'disconnect', 'control_external', 'write_database', 'execute_action'],
    reason: 'Connector Center is in sidebar but is readonly. No external tool connection or control.',
    nextAction: 'Keep readonly preview. Do not add connector controls.',
  },
  {
    id: 'lab-center',
    label: 'Lab Center',
    domain: 'center_access',
    sourceRegistry: 'center-access-registry.ts (lab entry)',
    previewRoute: '/lab-center-readonly',
    validatorName: 'Inline (center-access-registry.ts)',
    exposure: 'hidden_direct',
    readiness: 'ready_preview',
    risk: 'medium',
    allowedNow: true,
    inSidebar: false,
    requiresStageC: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    supportsExecution: false,
    writesData: false,
    summaryFields: ['experiments', 'evaluations', 'runs'],
    riskFields: ['risk'],
    traceFields: ['allowedNow', 'gates'],
    linkedDocs: [],
    gates: ['readonly_only'],
    blockedActions: ['run_experiment', 'write_database', 'control_external'],
    reason: 'Lab Center is hidden direct. Readonly preview. No experiment execution.',
    nextAction: 'Keep readonly preview. Do not implement lab executor.',
  },
  {
    id: 'governance-center',
    label: 'Governance Center',
    domain: 'center_access',
    sourceRegistry: 'center-access-registry.ts (governance entry)',
    previewRoute: undefined,
    validatorName: 'Inline (center-access-registry.ts)',
    exposure: 'hidden_direct',
    readiness: 'design_only',
    risk: 'medium',
    allowedNow: false,
    inSidebar: false,
    requiresStageC: true,
    requiresDbWrite: true,
    requiresExternalControl: true,
    supportsExecution: false,
    writesData: false,
    summaryFields: ['governance_overview', 'policy_status', 'compliance'],
    riskFields: ['risk', 'requiresStageC', 'requiresDbWrite', 'requiresExternalControl'],
    traceFields: [],
    linkedDocs: [],
    gates: ['readonly_only', 'stage_c_disabled'],
    blockedActions: ['enable_governance', 'write_database', 'control_external', 'enable_stage_c'],
    reason: 'Governance Center is design-only. Requires Stage C, DB write, and external control.',
    nextAction: 'Keep blocked. Governance Center requires Stage C implementation.',
  },
  {
    id: 'navigation-preview',
    label: 'Navigation Preview',
    domain: 'navigation',
    sourceRegistry: 'navigation-exposure-registry.ts (navigation preview entry)',
    previewRoute: undefined,
    validatorName: 'Inline (navigation-exposure-registry.ts)',
    exposure: 'hidden_direct',
    readiness: 'ready_preview',
    risk: 'low',
    allowedNow: true,
    inSidebar: false,
    requiresStageC: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    supportsExecution: false,
    writesData: false,
    summaryFields: ['sidebar_items', 'exposure', 'gates'],
    riskFields: [],
    traceFields: [],
    linkedDocs: [],
    gates: ['readonly_only'],
    blockedActions: ['modify_sidebar', 'change_exposure'],
    reason: 'Navigation Preview is hidden direct. Readonly. No sidebar modification.',
    nextAction: 'Keep readonly preview. Do not enable sidebar editing.',
  },
  {
    id: 'stage-c',
    label: 'Stage C',
    domain: 'center_access',
    sourceRegistry: 'Cross-registry (permission-evaluator, governance-state, rollback, etc.)',
    previewRoute: undefined,
    validatorName: 'All validators',
    exposure: 'blocked',
    readiness: 'blocked',
    risk: 'critical',
    allowedNow: false,
    inSidebar: false,
    requiresStageC: true,
    requiresDbWrite: true,
    requiresExternalControl: true,
    supportsExecution: true,
    writesData: true,
    summaryFields: [],
    riskFields: ['critical'],
    traceFields: [],
    linkedDocs: ['AIP_STAGE_C_READINESS_CHECKLIST.md'],
    gates: ['stage_c_disabled', 'irreversible_action'],
    blockedActions: ['enable_stage_c', 'transition_stage', 'execute_action', 'write_database', 'control_external'],
    reason: 'Stage C is permanently disabled across all preview systems.',
    nextAction: 'Keep Stage C permanently disabled. Do not design Stage C rollback.',
  },
  {
    id: 'db-write',
    label: 'Database Write',
    domain: 'center_access',
    sourceRegistry: 'Cross-registry (permission-evaluator, governance-state, rollback, etc.)',
    previewRoute: undefined,
    validatorName: 'All validators',
    exposure: 'blocked',
    readiness: 'blocked',
    risk: 'critical',
    allowedNow: false,
    inSidebar: false,
    requiresStageC: true,
    requiresDbWrite: true,
    requiresExternalControl: false,
    supportsExecution: false,
    writesData: true,
    summaryFields: [],
    riskFields: ['critical'],
    traceFields: [],
    linkedDocs: [],
    gates: ['stage_c_disabled', 'readonly_only'],
    blockedActions: ['write_database', 'write_audit_log', 'write_evidence'],
    reason: 'Database write is blocked. No DB schema or write service exists.',
    nextAction: 'Keep DB write blocked. Do not implement DB writes.',
  },
  {
    id: 'external-control',
    label: 'External Control',
    domain: 'center_access',
    sourceRegistry: 'Cross-registry (connector, rollback, dry-run, governance)',
    previewRoute: undefined,
    validatorName: 'All validators',
    exposure: 'blocked',
    readiness: 'blocked',
    risk: 'critical',
    allowedNow: false,
    inSidebar: false,
    requiresStageC: true,
    requiresDbWrite: false,
    requiresExternalControl: true,
    supportsExecution: true,
    writesData: false,
    summaryFields: [],
    riskFields: ['critical'],
    traceFields: [],
    linkedDocs: [],
    gates: ['stage_c_disabled', 'readonly_only'],
    blockedActions: ['control_external', 'connect', 'execute_action', 'write_database'],
    reason: 'External control is blocked. No connector endpoints or execution service.',
    nextAction: 'Keep external control blocked. Do not implement external tool control.',
  },
];

export function getGovernanceConsoleRegistryItems(): GovernanceConsoleRegistryItem[] {
  return GOVERNANCE_CONSOLE_REGISTRY;
}

export function getGovernanceConsoleRegistrySummary() {
  const items = GOVERNANCE_CONSOLE_REGISTRY;
  return {
    total: items.length,
    readyPreview: items.filter(i => i.readiness === 'ready_preview').length,
    blocked: items.filter(i => i.readiness === 'blocked' || !i.allowedNow).length,
    highOrCritical: items.filter(i => i.risk === 'high' || i.risk === 'critical').length,
    sidebar: items.filter(i => i.inSidebar).length,
    hiddenDirect: items.filter(i => !i.inSidebar && i.exposure === 'hidden_direct').length,
    requiresStageC: items.filter(i => i.requiresStageC).length,
    requiresDbWrite: items.filter(i => i.requiresDbWrite).length,
    requiresExternalControl: items.filter(i => i.requiresExternalControl).length,
    supportsExecution: items.filter(i => i.supportsExecution).length,
    writesData: items.filter(i => i.writesData).length,
  };
}

export function getGovernanceConsoleItemsByDomain(domain: ConsoleRegistryDomain): GovernanceConsoleRegistryItem[] {
  return GOVERNANCE_CONSOLE_REGISTRY.filter(i => i.domain === domain);
}

export function getGovernanceConsoleItemsByReadiness(readiness: ConsoleRegistryReadiness): GovernanceConsoleRegistryItem[] {
  return GOVERNANCE_CONSOLE_REGISTRY.filter(i => i.readiness === readiness);
}

export function getGovernanceConsoleItemsByRisk(risk: ConsoleRiskLevel): GovernanceConsoleRegistryItem[] {
  return GOVERNANCE_CONSOLE_REGISTRY.filter(i => i.risk === risk);
}

export function getGovernanceConsoleBlockedItems(): GovernanceConsoleRegistryItem[] {
  return GOVERNANCE_CONSOLE_REGISTRY.filter(i => !i.allowedNow);
}

export function getGovernanceConsoleHiddenPreviewItems(): GovernanceConsoleRegistryItem[] {
  return GOVERNANCE_CONSOLE_REGISTRY.filter(i => i.exposure === 'hidden_direct' && i.previewRoute);
}
