// Menu Registry — shadow data file
// Mirrors current Layout.tsx sidebar menu structure.
// NOT referenced by Layout.tsx — shadow mode only.

export type MenuMaturity = 'stable' | 'preview' | 'lab' | 'external' | 'archived';
export type MenuRiskLevel = 'low' | 'medium' | 'high';
export type MenuPageType =
  | 'core'
  | 'governance'
  | 'training'
  | 'model'
  | 'data'
  | 'workflow'
  | 'connector'
  | 'lab'
  | 'placeholder'
  | 'preview'
  | 'system';

export interface MenuRegistryItem {
  id: string;
  label: string;
  labelKey?: string;
  path: string;
  icon?: string;
  maturity: MenuMaturity;
  riskLevel: MenuRiskLevel;
  pageType: MenuPageType;
  owner: string;
  notes?: string;
  currentNav: true;
}

export interface MenuRegistrySection {
  id: string;
  label: string;
  labelKey?: string;
  collapsedByDefault?: boolean;
  items: MenuRegistryItem[];
}

export const MENU_REGISTRY: MenuRegistrySection[] = [
  // ── OpenAIP (primary section) ──
  {
    id: 'openAip',
    label: 'OpenAIP',
    labelKey: 'nav.openAip',
    items: [
      {
        id: 'openaip-v8-command-center-preview',
        label: '指挥中心',
        labelKey: 'nav.openAipV8CommandCenter',
        path: '/openaip-v8-command-center-preview',
        icon: 'command',
        maturity: 'preview',
        riskLevel: 'low',
        pageType: 'core',
        owner: 'openaip-v8',
        notes: 'Wave 2 可见 v8 入口。只读指挥中心；不提供执行、启动、provider 切换或配置写入能力。',
        currentNav: true,
      },
      {
        id: 'openaip-v8-agent-center-preview',
        label: '智能体',
        labelKey: 'nav.openAipV8AgentCenter',
        path: '/openaip-v8-agent-center-preview',
        icon: 'bot',
        maturity: 'preview',
        riskLevel: 'low',
        pageType: 'core',
        owner: 'openaip-v8',
        notes: '只读智能体中心。展示 Agent 生命周期和权限，不执行 agent，不派发任务，不写配置。',
        currentNav: true,
      },
      {
        id: 'openaip-v8-task-center-preview',
        label: '任务',
        labelKey: 'nav.openAipV8TaskCenter',
        path: '/openaip-v8-task-center-preview',
        icon: 'tasks',
        maturity: 'preview',
        riskLevel: 'low',
        pageType: 'core',
        owner: 'openaip-v8',
        notes: '只读任务中心。展示 task pack、receipt、review queue，不执行任务，不写 DB。',
        currentNav: true,
      },
      {
        id: 'openaip-v8-audit-center-preview',
        label: '审计',
        labelKey: 'nav.openAipV8AuditCenter',
        path: '/openaip-v8-audit-center-preview',
        icon: 'shield',
        maturity: 'preview',
        riskLevel: 'low',
        pageType: 'governance',
        owner: 'openaip-v8',
        notes: '只读审计中心。展示 evidence/receipt 规则，不写 audit DB，不审批。',
        currentNav: true,
      },
      {
        id: 'openaip-v8-policy-capability-center-preview',
        label: '策略',
        labelKey: 'nav.openAipV8PolicyCapabilityCenter',
        path: '/openaip-v8-policy-capability-center-preview',
        icon: 'lock',
        maturity: 'preview',
        riskLevel: 'low',
        pageType: 'governance',
        owner: 'openaip-v8',
        notes: '只读策略与能力中心。展示 policy/capability 矩阵，不开启能力，不打开 Gate。',
        currentNav: true,
      },
      {
        id: 'openaip-v8-execution-gateway-preview',
        label: '执行网关',
        labelKey: 'nav.openAipV8ExecutionGateway',
        path: '/openaip-v8-execution-gateway-preview',
        icon: 'power',
        maturity: 'preview',
        riskLevel: 'low',
        pageType: 'governance',
        owner: 'openaip-v8',
        notes: '只读边界页。Execution Gateway 仍为 closed boundary，不执行、不打开 Gate、不启用 Stage C。',
        currentNav: true,
      },
    ],
  },

  // ── Resources ──
  {
    id: 'resources',
    label: '资源',
    labelKey: 'nav.resources',
    items: [
      {
        id: 'openaip-v8-provider-manager-preview',
        label: '供应商',
        labelKey: 'nav.openAipV8ProviderManager',
        path: '/openaip-v8-provider-manager-preview',
        icon: 'server',
        maturity: 'preview',
        riskLevel: 'low',
        pageType: 'connector',
        owner: 'openaip-v8',
        notes: '只读供应商管理。展示 provider registry，不切换 provider，不调用模型，不显示 API key 输入。',
        currentNav: true,
      },
      {
        id: 'openaip-v8-integration-center-preview',
        label: '集成',
        labelKey: 'nav.openAipV8IntegrationCenter',
        path: '/openaip-v8-integration-center-preview',
        icon: 'plug',
        maturity: 'preview',
        riskLevel: 'low',
        pageType: 'connector',
        owner: 'openaip-v8',
        notes: '只读集成中心。展示 connector 迁移桥，不执行 connector action，不调用外部 API，不写配置。',
        currentNav: true,
      },
      {
        id: 'openaip-v8-local-apps-center-preview',
        label: '本地应用',
        labelKey: 'nav.openAipV8LocalAppsCenter',
        path: '/openaip-v8-local-apps-center-preview',
        icon: 'monitor',
        maturity: 'preview',
        riskLevel: 'low',
        pageType: 'connector',
        owner: 'openaip-v8',
        notes: '只读本地应用中心。展示 local app registry，不启动本地应用，不调用 local app API。',
        currentNav: true,
      },
      {
        id: 'openaip-v8-memory-knowledge-center-preview',
        label: '记忆与知识',
        labelKey: 'nav.openAipV8MemoryKnowledgeCenter',
        path: '/openaip-v8-memory-knowledge-center-preview',
        icon: 'database',
        maturity: 'preview',
        riskLevel: 'low',
        pageType: 'core',
        owner: 'openaip-v8',
        notes: '只读记忆与知识中心。展示 memory/knowledge registry，不写 memory DB，不写 vector DB，不运行 indexing job。',
        currentNav: true,
      },
      {
        id: 'connector-center-readonly',
        label: '连接器',
        labelKey: 'nav.connectorCenterReadonly',
        path: '/connector-center-readonly',
        icon: 'zap',
        maturity: 'preview',
        riskLevel: 'low',
        pageType: 'connector',
        owner: 'connector',
        notes: '兼容视图。新的外部服务接入能力请使用"集成"页面。',
        currentNav: true,
      },
    ],
  },

  // ── Workbench ──
  {
    id: 'workbench',
    label: '工作台',
    labelKey: 'nav.workbench',
    items: [
      {
        id: 'datasets',
        label: '数据集',
        labelKey: 'nav.datasets',
        path: '/datasets',
        icon: 'dataset',
        maturity: 'stable',
        riskLevel: 'low',
        pageType: 'data',
        owner: 'core',
        notes: '数据集管理，生产就绪',
        currentNav: true,
      },
      {
        id: 'training',
        label: '训练',
        labelKey: 'nav.trainingCenter',
        path: '/training',
        icon: 'training',
        maturity: 'stable',
        riskLevel: 'medium',
        pageType: 'training',
        owner: 'core',
        notes: '可触发训练任务',
        currentNav: true,
      },
      {
        id: 'runs',
        label: '运行',
        labelKey: 'nav.runCenter',
        path: '/runs',
        icon: 'run',
        maturity: 'stable',
        riskLevel: 'medium',
        pageType: 'training',
        owner: 'core',
        notes: '任务运行记录查看',
        currentNav: true,
      },
      {
        id: 'templates',
        label: '模板',
        labelKey: 'nav.templates',
        path: '/templates',
        icon: 'template',
        maturity: 'stable',
        riskLevel: 'low',
        pageType: 'data',
        owner: 'core',
        notes: '模板管理，生产就绪',
        currentNav: true,
      },
      {
        id: 'models',
        label: '模型',
        labelKey: 'nav.modelMgmt',
        path: '/models',
        icon: 'artifact',
        maturity: 'stable',
        riskLevel: 'medium',
        pageType: 'model',
        owner: 'core',
        notes: '模型注册表，生产就绪',
        currentNav: true,
      },
      {
        id: 'artifacts',
        label: '模型产物',
        labelKey: 'nav.artifacts',
        path: '/artifacts',
        icon: 'artifact',
        maturity: 'stable',
        riskLevel: 'low',
        pageType: 'model',
        owner: 'core',
        notes: '产物存储管理',
        currentNav: true,
      },
      {
        id: 'evaluations',
        label: '评估',
        labelKey: 'nav.evalCenter',
        path: '/evaluations',
        icon: 'eval',
        maturity: 'stable',
        riskLevel: 'low',
        pageType: 'model',
        owner: 'core',
        notes: '模型评估结果查看',
        currentNav: true,
      },
      {
        id: 'deployments',
        label: '部署',
        labelKey: 'nav.deployCenter',
        path: '/deployments',
        icon: 'deploy',
        maturity: 'stable',
        riskLevel: 'medium',
        pageType: 'model',
        owner: 'core',
        notes: '可触发部署动作',
        currentNav: true,
      },
      {
        id: 'workflow-jobs',
        label: '工作流',
        labelKey: 'nav.workflow',
        path: '/workflow-jobs',
        icon: 'workflow',
        maturity: 'stable',
        riskLevel: 'medium',
        pageType: 'workflow',
        owner: 'core',
        notes: '工作流任务管理',
        currentNav: true,
      },
      {
        id: 'workflow-composer',
        label: '工作流编排器',
        labelKey: 'nav.workflowComposer',
        path: '/workflow-composer',
        icon: 'composer',
        maturity: 'stable',
        riskLevel: 'medium',
        pageType: 'workflow',
        owner: 'core',
        notes: '最复杂页面，2400 行',
        currentNav: true,
      },
      {
        id: 'workflow-canvas',
        label: '流程运行画布',
        labelKey: 'nav.workflowCanvas',
        path: '/workflow-canvas',
        icon: 'workflow',
        maturity: 'stable',
        riskLevel: 'medium',
        pageType: 'workflow',
        owner: 'core',
        notes: '画布运行视图',
        currentNav: true,
      },
    ],
  },

  // ── System ──
  {
    id: 'system',
    label: '系统',
    labelKey: 'nav.system',
    items: [
      {
        id: 'dashboard',
        label: '仪表板',
        labelKey: 'nav.dashboard',
        path: '/',
        icon: 'dashboard',
        maturity: 'stable',
        riskLevel: 'low',
        pageType: 'core',
        owner: 'core',
        notes: 'AIP 主驾驶舱',
        currentNav: true,
      },
      {
        id: 'factory-status',
        label: '系统状态',
        labelKey: 'nav.factoryStatus',
        path: '/factory-status',
        icon: 'factory',
        maturity: 'stable',
        riskLevel: 'low',
        pageType: 'core',
        owner: 'core',
        notes: '系统级状态面板',
        currentNav: true,
      },
      {
        id: 'assistant-center',
        label: '助手',
        labelKey: 'nav.assistantCenter',
        path: '/assistant-center',
        icon: 'modules',
        maturity: 'preview',
        riskLevel: 'low',
        pageType: 'core',
        owner: 'core',
        notes: 'P1d 已接入 PageShell',
        currentNav: true,
      },
      {
        id: 'module-center',
        label: '模块中心',
        labelKey: 'nav.moduleCenter',
        path: '/module-center',
        icon: 'modules',
        maturity: 'stable',
        riskLevel: 'low',
        pageType: 'core',
        owner: 'core',
        notes: '模块管理中枢，生产就绪',
        currentNav: true,
      },
      {
        id: 'plugin-pool',
        label: '插件',
        labelKey: 'nav.pluginPool',
        path: '/plugin-pool',
        icon: 'api',
        maturity: 'stable',
        riskLevel: 'low',
        pageType: 'core',
        owner: 'core',
        notes: '插件注册与管理',
        currentNav: true,
      },
      {
        id: 'tasks',
        label: '任务编排',
        labelKey: 'nav.taskOrchestration',
        path: '/tasks',
        icon: 'tasks',
        maturity: 'stable',
        riskLevel: 'medium',
        pageType: 'core',
        owner: 'core',
        notes: '可创建和执行任务',
        currentNav: true,
      },
      {
        id: 'cost-routing',
        label: '成本路由',
        labelKey: 'nav.costRouting',
        path: '/cost-routing',
        icon: 'route',
        maturity: 'stable',
        riskLevel: 'low',
        pageType: 'governance',
        owner: 'governance',
        notes: 'P1a 已接入 PageShell',
        currentNav: true,
      },
      {
        id: 'approvals',
        label: '审批',
        labelKey: 'nav.approvals',
        path: '/approvals',
        icon: 'approval',
        maturity: 'stable',
        riskLevel: 'medium',
        pageType: 'governance',
        owner: 'governance',
        notes: '审批管理',
        currentNav: true,
      },
      {
        id: 'governance-hub',
        label: '治理中枢',
        labelKey: 'nav.governanceHub',
        path: '/governance-hub',
        icon: 'audit',
        maturity: 'stable',
        riskLevel: 'medium',
        pageType: 'governance',
        owner: 'governance',
        notes: '治理中枢',
        currentNav: true,
      },
      {
        id: 'audit',
        label: '审计日志',
        labelKey: 'nav.audit',
        path: '/audit',
        icon: 'audit',
        maturity: 'stable',
        riskLevel: 'low',
        pageType: 'governance',
        owner: 'governance',
        notes: '审计日志查看',
        currentNav: true,
      },
      {
        id: 'feedback',
        label: '回流池',
        labelKey: 'nav.feedback',
        path: '/feedback',
        icon: 'feedback',
        maturity: 'stable',
        riskLevel: 'low',
        pageType: 'governance',
        owner: 'governance',
        notes: '用户回流建议',
        currentNav: true,
      },
      {
        id: 'advanced-mode-readonly',
        label: '高级模式',
        labelKey: 'nav.advancedModeReadonly',
        path: '/advanced-mode-readonly',
        icon: 'audit',
        maturity: 'preview',
        riskLevel: 'low',
        pageType: 'governance',
        owner: 'governance',
        notes: '只读入口。不启用 Advanced Mode，不启用 Stage C，不提供真实执行能力。',
        currentNav: true,
      },
      {
        id: 'knowledge-center',
        label: '知识中心',
        labelKey: 'nav.knowledgeCenter',
        path: '/knowledge',
        icon: 'knowledge',
        maturity: 'stable',
        riskLevel: 'low',
        pageType: 'core',
        owner: 'core',
        notes: '知识库管理，生产就绪',
        currentNav: true,
      },
      {
        id: 'standard-output',
        label: '标准输出',
        labelKey: 'nav.standardOutput',
        path: '/outputs',
        icon: 'output',
        maturity: 'stable',
        riskLevel: 'low',
        pageType: 'core',
        owner: 'core',
        notes: '标准输出查看，生产就绪',
        currentNav: true,
      },
    ],
  },

  // ── Advanced Tools ──
  {
    id: 'advancedTools',
    label: '高级工具',
    labelKey: 'nav.advancedTools',
    collapsedByDefault: true,
    items: [
      {
        id: 'openaxiom-readonly',
        label: 'OpenAxiom',
        labelKey: 'nav.openAxiomReadonly',
        path: '/openaxiom-readonly',
        icon: 'label',
        maturity: 'external',
        riskLevel: 'low',
        pageType: 'connector',
        owner: 'connector',
        notes: 'P1b 已接入 PageShell。外部工具只读页。',
        currentNav: true,
      },
      {
        id: 'memory-hub-readonly',
        label: 'Memory Hub',
        labelKey: 'nav.memoryHubReadonly',
        path: '/memory-hub',
        icon: 'database',
        maturity: 'external',
        riskLevel: 'low',
        pageType: 'connector',
        owner: 'connector',
        notes: 'P1b 已接入 PageShell。外部工具只读页。',
        currentNav: true,
      },
      {
        id: 'mahjong-debug',
        label: '麻将工具',
        labelKey: 'nav.mahjongDebug',
        path: '/vision-lab/mahjong-debug',
        icon: 'template',
        maturity: 'lab',
        riskLevel: 'medium',
        pageType: 'lab',
        owner: 'lab',
        notes: '调试工具页',
        currentNav: true,
      },
      {
        id: 'digital-employee',
        label: '数字员工',
        labelKey: 'nav.digitalEmployee',
        path: '/digital-employee',
        icon: 'brain',
        maturity: 'lab',
        riskLevel: 'medium',
        pageType: 'preview',
        owner: 'advanced',
        notes: 'Preview page',
        currentNav: true,
      },
      {
        id: 'training-v2',
        label: '训练工具',
        labelKey: 'nav.trainingV2',
        path: '/training-v2',
        icon: 'training',
        maturity: 'lab',
        riskLevel: 'medium',
        pageType: 'preview',
        owner: 'advanced',
        notes: 'Preview page',
        currentNav: true,
      },
      {
        id: 'hpo',
        label: '超参搜索',
        labelKey: 'nav.hpo',
        path: '/hpo',
        icon: 'run',
        maturity: 'lab',
        riskLevel: 'low',
        pageType: 'preview',
        owner: 'advanced',
        notes: 'Preview page',
        currentNav: true,
      },
      {
        id: 'distill',
        label: '知识蒸馏',
        labelKey: 'nav.distill',
        path: '/distill',
        icon: 'eval',
        maturity: 'lab',
        riskLevel: 'low',
        pageType: 'preview',
        owner: 'advanced',
        notes: 'Preview page',
        currentNav: true,
      },
      {
        id: 'model-merge',
        label: '模型合并',
        labelKey: 'nav.modelMerge',
        path: '/model-merge',
        icon: 'merge',
        maturity: 'lab',
        riskLevel: 'medium',
        pageType: 'preview',
        owner: 'advanced',
        notes: 'Preview page',
        currentNav: true,
      },
      {
        id: 'inference',
        label: '模型推理',
        labelKey: 'nav.inference',
        path: '/inference',
        icon: 'run',
        maturity: 'lab',
        riskLevel: 'medium',
        pageType: 'preview',
        owner: 'advanced',
        notes: 'Preview page',
        currentNav: true,
      },
      {
        id: 'annotation',
        label: '数据标注',
        labelKey: 'nav.annotation',
        path: '/annotation',
        icon: 'label',
        maturity: 'lab',
        riskLevel: 'low',
        pageType: 'preview',
        owner: 'advanced',
        notes: 'Preview page',
        currentNav: true,
      },
      {
        id: 'huggingface',
        label: '模型仓库',
        labelKey: 'nav.huggingface',
        path: '/huggingface',
        icon: 'api',
        maturity: 'lab',
        riskLevel: 'low',
        pageType: 'preview',
        owner: 'connector',
        notes: 'Preview page',
        currentNav: true,
      },
      {
        id: 'backflow-v2',
        label: '智能回流',
        labelKey: 'nav.backflowV2',
        path: '/backflow-v2',
        icon: 'feedback',
        maturity: 'lab',
        riskLevel: 'medium',
        pageType: 'preview',
        owner: 'advanced',
        notes: 'Preview page',
        currentNav: true,
      },
      {
        id: 'scheduler',
        label: '任务调度器',
        labelKey: 'nav.scheduler',
        path: '/scheduler',
        icon: 'clock',
        maturity: 'lab',
        riskLevel: 'medium',
        pageType: 'preview',
        owner: 'advanced',
        notes: 'Preview page',
        currentNav: true,
      },
      {
        id: 'alerting',
        label: '告警中心',
        labelKey: 'nav.alerting',
        path: '/alerting',
        icon: 'bell',
        maturity: 'lab',
        riskLevel: 'medium',
        pageType: 'preview',
        owner: 'advanced',
        notes: 'Preview page',
        currentNav: true,
      },
      {
        id: 'model-monitor',
        label: '模型监控',
        labelKey: 'nav.modelMonitor',
        path: '/model-monitor',
        icon: 'eval',
        maturity: 'lab',
        riskLevel: 'medium',
        pageType: 'preview',
        owner: 'advanced',
        notes: 'Preview page',
        currentNav: true,
      },
      {
        id: 'deploy-v2',
        label: '发布管道',
        labelKey: 'nav.deployV2',
        path: '/deploy-v2',
        icon: 'deploy',
        maturity: 'lab',
        riskLevel: 'high',
        pageType: 'preview',
        owner: 'advanced',
        notes: 'Preview page',
        currentNav: true,
      },
    ],
  },
];

export function getMenuRegistryItemCount(): number {
  return MENU_REGISTRY.reduce((sum, section) => sum + section.items.length, 0);
}

export function getMenuRegistrySectionCount(): number {
  return MENU_REGISTRY.length;
}
