export type RollbackTarget =
  | 'runtime_registry'
  | 'dry_run_plan'
  | 'audit_log'
  | 'human_approval'
  | 'governance_state'
  | 'evidence_schema'
  | 'permission_evaluator'
  | 'connector_center'
  | 'git'
  | 'database'
  | 'external_tool'
  | 'stage_c'
  | 'local_file';

export type RollbackType =
  | 'preview_only'
  | 'idempotency_check'
  | 'risk_assessment'
  | 'manual_recovery_plan'
  | 'human_approved_rollback'
  | 'blocked_irreversible'
  | 'future_stage_c';

export type RollbackRisk = 'low' | 'medium' | 'high' | 'critical';

export type RollbackReadiness =
  | 'readonly_preview'
  | 'design_only'
  | 'manual_review_required'
  | 'blocked'
  | 'future';

export interface RollbackRegistryItem {
  id: string;
  label: string;
  target: RollbackTarget;
  rollbackType: RollbackType;
  risk: RollbackRisk;
  readiness: RollbackReadiness;
  allowedNow: boolean;
  previewOnly: boolean;
  reversible: boolean;
  irreversible: boolean;
  requiresHumanApproval: boolean;
  requiresEvidence: boolean;
  requiresAuditLog: boolean;
  requiresDbWrite: boolean;
  requiresExternalControl: boolean;
  requiresStageC: boolean;
  executesRollback: boolean;
  modifiesFiles: boolean;
  modifiesGit: boolean;
  idempotencyKeyRequired: boolean;
  preconditions: string[];
  evidenceRequired: string[];
  rollbackStepsPreview: string[];
  failureModes: string[];
  blockedActions: string[];
  gates: string[];
  reason: string;
  nextAction: string;
}

const ROLLBACK_REGISTRY: RollbackRegistryItem[] = [
  {
    id: 'runtime-registry-preview-rollback',
    label: 'Runtime Registry Preview Rollback',
    target: 'runtime_registry',
    rollbackType: 'preview_only',
    risk: 'low',
    readiness: 'readonly_preview',
    allowedNow: true,
    previewOnly: true,
    reversible: true,
    irreversible: false,
    requiresHumanApproval: false,
    requiresEvidence: false,
    requiresAuditLog: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    requiresStageC: false,
    executesRollback: false,
    modifiesFiles: false,
    modifiesGit: false,
    idempotencyKeyRequired: false,
    preconditions: ['Runtime registry must be in readonly mode'],
    evidenceRequired: ['runtime-registry-snapshot'],
    rollbackStepsPreview: ['No rollback needed — registry snapshot is static readonly view'],
    failureModes: ['N/A — no runtime action to fail'],
    blockedActions: ['execute_rollback', 'restore', 'recover', 'reset'],
    gates: ['readonly_only', 'no_rollback_execution'],
    reason: 'Runtime Registry Preview is a static readonly model — no runtime actions to roll back',
    nextAction: 'Continue using readonly preview. Rollback design not yet implemented.',
  },
  {
    id: 'dry-run-plan-preview-rollback',
    label: 'Dry-Run Plan Preview Rollback',
    target: 'dry_run_plan',
    rollbackType: 'preview_only',
    risk: 'low',
    readiness: 'readonly_preview',
    allowedNow: true,
    previewOnly: true,
    reversible: true,
    irreversible: false,
    requiresHumanApproval: false,
    requiresEvidence: false,
    requiresAuditLog: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    requiresStageC: false,
    executesRollback: false,
    modifiesFiles: false,
    modifiesGit: false,
    idempotencyKeyRequired: false,
    preconditions: ['Dry-run plan must be in readonly mode'],
    evidenceRequired: ['dry-run-plan-preview-evidence'],
    rollbackStepsPreview: ['No rollback needed — dry-run plan is static readonly view'],
    failureModes: ['N/A — no dry-run execution to fail'],
    blockedActions: ['execute_rollback', 'restore', 'recover', 'reset'],
    gates: ['readonly_only', 'no_rollback_execution'],
    reason: 'Dry-Run Plan Preview is a static readonly model — no dry-run actions to roll back',
    nextAction: 'Continue using readonly preview. Rollback design not yet implemented.',
  },
  {
    id: 'audit-log-preview-rollback',
    label: 'Audit Log Preview Rollback',
    target: 'audit_log',
    rollbackType: 'preview_only',
    risk: 'low',
    readiness: 'readonly_preview',
    allowedNow: true,
    previewOnly: true,
    reversible: true,
    irreversible: false,
    requiresHumanApproval: false,
    requiresEvidence: false,
    requiresAuditLog: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    requiresStageC: false,
    executesRollback: false,
    modifiesFiles: false,
    modifiesGit: false,
    idempotencyKeyRequired: false,
    preconditions: ['Audit log preview must be in readonly mode'],
    evidenceRequired: ['audit-log-preview-evidence'],
    rollbackStepsPreview: ['No rollback needed — audit log is static readonly view'],
    failureModes: ['N/A — no audit write to fail'],
    blockedActions: ['execute_rollback', 'restore', 'recover', 'reset'],
    gates: ['readonly_only', 'no_rollback_execution', 'no_audit_write'],
    reason: 'Audit Log Preview is a static readonly model — no audit log write to roll back',
    nextAction: 'Continue using readonly preview. Rollback design not yet implemented.',
  },
  {
    id: 'human-approval-preview-rollback',
    label: 'Human Approval Preview Rollback',
    target: 'human_approval',
    rollbackType: 'preview_only',
    risk: 'low',
    readiness: 'readonly_preview',
    allowedNow: true,
    previewOnly: true,
    reversible: true,
    irreversible: false,
    requiresHumanApproval: false,
    requiresEvidence: false,
    requiresAuditLog: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    requiresStageC: false,
    executesRollback: false,
    modifiesFiles: false,
    modifiesGit: false,
    idempotencyKeyRequired: false,
    preconditions: ['Human approval preview must be in readonly mode'],
    evidenceRequired: ['human-approval-request-preview'],
    rollbackStepsPreview: ['No rollback needed — approval workflow is static readonly view'],
    failureModes: ['N/A — no approval queue to roll back'],
    blockedActions: ['execute_rollback', 'restore', 'recover', 'reset'],
    gates: ['readonly_only', 'no_rollback_execution', 'no_approval_queue'],
    reason: 'Human Approval Preview is a static readonly model — no approval queue to roll back',
    nextAction: 'Continue using readonly preview. Rollback design not yet implemented.',
  },
  {
    id: 'governance-state-preview-rollback',
    label: 'Governance State Preview Rollback',
    target: 'governance_state',
    rollbackType: 'preview_only',
    risk: 'low',
    readiness: 'readonly_preview',
    allowedNow: true,
    previewOnly: true,
    reversible: true,
    irreversible: false,
    requiresHumanApproval: false,
    requiresEvidence: false,
    requiresAuditLog: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    requiresStageC: false,
    executesRollback: false,
    modifiesFiles: false,
    modifiesGit: false,
    idempotencyKeyRequired: false,
    preconditions: ['Governance state preview must be in readonly mode'],
    evidenceRequired: ['governance-state-snapshot'],
    rollbackStepsPreview: ['No rollback needed — state machine is static readonly view'],
    failureModes: ['N/A — no state transitions to roll back'],
    blockedActions: ['execute_rollback', 'restore', 'recover', 'reset', 'transition_state'],
    gates: ['readonly_only', 'no_rollback_execution', 'no_state_transition'],
    reason: 'Governance State Preview is a static readonly model — no state transitions to roll back',
    nextAction: 'Continue using readonly preview. Rollback design not yet implemented.',
  },
  {
    id: 'evidence-schema-preview-rollback',
    label: 'Evidence Schema Preview Rollback',
    target: 'evidence_schema',
    rollbackType: 'preview_only',
    risk: 'low',
    readiness: 'readonly_preview',
    allowedNow: true,
    previewOnly: true,
    reversible: true,
    irreversible: false,
    requiresHumanApproval: false,
    requiresEvidence: false,
    requiresAuditLog: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    requiresStageC: false,
    executesRollback: false,
    modifiesFiles: false,
    modifiesGit: false,
    idempotencyKeyRequired: false,
    preconditions: ['Evidence schema preview must be in readonly mode'],
    evidenceRequired: ['registry_snapshot'],
    rollbackStepsPreview: ['No rollback needed — evidence schema is static readonly view'],
    failureModes: ['N/A — no evidence capture to roll back'],
    blockedActions: ['execute_rollback', 'restore', 'recover', 'reset'],
    gates: ['readonly_only', 'no_rollback_execution', 'no_evidence_capture'],
    reason: 'Evidence Schema Preview is a static readonly model — no evidence capture to roll back',
    nextAction: 'Continue using readonly preview. Rollback design not yet implemented.',
  },
  {
    id: 'permission-evaluator-preview-rollback',
    label: 'Permission Evaluator Preview Rollback',
    target: 'permission_evaluator',
    rollbackType: 'preview_only',
    risk: 'low',
    readiness: 'readonly_preview',
    allowedNow: true,
    previewOnly: true,
    reversible: true,
    irreversible: false,
    requiresHumanApproval: false,
    requiresEvidence: false,
    requiresAuditLog: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    requiresStageC: false,
    executesRollback: false,
    modifiesFiles: false,
    modifiesGit: false,
    idempotencyKeyRequired: false,
    preconditions: ['Permission evaluator preview must be in readonly mode'],
    evidenceRequired: ['permission-evaluator-summary'],
    rollbackStepsPreview: ['No rollback needed — permission evaluator is static readonly view'],
    failureModes: ['N/A — no permission enforcement to roll back'],
    blockedActions: ['execute_rollback', 'restore', 'recover', 'reset'],
    gates: ['readonly_only', 'no_rollback_execution'],
    reason: 'Permission Evaluator Preview is a static readonly model — no permission enforcement to roll back',
    nextAction: 'Continue using readonly preview. Rollback design not yet implemented.',
  },
  {
    id: 'connector-center-preview-rollback',
    label: 'Connector Center Preview Rollback',
    target: 'connector_center',
    rollbackType: 'preview_only',
    risk: 'low',
    readiness: 'readonly_preview',
    allowedNow: true,
    previewOnly: true,
    reversible: true,
    irreversible: false,
    requiresHumanApproval: false,
    requiresEvidence: false,
    requiresAuditLog: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    requiresStageC: false,
    executesRollback: false,
    modifiesFiles: false,
    modifiesGit: false,
    idempotencyKeyRequired: false,
    preconditions: ['Connector center preview must be in readonly mode'],
    evidenceRequired: ['connector-center-readiness-snapshot'],
    rollbackStepsPreview: ['No rollback needed — connector readiness is static readonly view'],
    failureModes: ['N/A — no connector connection to roll back'],
    blockedActions: ['execute_rollback', 'restore', 'recover', 'reset', 'connect'],
    gates: ['readonly_only', 'no_rollback_execution', 'no_external_control'],
    reason: 'Connector Center Preview is a static readonly model — no connector actions to roll back',
    nextAction: 'Continue using readonly preview. Rollback design not yet implemented.',
  },
  {
    id: 'manual-recovery-plan-preview',
    label: 'Manual Recovery Plan Preview',
    target: 'runtime_registry',
    rollbackType: 'manual_recovery_plan',
    risk: 'medium',
    readiness: 'design_only',
    allowedNow: true,
    previewOnly: true,
    reversible: false,
    irreversible: false,
    requiresHumanApproval: true,
    requiresEvidence: true,
    requiresAuditLog: true,
    requiresDbWrite: false,
    requiresExternalControl: false,
    requiresStageC: false,
    executesRollback: false,
    modifiesFiles: false,
    modifiesGit: false,
    idempotencyKeyRequired: false,
    preconditions: ['Manual recovery plan must be reviewed by human operator', 'Evidence of current state must be collected', 'Audit log of recovery actions must be planned'],
    evidenceRequired: ['runtime-registry-snapshot', 'audit-log-preview-evidence', 'rollback-audit-trace-preview'],
    rollbackStepsPreview: ['1. Collect current state snapshot', '2. Plan recovery steps manually', '3. Execute recovery with human approval', '4. Verify recovery outcome'],
    failureModes: ['Incomplete state snapshot', 'Missing audit trail', 'Human operator unavailable'],
    blockedActions: ['execute_rollback', 'restore', 'recover', 'reset', 'overwrite'],
    gates: ['readonly_only', 'human_approval_required', 'no_rollback_execution'],
    reason: 'Manual recovery plan is design-only — no automatic rollback execution',
    nextAction: 'Design manual recovery procedures. Do not implement rollback executor.',
  },
  {
    id: 'idempotency-key-check-preview',
    label: 'Idempotency Key Check Preview',
    target: 'runtime_registry',
    rollbackType: 'idempotency_check',
    risk: 'low',
    readiness: 'readonly_preview',
    allowedNow: true,
    previewOnly: true,
    reversible: true,
    irreversible: false,
    requiresHumanApproval: false,
    requiresEvidence: false,
    requiresAuditLog: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    requiresStageC: false,
    executesRollback: false,
    modifiesFiles: false,
    modifiesGit: false,
    idempotencyKeyRequired: true,
    preconditions: ['Action must have idempotency key', 'Idempotency key must be unique per action'],
    evidenceRequired: ['runtime-registry-snapshot'],
    rollbackStepsPreview: ['1. Verify idempotency key presence', '2. Check key uniqueness', '3. Report idempotency status'],
    failureModes: ['Missing idempotency key', 'Duplicate key detected', 'Key format invalid'],
    blockedActions: ['execute_action', 'retry', 'force_execute'],
    gates: ['readonly_only', 'idempotency_check_only'],
    reason: 'Idempotency key check is preview-only — no action execution',
    nextAction: 'Ensure all runtime actions have unique idempotency keys before execution.',
  },
  {
    id: 'rollback-evidence-requirement-preview',
    label: 'Rollback Evidence Requirement Preview',
    target: 'evidence_schema',
    rollbackType: 'risk_assessment',
    risk: 'medium',
    readiness: 'readonly_preview',
    allowedNow: true,
    previewOnly: true,
    reversible: true,
    irreversible: false,
    requiresHumanApproval: false,
    requiresEvidence: true,
    requiresAuditLog: false,
    requiresDbWrite: false,
    requiresExternalControl: false,
    requiresStageC: false,
    executesRollback: false,
    modifiesFiles: false,
    modifiesGit: false,
    idempotencyKeyRequired: false,
    preconditions: ['Evidence schema must be defined for rollback target'],
    evidenceRequired: ['registry_snapshot', 'validator_summary'],
    rollbackStepsPreview: ['1. Identify rollback target', '2. Collect required evidence items', '3. Verify evidence readiness'],
    failureModes: ['Missing evidence schema', 'Evidence not collectible', 'Evidence contains forbidden data'],
    blockedActions: ['execute_rollback', 'capture_evidence', 'store_evidence'],
    gates: ['readonly_only', 'no_evidence_capture'],
    reason: 'Rollback evidence requirement is preview-only — no evidence capture',
    nextAction: 'Define evidence schema for each rollback target before rollback implementation.',
  },
  {
    id: 'rollback-audit-trace-preview',
    label: 'Rollback Audit Trace Preview',
    target: 'audit_log',
    rollbackType: 'risk_assessment',
    risk: 'medium',
    readiness: 'readonly_preview',
    allowedNow: true,
    previewOnly: true,
    reversible: true,
    irreversible: false,
    requiresHumanApproval: false,
    requiresEvidence: true,
    requiresAuditLog: true,
    requiresDbWrite: false,
    requiresExternalControl: false,
    requiresStageC: false,
    executesRollback: false,
    modifiesFiles: false,
    modifiesGit: false,
    idempotencyKeyRequired: false,
    preconditions: ['Audit log must be available for rollback target', 'Audit trail must be complete'],
    evidenceRequired: ['audit-log-preview-evidence', 'audit-validator-summary'],
    rollbackStepsPreview: ['1. Query audit log for target actions', '2. Build rollback trace', '3. Verify audit completeness'],
    failureModes: ['Incomplete audit trail', 'Missing audit entries', 'Audit log not available'],
    blockedActions: ['execute_rollback', 'write_audit', 'modify_audit'],
    gates: ['readonly_only', 'no_audit_write'],
    reason: 'Rollback audit trace is preview-only — no audit write or modification',
    nextAction: 'Ensure complete audit trail before any rollback implementation.',
  },
  {
    id: 'git-commit-push-rollback-plan',
    label: 'Git Commit/Push Rollback Plan',
    target: 'git',
    rollbackType: 'manual_recovery_plan',
    risk: 'high',
    readiness: 'manual_review_required',
    allowedNow: true,
    previewOnly: true,
    reversible: true,
    irreversible: false,
    requiresHumanApproval: true,
    requiresEvidence: true,
    requiresAuditLog: true,
    requiresDbWrite: false,
    requiresExternalControl: false,
    requiresStageC: false,
    executesRollback: false,
    modifiesFiles: false,
    modifiesGit: false,
    idempotencyKeyRequired: false,
    preconditions: ['Git commit/push rollback must be reviewed by human operator', 'Clean working tree required'],
    evidenceRequired: ['git-commit-reference', 'report-path-reference'],
    rollbackStepsPreview: ['1. Review recent commits', '2. Plan revert with human approval', '3. Execute git revert (manual)', '4. Verify revert outcome'],
    failureModes: ['Conflicting changes after target commit', 'Force push required', 'Shared branch conflict'],
    blockedActions: ['git_reset', 'git_revert', 'git_tag', 'git_release', 'force_push', 'overwrite'],
    gates: ['readonly_only', 'human_approval_required', 'no_git_mutation'],
    reason: 'Git rollback plan is design-only — no git mutation executed',
    nextAction: 'Keep git rollback as manual procedure. Do not automate git reset/revert.',
  },
  {
    id: 'git-tag-release-rollback-blocked',
    label: 'Git Tag/Release Rollback — Blocked',
    target: 'git',
    rollbackType: 'blocked_irreversible',
    risk: 'critical',
    readiness: 'blocked',
    allowedNow: false,
    previewOnly: false,
    reversible: false,
    irreversible: true,
    requiresHumanApproval: true,
    requiresEvidence: true,
    requiresAuditLog: true,
    requiresDbWrite: false,
    requiresExternalControl: false,
    requiresStageC: false,
    executesRollback: false,
    modifiesFiles: false,
    modifiesGit: true,
    idempotencyKeyRequired: false,
    preconditions: ['Tag/release rollback is irreversible', 'Requires human approval', 'Requires evidence of current release'],
    evidenceRequired: ['git-commit-reference', 'validation-output-reference'],
    rollbackStepsPreview: ['BLOCKED — git tag/release rollback is not implemented', 'Manual revert required if absolutely necessary'],
    failureModes: ['Irreversible action', 'Downstream consumers affected', 'Release history inconsistency'],
    blockedActions: ['execute_rollback', 'git_reset', 'git_revert', 'git_tag', 'git_release', 'force_push', 'overwrite'],
    gates: ['readonly_only', 'human_approval_required', 'no_git_mutation', 'irreversible_action'],
    reason: 'Git tag/release rollback is blocked — this action is irreversible in the context of distributed git',
    nextAction: 'Do not implement git tag/release rollback. Keep as manual emergency procedure.',
  },
  {
    id: 'db-write-rollback-blocked',
    label: 'Database Write Rollback — Blocked',
    target: 'database',
    rollbackType: 'blocked_irreversible',
    risk: 'critical',
    readiness: 'blocked',
    allowedNow: false,
    previewOnly: false,
    reversible: false,
    irreversible: true,
    requiresHumanApproval: true,
    requiresEvidence: true,
    requiresAuditLog: true,
    requiresDbWrite: false,
    requiresExternalControl: false,
    requiresStageC: false,
    executesRollback: false,
    modifiesFiles: false,
    modifiesGit: false,
    idempotencyKeyRequired: false,
    preconditions: ['DB write rollback is blocked — no DB writes are currently performed'],
    evidenceRequired: ['audit-log-preview-evidence', 'validation-output-reference'],
    rollbackStepsPreview: ['BLOCKED — DB write rollback is not implemented', 'No DB writes exist to roll back'],
    failureModes: ['DB writes would require transaction rollback', 'No DB transaction implemented'],
    blockedActions: ['execute_rollback', 'write_database', 'modify_schema', 'overwrite'],
    gates: ['readonly_only', 'no_db_write', 'irreversible_action'],
    reason: 'DB write rollback is blocked — no DB writes are currently implemented across the entire preview system',
    nextAction: 'Keep DB writes permanently blocked. Do not implement DB write rollback.',
  },
  {
    id: 'external-tool-control-rollback-blocked',
    label: 'External Tool Control Rollback — Blocked',
    target: 'external_tool',
    rollbackType: 'blocked_irreversible',
    risk: 'critical',
    readiness: 'blocked',
    allowedNow: false,
    previewOnly: false,
    reversible: false,
    irreversible: true,
    requiresHumanApproval: true,
    requiresEvidence: true,
    requiresAuditLog: true,
    requiresDbWrite: false,
    requiresExternalControl: false,
    requiresStageC: false,
    executesRollback: false,
    modifiesFiles: false,
    modifiesGit: false,
    idempotencyKeyRequired: false,
    preconditions: ['External tool control rollback is blocked — no external tools are currently controlled'],
    evidenceRequired: ['connector-center-readiness-snapshot'],
    rollbackStepsPreview: ['BLOCKED — external tool control rollback is not implemented', 'No external tool actions exist to roll back'],
    failureModes: ['External tools may have irreversible state changes', 'No control over external system rollback'],
    blockedActions: ['execute_rollback', 'control_external_tools', 'connect', 'overwrite'],
    gates: ['readonly_only', 'no_external_control', 'irreversible_action'],
    reason: 'External tool control rollback is blocked — no external tool control is currently implemented',
    nextAction: 'Keep external tool control permanently blocked. Do not implement external rollback.',
  },
  {
    id: 'stage-c-transition-rollback-blocked',
    label: 'Stage C Transition Rollback — Blocked',
    target: 'stage_c',
    rollbackType: 'future_stage_c',
    risk: 'critical',
    readiness: 'blocked',
    allowedNow: false,
    previewOnly: false,
    reversible: false,
    irreversible: true,
    requiresHumanApproval: true,
    requiresEvidence: true,
    requiresAuditLog: true,
    requiresDbWrite: true,
    requiresExternalControl: true,
    requiresStageC: true,
    executesRollback: false,
    modifiesFiles: true,
    modifiesGit: true,
    idempotencyKeyRequired: true,
    preconditions: ['Stage C is permanently disabled', 'Stage C transition rollback cannot be designed until Stage C is implemented'],
    evidenceRequired: ['governance-state-snapshot', 'stage-gate-state-preview'],
    rollbackStepsPreview: ['BLOCKED — Stage C is permanently disabled', 'Stage C transition rollback is blocked'],
    failureModes: ['Stage C not implemented', 'Stage C transition rollback cannot be designed'],
    blockedActions: ['execute_rollback', 'enable_stage_c', 'transition_stage', 'write_database', 'control_external_tools', 'modify_files', 'modify_git'],
    gates: ['readonly_only', 'stage_c_disabled', 'irreversible_action', 'no_db_write', 'no_external_control'],
    reason: 'Stage C transition rollback is blocked — Stage C is permanently disabled across all preview systems',
    nextAction: 'Keep Stage C permanently disabled. Do not design Stage C rollback until Stage C is implemented.',
  },
  {
    id: 'candidate-processing-rollback-blocked',
    label: 'Candidate Processing Rollback — Blocked',
    target: 'human_approval',
    rollbackType: 'blocked_irreversible',
    risk: 'high',
    readiness: 'blocked',
    allowedNow: false,
    previewOnly: false,
    reversible: false,
    irreversible: true,
    requiresHumanApproval: true,
    requiresEvidence: true,
    requiresAuditLog: true,
    requiresDbWrite: false,
    requiresExternalControl: false,
    requiresStageC: false,
    executesRollback: false,
    modifiesFiles: false,
    modifiesGit: false,
    idempotencyKeyRequired: false,
    preconditions: ['Candidate processing rollback is blocked — no candidate processing is currently implemented'],
    evidenceRequired: ['human-approval-request-preview', 'human-approval-validator-summary'],
    rollbackStepsPreview: ['BLOCKED — candidate processing rollback is not implemented', 'No candidates exist to roll back'],
    failureModes: ['Candidate processing would require approval queue', 'No approval queue implemented'],
    blockedActions: ['execute_rollback', 'process_candidate', 'create_approval_queue', 'approve', 'reject'],
    gates: ['readonly_only', 'no_approval_queue', 'no_candidate_processing'],
    reason: 'Candidate processing rollback is blocked — no candidate processing or approval queue implemented',
    nextAction: 'Keep candidate processing blocked. Do not implement candidate rollback.',
  },
  {
    id: 'local-file-overwrite-rollback-blocked',
    label: 'Local File Overwrite Rollback — Blocked',
    target: 'local_file',
    rollbackType: 'blocked_irreversible',
    risk: 'critical',
    readiness: 'blocked',
    allowedNow: false,
    previewOnly: false,
    reversible: false,
    irreversible: true,
    requiresHumanApproval: true,
    requiresEvidence: true,
    requiresAuditLog: true,
    requiresDbWrite: false,
    requiresExternalControl: false,
    requiresStageC: false,
    executesRollback: false,
    modifiesFiles: true,
    modifiesGit: false,
    idempotencyKeyRequired: false,
    preconditions: ['Local file overwrite rollback is blocked — no file overwrites are currently performed'],
    evidenceRequired: ['report-path-reference', 'screenshot-reference'],
    rollbackStepsPreview: ['BLOCKED — local file overwrite rollback is not implemented', 'No file operations exist to roll back'],
    failureModes: ['File overwrite is irreversible without backup', 'No backup system implemented'],
    blockedActions: ['execute_rollback', 'overwrite_file', 'delete_file', 'move_file', 'restore_file'],
    gates: ['readonly_only', 'no_file_modification', 'irreversible_action'],
    reason: 'Local file overwrite rollback is blocked — no file modification is currently performed',
    nextAction: 'Keep file modification blocked. Do not implement file rollback.',
  },
  {
    id: 'secret-capture-rollback-blocked',
    label: 'Secret Capture Rollback — Blocked',
    target: 'external_tool',
    rollbackType: 'blocked_irreversible',
    risk: 'critical',
    readiness: 'blocked',
    allowedNow: false,
    previewOnly: false,
    reversible: false,
    irreversible: true,
    requiresHumanApproval: true,
    requiresEvidence: true,
    requiresAuditLog: true,
    requiresDbWrite: false,
    requiresExternalControl: false,
    requiresStageC: false,
    executesRollback: false,
    modifiesFiles: false,
    modifiesGit: false,
    idempotencyKeyRequired: false,
    preconditions: ['Secret capture rollback is blocked — no secret capture is currently implemented'],
    evidenceRequired: ['token-secret-material-forbidden', 'api-key-material-forbidden', 'raw-password-material-forbidden'],
    rollbackStepsPreview: ['BLOCKED — secret capture rollback is not implemented', 'Secret capture is forbidden across all systems'],
    failureModes: ['Secret capture is forbidden', 'No rollback can undo leaked secrets'],
    blockedActions: ['execute_rollback', 'capture_secret', 'store_secret', 'save_token', 'save_api_key', 'save_password'],
    gates: ['readonly_only', 'no_secret_storage', 'no_evidence_capture', 'irreversible_action'],
    reason: 'Secret capture rollback is blocked — secret capture is forbidden across all preview systems',
    nextAction: 'Keep secret capture permanently blocked. Do not implement secret rollback.',
  },
  {
    id: 'runtime-execution-rollback-blocked',
    label: 'Runtime Execution Rollback — Blocked',
    target: 'runtime_registry',
    rollbackType: 'blocked_irreversible',
    risk: 'critical',
    readiness: 'blocked',
    allowedNow: false,
    previewOnly: false,
    reversible: false,
    irreversible: true,
    requiresHumanApproval: true,
    requiresEvidence: true,
    requiresAuditLog: true,
    requiresDbWrite: true,
    requiresExternalControl: true,
    requiresStageC: true,
    executesRollback: false,
    modifiesFiles: true,
    modifiesGit: false,
    idempotencyKeyRequired: true,
    preconditions: ['Runtime execution rollback is blocked — no runtime execution is currently implemented'],
    evidenceRequired: ['runtime-registry-snapshot', 'runtime-validator-summary'],
    rollbackStepsPreview: ['BLOCKED — runtime execution rollback is not implemented', 'No runtime actions exist to roll back'],
    failureModes: ['Runtime execution not implemented', 'Runtime rollback requires runtime implementation first'],
    blockedActions: ['execute_rollback', 'execute_action', 'control_external_tools', 'write_database', 'modify_files'],
    gates: ['readonly_only', 'no_runtime_implementation', 'stage_c_disabled', 'irreversible_action'],
    reason: 'Runtime execution rollback is blocked — no runtime execution is currently implemented',
    nextAction: 'Keep runtime execution blocked. Do not implement runtime rollback until runtime is implemented.',
  },
  {
    id: 'irreversible-action-blocked',
    label: 'Irreversible Action — Blocked',
    target: 'external_tool',
    rollbackType: 'blocked_irreversible',
    risk: 'critical',
    readiness: 'blocked',
    allowedNow: false,
    previewOnly: false,
    reversible: false,
    irreversible: true,
    requiresHumanApproval: true,
    requiresEvidence: true,
    requiresAuditLog: true,
    requiresDbWrite: false,
    requiresExternalControl: true,
    requiresStageC: true,
    executesRollback: true,
    modifiesFiles: true,
    modifiesGit: true,
    idempotencyKeyRequired: true,
    preconditions: ['Irreversible actions are blocked by design', 'No irreversible action should be automated'],
    evidenceRequired: ['validation-output-reference', 'governance-state-snapshot'],
    rollbackStepsPreview: ['BLOCKED — irreversible action rollback is not implemented', 'Irreversible actions must be prevented, not rolled back'],
    failureModes: ['Irreversible action cannot be undone', 'No rollback possible by definition'],
    blockedActions: ['execute_rollback', 'execute_action', 'force_execute', 'overwrite', 'delete', 'release'],
    gates: ['readonly_only', 'irreversible_action', 'stage_c_disabled', 'no_external_control', 'no_db_write'],
    reason: 'Irreversible action rollback is blocked — irreversible actions must be prevented, not recovered',
    nextAction: 'Identify and block all irreversible actions at design stage. Do not implement irreversible rollback.',
  },
];

export function getRollbackRegistryItems(): RollbackRegistryItem[] {
  return ROLLBACK_REGISTRY;
}

export function getRollbackRegistrySummary() {
  const items = ROLLBACK_REGISTRY;
  return {
    total: items.length,
    allowedNow: items.filter(i => i.allowedNow).length,
    blocked: items.filter(i => !i.allowedNow).length,
    highOrCritical: items.filter(i => i.risk === 'high' || i.risk === 'critical').length,
    irreversible: items.filter(i => i.irreversible).length,
    executesRollback: items.filter(i => i.executesRollback).length,
    requiresHumanApproval: items.filter(i => i.requiresHumanApproval).length,
    requiresEvidence: items.filter(i => i.requiresEvidence).length,
    requiresAuditLog: items.filter(i => i.requiresAuditLog).length,
    requiresDbWrite: items.filter(i => i.requiresDbWrite).length,
    requiresExternalControl: items.filter(i => i.requiresExternalControl).length,
    requiresStageC: items.filter(i => i.requiresStageC).length,
    modifiesFiles: items.filter(i => i.modifiesFiles).length,
    modifiesGit: items.filter(i => i.modifiesGit).length,
  };
}

export function getRollbackItemsByTarget(target: RollbackTarget): RollbackRegistryItem[] {
  return ROLLBACK_REGISTRY.filter(i => i.target === target);
}

export function getRollbackItemsByType(type: RollbackType): RollbackRegistryItem[] {
  return ROLLBACK_REGISTRY.filter(i => i.rollbackType === type);
}

export function getRollbackItemsByRisk(risk: RollbackRisk): RollbackRegistryItem[] {
  return ROLLBACK_REGISTRY.filter(i => i.risk === risk);
}

export function getRollbackBlockedItems(): RollbackRegistryItem[] {
  return ROLLBACK_REGISTRY.filter(i => !i.allowedNow);
}

export function getRollbackExecutableItems(): RollbackRegistryItem[] {
  return ROLLBACK_REGISTRY.filter(i => i.executesRollback);
}

export function getIrreversibleRollbackItems(): RollbackRegistryItem[] {
  return ROLLBACK_REGISTRY.filter(i => i.irreversible);
}
