// Runtime Dry-run Contract Registry — static readonly contract model for dry-run operations
// Does not execute dry-runs, call APIs, modify state, write to databases, or control external tools.

export type DryRunContractKind =
  | 'readonly_preview'
  | 'request_schema'
  | 'response_schema'
  | 'gate_check'
  | 'evidence_requirement'
  | 'audit_requirement'
  | 'rollback_requirement'
  | 'blocked_execution';

export type DryRunContractRisk = 'low' | 'medium' | 'high' | 'critical';

export interface RuntimeDryRunContractItem {
  id: string;
  label: string;
  kind: DryRunContractKind;
  risk: DryRunContractRisk;
  allowedNow: boolean;
  contractOnly: boolean;
  executesDryRun: boolean;
  callsExternalTool: boolean;
  writesDb: boolean;
  requiresHumanApproval: boolean;
  requiresStageC: boolean;
  requiresEvidence: boolean;
  requiresAuditLog: boolean;
  requiresRollbackPlan: boolean;
  requestFields: string[];
  responseFields: string[];
  forbiddenFields: string[];
  gates: string[];
  blockedActions: string[];
  linkedDocs: string[];
  reason: string;
  nextAction: string;
}

export const RUNTIME_DRY_RUN_CONTRACT_ITEMS: RuntimeDryRunContractItem[] = [
  {
    id: 'dry-run-preview-contract',
    label: 'Dry-run Preview Contract Overview',
    kind: 'readonly_preview',
    risk: 'low',
    allowedNow: true,
    contractOnly: true,
    executesDryRun: false,
    callsExternalTool: false,
    writesDb: false,
    requiresHumanApproval: false,
    requiresStageC: false,
    requiresEvidence: false,
    requiresAuditLog: false,
    requiresRollbackPlan: false,
    requestFields: [],
    responseFields: ['overview'],
    forbiddenFields: [],
    gates: ['readonly_only', 'no_backend_endpoint', 'no_api_call', 'no_db_write', 'no_external_control', 'stage_c_disabled'],
    blockedActions: ['execute_dry_run', 'call_external_api', 'write_db', 'enable_stage_c'],
    linkedDocs: ['AIP_RUNTIME_API_CONTRACT_FREEZE.md', 'AIP_RUNTIME_API_MOCK_EXAMPLES.md'],
    reason: 'Dry-run Preview Contract is a readonly overview of the dry-run contract model. No dry-run execution, no API call, no DB write, no external control, no Stage C.',
    nextAction: 'Keep contract_only. Do not implement dry-run execution without Stage C.',
  },
  {
    id: 'dry-run-request-schema',
    label: 'Dry-run Request Schema Contract',
    kind: 'request_schema',
    risk: 'low',
    allowedNow: true,
    contractOnly: true,
    executesDryRun: false,
    callsExternalTool: false,
    writesDb: false,
    requiresHumanApproval: false,
    requiresStageC: false,
    requiresEvidence: false,
    requiresAuditLog: false,
    requiresRollbackPlan: false,
    requestFields: ['actionId', 'targetType', 'parameters', 'idempotencyKey', 'metadata'],
    responseFields: ['schema', 'required', 'optional', 'examples'],
    forbiddenFields: ['token', 'apiKey', 'password', 'secret', 'privateKey', 'credential'],
    gates: ['readonly_only', 'no_backend_endpoint', 'no_api_call', 'no_db_write', 'no_external_control', 'stage_c_disabled'],
    blockedActions: ['execute_dry_run', 'validate_schema', 'process_request'],
    linkedDocs: ['AIP_RUNTIME_API_SCHEMA_CATALOG.md'],
    reason: 'Dry-run Request Schema defines the contract for future dry-run requests. No request processing, no validation execution, no Stage C.',
    nextAction: 'Keep contract_only. Do not implement request validation without Stage C.',
  },
  {
    id: 'dry-run-response-schema',
    label: 'Dry-run Response Schema Contract',
    kind: 'response_schema',
    risk: 'low',
    allowedNow: true,
    contractOnly: true,
    executesDryRun: false,
    callsExternalTool: false,
    writesDb: false,
    requiresHumanApproval: false,
    requiresStageC: false,
    requiresEvidence: false,
    requiresAuditLog: false,
    requiresRollbackPlan: false,
    requestFields: [],
    responseFields: ['status', 'summary', 'predictedOutcome', 'riskAssessment', 'gateResults', 'blockers', 'estimatedCost', 'estimatedDuration', 'timestamp'],
    forbiddenFields: [],
    gates: ['readonly_only', 'no_backend_endpoint', 'no_api_call', 'no_db_write', 'no_external_control', 'stage_c_disabled'],
    blockedActions: ['execute_dry_run', 'generate_response', 'store_result'],
    linkedDocs: ['AIP_RUNTIME_API_SCHEMA_CATALOG.md'],
    reason: 'Dry-run Response Schema defines the contract for future dry-run results. No response generation, no result storage, no Stage C.',
    nextAction: 'Keep contract_only. Do not implement response generation without Stage C.',
  },
  {
    id: 'dry-run-gate-check-contract',
    label: 'Dry-run Gate Check Contract',
    kind: 'gate_check',
    risk: 'medium',
    allowedNow: true,
    contractOnly: true,
    executesDryRun: false,
    callsExternalTool: false,
    writesDb: false,
    requiresHumanApproval: false,
    requiresStageC: false,
    requiresEvidence: false,
    requiresAuditLog: false,
    requiresRollbackPlan: false,
    requestFields: ['actionId', 'targetType', 'parameters'],
    responseFields: ['gateId', 'status', 'blockingReason', 'resolvedBy'],
    forbiddenFields: ['token', 'apiKey', 'password', 'secret', 'privateKey', 'credential'],
    gates: ['readonly_only', 'no_backend_endpoint', 'no_api_call', 'no_db_write', 'no_external_control', 'stage_c_disabled'],
    blockedActions: ['execute_gate_check', 'override_gate', 'skip_gate', 'enable_stage_c'],
    linkedDocs: ['AIP_RUNTIME_API_GATE_AND_PERMISSION_MODEL.md'],
    reason: 'Dry-run Gate Check defines 11 gates for dry-run operations. All gates are design-only. No gate execution, no override, no Stage C.',
    nextAction: 'Keep contract_only. Do not implement gate execution without Stage C.',
  },
  {
    id: 'dry-run-evidence-requirement',
    label: 'Dry-run Evidence Requirement Contract',
    kind: 'evidence_requirement',
    risk: 'medium',
    allowedNow: true,
    contractOnly: true,
    executesDryRun: false,
    callsExternalTool: false,
    writesDb: false,
    requiresHumanApproval: false,
    requiresStageC: false,
    requiresEvidence: true,
    requiresAuditLog: false,
    requiresRollbackPlan: false,
    requestFields: ['actionId', 'evidenceType', 'source'],
    responseFields: ['requiredEvidence', 'collectedEvidence', 'missingEvidence', 'status'],
    forbiddenFields: ['token', 'apiKey', 'password', 'secret', 'privateKey', 'credential'],
    gates: ['readonly_only', 'no_backend_endpoint', 'no_api_call', 'no_db_write', 'no_external_control', 'stage_c_disabled', 'no_evidence_capture'],
    blockedActions: ['capture_evidence', 'store_evidence', 'validate_evidence', 'access_secret', 'enable_stage_c'],
    linkedDocs: ['AIP_RUNTIME_EVIDENCE_SCHEMA_SPEC.md'],
    reason: 'Dry-run Evidence Requirement defines evidence collection requirements for dry-run operations. No evidence capture, no secret access, no Stage C.',
    nextAction: 'Keep contract_only. Do not implement evidence capture without Stage C.',
  },
  {
    id: 'dry-run-audit-requirement',
    label: 'Dry-run Audit Requirement Contract',
    kind: 'audit_requirement',
    risk: 'medium',
    allowedNow: true,
    contractOnly: true,
    executesDryRun: false,
    callsExternalTool: false,
    writesDb: false,
    requiresHumanApproval: false,
    requiresStageC: false,
    requiresEvidence: false,
    requiresAuditLog: true,
    requiresRollbackPlan: false,
    requestFields: ['actionId', 'eventType', 'source'],
    responseFields: ['requiredAuditEvents', 'retentionClass', 'redactionRequired'],
    forbiddenFields: ['token', 'apiKey', 'password', 'secret', 'privateKey', 'credential'],
    gates: ['readonly_only', 'no_backend_endpoint', 'no_api_call', 'no_db_write', 'no_external_control', 'stage_c_disabled', 'no_audit_write'],
    blockedActions: ['write_audit_log', 'create_audit_store', 'retain_audit_event', 'enable_stage_c'],
    linkedDocs: ['AIP_RUNTIME_AUDIT_AND_ROLLBACK_PLAN.md'],
    reason: 'Dry-run Audit Requirement defines audit logging requirements for dry-run operations. No audit write, no audit store, no Stage C.',
    nextAction: 'Keep contract_only. Do not implement audit logging without Stage C.',
  },
  {
    id: 'dry-run-rollback-requirement',
    label: 'Dry-run Rollback Requirement Contract',
    kind: 'rollback_requirement',
    risk: 'medium',
    allowedNow: true,
    contractOnly: true,
    executesDryRun: false,
    callsExternalTool: false,
    writesDb: false,
    requiresHumanApproval: false,
    requiresStageC: false,
    requiresEvidence: false,
    requiresAuditLog: false,
    requiresRollbackPlan: true,
    requestFields: ['actionId', 'rollbackStrategy'],
    responseFields: ['requiredRollbackSteps', 'idempotencyCheck', 'restorePlan'],
    forbiddenFields: ['token', 'apiKey', 'password', 'secret', 'privateKey', 'credential'],
    gates: ['readonly_only', 'no_backend_endpoint', 'no_api_call', 'no_db_write', 'no_external_control', 'stage_c_disabled', 'no_rollback_execution'],
    blockedActions: ['execute_rollback', 'restore_file', 'git_mutation', 'enable_stage_c'],
    linkedDocs: ['AIP_RUNTIME_ROLLBACK_IDEMPOTENCY_SPEC.md'],
    reason: 'Dry-run Rollback Requirement defines rollback plan requirements. No rollback execution, no file restore, no git mutation, no Stage C.',
    nextAction: 'Keep contract_only. Do not implement rollback without Stage C.',
  },
  {
    id: 'dry-run-human-approval-requirement',
    label: 'Dry-run Human Approval Requirement Contract',
    kind: 'gate_check',
    risk: 'high',
    allowedNow: true,
    contractOnly: true,
    executesDryRun: false,
    callsExternalTool: false,
    writesDb: false,
    requiresHumanApproval: true,
    requiresStageC: false,
    requiresEvidence: false,
    requiresAuditLog: false,
    requiresRollbackPlan: false,
    requestFields: ['actionId', 'requestor', 'justification'],
    responseFields: ['approvalRequired', 'approvalType', 'approvalQueue', 'status'],
    forbiddenFields: ['token', 'apiKey', 'password', 'secret', 'privateKey', 'credential'],
    gates: ['readonly_only', 'no_backend_endpoint', 'no_api_call', 'no_db_write', 'no_external_control', 'stage_c_disabled', 'human_approval_required'],
    blockedActions: ['create_approval_queue', 'process_candidate', 'approve', 'reject', 'archive', 'enable_stage_c'],
    linkedDocs: ['AIP_HUMAN_APPROVAL_WORKFLOW_SPEC.md'],
    reason: 'Dry-run Human Approval Requirement defines approval requirements. No approval queue creation, no candidate processing, no approve/reject, no Stage C.',
    nextAction: 'Keep contract_only. Do not implement approval queue without Stage C.',
  },
  {
    id: 'dry-run-stage-c-gate',
    label: 'Dry-run Stage C Gate',
    kind: 'gate_check',
    risk: 'critical',
    allowedNow: true,
    contractOnly: true,
    executesDryRun: false,
    callsExternalTool: false,
    writesDb: false,
    requiresHumanApproval: false,
    requiresStageC: true,
    requiresEvidence: false,
    requiresAuditLog: false,
    requiresRollbackPlan: false,
    requestFields: [],
    responseFields: ['stageCRequired', 'stageCStatus', 'blockingReason'],
    forbiddenFields: [],
    gates: ['readonly_only', 'no_backend_endpoint', 'no_api_call', 'no_db_write', 'no_external_control', 'stage_c_disabled', 'stage_c_required'],
    blockedActions: ['enable_stage_c', 'execute_dry_run', 'override_stage_c', 'bypass_gate'],
    linkedDocs: ['AIP_STAGE_C_FINAL_GATE_POLICY.md'],
    reason: 'Dry-run Stage C Gate documents that all dry-run execution requires Stage C. Stage C is permanently disabled. No dry-run execution, no Stage C override.',
    nextAction: 'Keep contract_only. Do not enable Stage C. Do not bypass Stage C gate.',
  },
  {
    id: 'dry-run-db-write-blocked',
    label: 'Dry-run DB Write Blocked',
    kind: 'blocked_execution',
    risk: 'critical',
    allowedNow: true,
    contractOnly: true,
    executesDryRun: false,
    callsExternalTool: false,
    writesDb: true,
    requiresHumanApproval: false,
    requiresStageC: false,
    requiresEvidence: false,
    requiresAuditLog: false,
    requiresRollbackPlan: false,
    requestFields: [],
    responseFields: [],
    forbiddenFields: [],
    gates: ['readonly_only', 'no_backend_endpoint', 'no_api_call', 'no_db_write', 'no_external_control', 'stage_c_disabled'],
    blockedActions: ['write_db', 'execute_dry_run_with_db', 'store_dry_run_result', 'enable_stage_c'],
    linkedDocs: ['AIP_STAGE_C_FINAL_GATE_POLICY.md', 'AIP_PERMISSION_MATRIX.md'],
    reason: 'Dry-run DB write is permanently blocked. No dry-run execution may write to database. DB write requires Stage C which is permanently disabled.',
    nextAction: 'Keep blocked. Do not allow DB write in dry-run mode.',
  },
  {
    id: 'dry-run-external-control-blocked',
    label: 'Dry-run External Control Blocked',
    kind: 'blocked_execution',
    risk: 'critical',
    allowedNow: true,
    contractOnly: true,
    executesDryRun: false,
    callsExternalTool: true,
    writesDb: false,
    requiresHumanApproval: false,
    requiresStageC: false,
    requiresEvidence: false,
    requiresAuditLog: false,
    requiresRollbackPlan: false,
    requestFields: [],
    responseFields: [],
    forbiddenFields: [],
    gates: ['readonly_only', 'no_backend_endpoint', 'no_api_call', 'no_db_write', 'no_external_control', 'stage_c_disabled'],
    blockedActions: ['control_external_tool', 'call_external_api', 'execute_dry_run_with_external', 'enable_stage_c'],
    linkedDocs: ['AIP_TOOL_CONTROL_BOUNDARY_PLAN.md', 'AIP_CONNECTOR_ACTION_TAXONOMY.md'],
    reason: 'Dry-run external control is permanently blocked. No dry-run execution may control external tools. External control requires Stage C.',
    nextAction: 'Keep blocked. Do not allow external control in dry-run mode.',
  },
  {
    id: 'dry-run-execution-blocked',
    label: 'Dry-run Execution Blocked',
    kind: 'blocked_execution',
    risk: 'critical',
    allowedNow: true,
    contractOnly: true,
    executesDryRun: true,
    callsExternalTool: false,
    writesDb: false,
    requiresHumanApproval: false,
    requiresStageC: false,
    requiresEvidence: false,
    requiresAuditLog: false,
    requiresRollbackPlan: false,
    requestFields: [],
    responseFields: [],
    forbiddenFields: [],
    gates: ['readonly_only', 'no_backend_endpoint', 'no_api_call', 'no_db_write', 'no_external_control', 'stage_c_disabled'],
    blockedActions: ['execute_dry_run', 'run_dry_run', 'execute_any_action', 'enable_stage_c'],
    linkedDocs: ['AIP_RUNTIME_API_CONTRACT_FREEZE.md'],
    reason: 'Dry-run execution is permanently blocked. No dry-run may be executed. All dry-run operations are contract-only. Stage C is permanently disabled.',
    nextAction: 'Keep blocked. Do not execute dry-run without Stage C.',
  },
  {
    id: 'dry-run-secret-field-blocked',
    label: 'Dry-run Secret Field Blocked',
    kind: 'blocked_execution',
    risk: 'critical',
    allowedNow: true,
    contractOnly: true,
    executesDryRun: false,
    callsExternalTool: false,
    writesDb: false,
    requiresHumanApproval: false,
    requiresStageC: false,
    requiresEvidence: false,
    requiresAuditLog: false,
    requiresRollbackPlan: false,
    requestFields: [],
    responseFields: [],
    forbiddenFields: ['token', 'apiKey', 'password', 'secret', 'privateKey', 'credential'],
    gates: ['readonly_only', 'no_backend_endpoint', 'no_api_call', 'no_db_write', 'no_external_control', 'stage_c_disabled'],
    blockedActions: ['capture_secret', 'input_token', 'store_password', 'access_credential', 'enable_stage_c'],
    linkedDocs: ['AIP_EVIDENCE_SCHEMA_PREVIEW.md'],
    reason: 'Dry-run secret fields are permanently blocked. No dry-run request/response may contain token, API key, password, secret, private key, or credential fields.',
    nextAction: 'Keep blocked. Do not accept secret fields in dry-run mode.',
  },
  {
    id: 'dry-run-candidate-processing-blocked',
    label: 'Dry-run Candidate Processing Blocked',
    kind: 'blocked_execution',
    risk: 'critical',
    allowedNow: true,
    contractOnly: true,
    executesDryRun: false,
    callsExternalTool: false,
    writesDb: true,
    requiresHumanApproval: false,
    requiresStageC: true,
    requiresEvidence: false,
    requiresAuditLog: false,
    requiresRollbackPlan: false,
    requestFields: [],
    responseFields: [],
    forbiddenFields: [],
    gates: ['readonly_only', 'no_backend_endpoint', 'no_api_call', 'no_db_write', 'no_external_control', 'stage_c_disabled'],
    blockedActions: ['process_candidate', 'create_approval_queue', 'approve', 'reject', 'archive', 'write_db', 'enable_stage_c'],
    linkedDocs: ['AIP_HUMAN_APPROVAL_WORKFLOW_SPEC.md'],
    reason: 'Candidate processing is blocked in dry-run mode. Requires DB write and Stage C, both permanently disabled.',
    nextAction: 'Keep blocked. Do not process candidates without Stage C.',
  },
  {
    id: 'dry-run-result-persistence-blocked',
    label: 'Dry-run Result Persistence Blocked',
    kind: 'blocked_execution',
    risk: 'high',
    allowedNow: true,
    contractOnly: true,
    executesDryRun: false,
    callsExternalTool: false,
    writesDb: true,
    requiresHumanApproval: false,
    requiresStageC: false,
    requiresEvidence: false,
    requiresAuditLog: false,
    requiresRollbackPlan: false,
    requestFields: [],
    responseFields: [],
    forbiddenFields: [],
    gates: ['readonly_only', 'no_backend_endpoint', 'no_api_call', 'no_db_write', 'no_external_control', 'stage_c_disabled'],
    blockedActions: ['store_dry_run_result', 'persist_prediction', 'save_dry_run_to_db', 'enable_stage_c'],
    linkedDocs: ['AIP_RUNTIME_API_CONTRACT_FREEZE.md'],
    reason: 'Dry-run result persistence is blocked. No dry-run results may be stored to database. DB write is permanently disabled.',
    nextAction: 'Keep blocked. Do not persist dry-run results.',
  },
  {
    id: 'dry-run-idempotency-key-contract',
    label: 'Dry-run Idempotency Key Contract',
    kind: 'request_schema',
    risk: 'low',
    allowedNow: true,
    contractOnly: true,
    executesDryRun: false,
    callsExternalTool: false,
    writesDb: false,
    requiresHumanApproval: false,
    requiresStageC: false,
    requiresEvidence: false,
    requiresAuditLog: false,
    requiresRollbackPlan: false,
    requestFields: ['idempotencyKey', 'timestamp', 'clientId'],
    responseFields: ['keyStatus', 'previousResult', 'expiry'],
    forbiddenFields: ['token', 'apiKey', 'password', 'secret', 'privateKey', 'credential'],
    gates: ['readonly_only', 'no_backend_endpoint', 'no_api_call', 'no_db_write', 'no_external_control', 'stage_c_disabled'],
    blockedActions: ['validate_idempotency', 'store_key', 'check_duplicate', 'enable_stage_c'],
    linkedDocs: ['AIP_RUNTIME_ROLLBACK_IDEMPOTENCY_SPEC.md'],
    reason: 'Dry-run idempotency key contract defines the idempotency key schema for future dry-run requests. No key validation, no duplicate check, no Stage C.',
    nextAction: 'Keep contract_only. Do not implement idempotency without Stage C.',
  },
  {
    id: 'dry-run-error-model-contract',
    label: 'Dry-run Error Model Contract',
    kind: 'response_schema',
    risk: 'low',
    allowedNow: true,
    contractOnly: true,
    executesDryRun: false,
    callsExternalTool: false,
    writesDb: false,
    requiresHumanApproval: false,
    requiresStageC: false,
    requiresEvidence: false,
    requiresAuditLog: false,
    requiresRollbackPlan: false,
    requestFields: [],
    responseFields: ['error', 'code', 'message', 'httpStatus', 'details', 'traceId'],
    forbiddenFields: [],
    gates: ['readonly_only', 'no_backend_endpoint', 'no_api_call', 'no_db_write', 'no_external_control', 'stage_c_disabled'],
    blockedActions: ['generate_error', 'throw_exception', 'log_error', 'enable_stage_c'],
    linkedDocs: ['AIP_RUNTIME_API_ERROR_MODEL.md'],
    reason: 'Dry-run error model contract defines the standard error response shape. No error generation, no exception throwing, no Stage C.',
    nextAction: 'Keep contract_only. Do not implement error generation without Stage C.',
  },
  {
    id: 'dry-run-final-seal-requirement',
    label: 'Dry-run Final Seal Requirement',
    kind: 'gate_check',
    risk: 'low',
    allowedNow: true,
    contractOnly: true,
    executesDryRun: false,
    callsExternalTool: false,
    writesDb: false,
    requiresHumanApproval: false,
    requiresStageC: false,
    requiresEvidence: false,
    requiresAuditLog: false,
    requiresRollbackPlan: false,
    requestFields: [],
    responseFields: ['sealVersion', 'sealDate', 'blockingChecks', 'verdict'],
    forbiddenFields: [],
    gates: ['readonly_only', 'no_backend_endpoint', 'no_api_call', 'no_db_write', 'no_external_control', 'stage_c_disabled'],
    blockedActions: ['create_tag', 'create_release', 'finalize_seal', 'enable_stage_c'],
    linkedDocs: ['AIP_VERSION_SEAL_HANDBOOK.md', 'AIP_VALIDATION_AND_SEAL_PROCESS.md'],
    reason: 'Dry-run final seal requirement defines the seal verification checks. No tag creation, no release, no seal finalization without human approval.',
    nextAction: 'Keep contract_only. Do not finalize seal without human approval.',
  },
];

export function getRuntimeDryRunContractItems(): RuntimeDryRunContractItem[] {
  return RUNTIME_DRY_RUN_CONTRACT_ITEMS;
}

export function getRuntimeDryRunContractSummary(): {
  total: number;
  byKind: Record<string, number>;
  byRisk: Record<string, number>;
  blocked: number;
  executesDryRun: number;
  callsExternalTool: number;
  writesDb: number;
  requiresStageC: number;
} {
  const all = RUNTIME_DRY_RUN_CONTRACT_ITEMS;
  const byKind: Record<string, number> = {};
  const byRisk: Record<string, number> = {};
  for (const item of all) {
    byKind[item.kind] = (byKind[item.kind] || 0) + 1;
    byRisk[item.risk] = (byRisk[item.risk] || 0) + 1;
  }
  return {
    total: all.length,
    byKind,
    byRisk,
    blocked: all.filter(i => !i.allowedNow).length,
    executesDryRun: all.filter(i => i.executesDryRun).length,
    callsExternalTool: all.filter(i => i.callsExternalTool).length,
    writesDb: all.filter(i => i.writesDb).length,
    requiresStageC: all.filter(i => i.requiresStageC).length,
  };
}

export function getRuntimeDryRunContractItemsByKind(kind: DryRunContractKind): RuntimeDryRunContractItem[] {
  return RUNTIME_DRY_RUN_CONTRACT_ITEMS.filter(i => i.kind === kind);
}

export function getRuntimeDryRunContractItemsByRisk(risk: DryRunContractRisk): RuntimeDryRunContractItem[] {
  return RUNTIME_DRY_RUN_CONTRACT_ITEMS.filter(i => i.risk === risk);
}

export function getRuntimeDryRunBlockedItems(): RuntimeDryRunContractItem[] {
  return RUNTIME_DRY_RUN_CONTRACT_ITEMS.filter(i => !i.allowedNow || i.executesDryRun || i.callsExternalTool || i.writesDb || i.requiresStageC);
}
