// Stage C Pre-Enable Seal Candidate Registry — static readonly pre-enable seal candidate items
// Does not execute API calls, modify state, write to databases, or control external tools.
// Stage C remains disabled. This is not an enablement page.

export type PreEnableSealArea =
  | 'baseline'
  | 'seal'
  | 'human_review'
  | 'contract'
  | 'dashboard'
  | 'approval'
  | 'evidence'
  | 'validator'
  | 'smoke'
  | 'safety'
  | 'forbidden'
  | 'rollback_recovery';

export interface PreEnableSealCandidateItem {
  id: string;
  title: string;
  area: PreEnableSealArea;
  readonly: true;
  requiredForPreEnable: boolean;
  canEnableStageC: false;
  actionAllowed: false;
  mutationAllowed: false;
  status: 'confirmed' | 'deferred' | 'not_applicable';
  evidenceRef: string;
  description: string;
}

export const STAGE_C_PREENABLE_SEAL_CANDIDATE_REGISTRY: PreEnableSealCandidateItem[] = [
  // Baseline
  {
    id: 'v7-32-productization-baseline',
    title: 'v7.32 Productization Baseline Confirmed',
    area: 'baseline',
    readonly: true,
    requiredForPreEnable: true,
    canEnableStageC: false,
    actionAllowed: false,
    mutationAllowed: false,
    status: 'confirmed',
    evidenceRef: 'V7_32_PRODUCTIZATION_SEAL_READY',
    description: 'v7.32 baseline sealed. 38 tests pass. 4 GET endpoints live.',
  },
  {
    id: 'v7-33-final-seal',
    title: 'v7.33 Final Seal Confirmed',
    area: 'seal',
    readonly: true,
    requiredForPreEnable: true,
    canEnableStageC: false,
    actionAllowed: false,
    mutationAllowed: false,
    status: 'confirmed',
    evidenceRef: 'V7_33_FINAL_SEAL_READY_WITH_ROUTE_SMOKE_DEFERRED',
    description: 'v7.33 final seal recheck completed. P1-P4 operator console previews.',
  },
  {
    id: 'v7-34-d1-human-review-blueprint',
    title: 'v7.34 D1 Human Review Blueprint',
    area: 'human_review',
    readonly: true,
    requiredForPreEnable: true,
    canEnableStageC: false,
    actionAllowed: false,
    mutationAllowed: false,
    status: 'confirmed',
    evidenceRef: 'V7_34_D1_STAGE_C_HUMAN_REVIEW_BLUEPRINT_READY',
    description: 'D1 blueprint defines roles, escalation, denial, decision records, evidence requirements.',
  },
  {
    id: 'v7-34-d2-readiness-contract',
    title: 'v7.34 D2 Readiness Contract Frozen',
    area: 'contract',
    readonly: true,
    requiredForPreEnable: true,
    canEnableStageC: false,
    actionAllowed: false,
    mutationAllowed: false,
    status: 'confirmed',
    evidenceRef: 'V7_34_D2_STAGE_C_READINESS_CONTRACT_FROZEN',
    description: '24 contract terms frozen. 18 validator checks.',
  },
  {
    id: 'v7-34-p1-dashboard',
    title: 'v7.34 P1 Readiness Dashboard',
    area: 'dashboard',
    readonly: true,
    requiredForPreEnable: true,
    canEnableStageC: false,
    actionAllowed: false,
    mutationAllowed: false,
    status: 'confirmed',
    evidenceRef: 'V7_34_P1_STAGE_C_READINESS_DASHBOARD_PREVIEW_READY',
    description: 'P1 dashboard with 10 sections. Stage C disabled. No enable button.',
  },
  {
    id: 'v7-34-p2-human-approval-review',
    title: 'v7.34 P2 Human Approval Review Console',
    area: 'approval',
    readonly: true,
    requiredForPreEnable: true,
    canEnableStageC: false,
    actionAllowed: false,
    mutationAllowed: false,
    status: 'confirmed',
    evidenceRef: 'V7_34_P2_STAGE_C_HUMAN_APPROVAL_REVIEW_CONSOLE_PREVIEW',
    description: 'P2 human approval review. 22 review items, 18 validator checks. No approve/deny capability.',
  },
  {
    id: 'v7-34-p3-evidence-readiness-drill',
    title: 'v7.34 P3 Evidence Readiness Drill',
    area: 'evidence',
    readonly: true,
    requiredForPreEnable: true,
    canEnableStageC: false,
    actionAllowed: false,
    mutationAllowed: false,
    status: 'confirmed',
    evidenceRef: 'V7_34_P3_STAGE_C_EVIDENCE_READINESS_DRILL_PREVIEW',
    description: 'P3 evidence readiness drill. 24 evidence items. No evidence write/store.',
  },
  {
    id: 'required-validators',
    title: 'Required Validators Pass',
    area: 'validator',
    readonly: true,
    requiredForPreEnable: true,
    canEnableStageC: false,
    actionAllowed: false,
    mutationAllowed: false,
    status: 'confirmed',
    evidenceRef: 'AIP_STAGE_C_REQUIRED_VALIDATORS_MATRIX.md',
    description: 'All validators across all phases pass with blocking=0.',
  },
  {
    id: 'required-evidence',
    title: 'Required Evidence Exists',
    area: 'evidence',
    readonly: true,
    requiredForPreEnable: true,
    canEnableStageC: false,
    actionAllowed: false,
    mutationAllowed: false,
    status: 'confirmed',
    evidenceRef: 'AIP_STAGE_C_REQUIRED_EVIDENCE_MATRIX.md',
    description: 'All required evidence items exist and are accessible.',
  },
  {
    id: 'required-smoke',
    title: 'Required Smoke Pass',
    area: 'smoke',
    readonly: true,
    requiredForPreEnable: true,
    canEnableStageC: false,
    actionAllowed: false,
    mutationAllowed: false,
    status: 'confirmed',
    evidenceRef: 'AIP_STAGE_C_REQUIRED_SMOKE_MATRIX.md',
    description: 'All smoke tests pass. Smoke must be re-run within 24h of enablement.',
  },
  {
    id: 'required-rollback-recovery-docs',
    title: 'Required Rollback/Recovery Docs',
    area: 'rollback_recovery',
    readonly: true,
    requiredForPreEnable: true,
    canEnableStageC: false,
    actionAllowed: false,
    mutationAllowed: false,
    status: 'confirmed',
    evidenceRef: 'Operator console seal candidate registry',
    description: 'Rollback and recovery documentation exists and is reviewed.',
  },
  {
    id: 'human-approval-required',
    title: 'Human Approval Required',
    area: 'human_review',
    readonly: true,
    requiredForPreEnable: true,
    canEnableStageC: false,
    actionAllowed: false,
    mutationAllowed: false,
    status: 'confirmed',
    evidenceRef: 'P2 human approval review registry item',
    description: 'Human owner approval is required before any Stage C enablement.',
  },
  {
    id: 'second-confirmation-required',
    title: 'Second Confirmation Required',
    area: 'human_review',
    readonly: true,
    requiredForPreEnable: true,
    canEnableStageC: false,
    actionAllowed: false,
    mutationAllowed: false,
    status: 'confirmed',
    evidenceRef: 'P2 human approval review registry item',
    description: 'Human owner must provide second confirmation after initial approval.',
  },
  {
    id: 'denial-policy-exists',
    title: 'Denial Policy Exists',
    area: 'human_review',
    readonly: true,
    requiredForPreEnable: true,
    canEnableStageC: false,
    actionAllowed: false,
    mutationAllowed: false,
    status: 'confirmed',
    evidenceRef: 'AIP_STAGE_C_DENIAL_AND_BLOCKER_POLICY.md',
    description: 'Denial and blocker policy documented. Automatic blockers defined.',
  },
  {
    id: 'decision-record-spec-exists',
    title: 'Decision Record Spec Exists',
    area: 'human_review',
    readonly: true,
    requiredForPreEnable: true,
    canEnableStageC: false,
    actionAllowed: false,
    mutationAllowed: false,
    status: 'confirmed',
    evidenceRef: 'AIP_STAGE_C_OPERATOR_DECISION_RECORD_SPEC.md',
    description: 'Decision record spec defines format, fields, and storage requirements.',
  },
  {
    id: 'stage-c-disabled-confirmed',
    title: 'Stage C Disabled Confirmed',
    area: 'safety',
    readonly: true,
    requiredForPreEnable: true,
    canEnableStageC: false,
    actionAllowed: false,
    mutationAllowed: false,
    status: 'confirmed',
    evidenceRef: 'Contract registry item stage-c-disabled + all phase P docs',
    description: 'Stage C confirmed disabled across all registries, pages, and docs.',
  },
  {
    id: 'post-blocked-confirmed',
    title: 'POST Blocked Confirmed',
    area: 'forbidden',
    readonly: true,
    requiredForPreEnable: true,
    canEnableStageC: false,
    actionAllowed: false,
    mutationAllowed: false,
    status: 'confirmed',
    evidenceRef: 'Contract registry item post-blocked',
    description: 'No POST runtime endpoint implemented.',
  },
  {
    id: 'db-write-not-occurred',
    title: 'DB Write Not Occurred',
    area: 'forbidden',
    readonly: true,
    requiredForPreEnable: true,
    canEnableStageC: false,
    actionAllowed: false,
    mutationAllowed: false,
    status: 'confirmed',
    evidenceRef: 'Contract registry item db-write-blocked',
    description: 'No database write has occurred in any phase.',
  },
  {
    id: 'external-control-not-occurred',
    title: 'External Control Not Occurred',
    area: 'forbidden',
    readonly: true,
    requiredForPreEnable: true,
    canEnableStageC: false,
    actionAllowed: false,
    mutationAllowed: false,
    status: 'confirmed',
    evidenceRef: 'Contract registry item external-control-blocked',
    description: 'No external tool control has been implemented.',
  },
  {
    id: 'executor-absent-confirmed',
    title: 'Executor Absent Confirmed',
    area: 'forbidden',
    readonly: true,
    requiredForPreEnable: true,
    canEnableStageC: false,
    actionAllowed: false,
    mutationAllowed: false,
    status: 'confirmed',
    evidenceRef: 'Contract registry item executor-absent',
    description: 'No runtime executor has been implemented.',
  },
  {
    id: 'connector-action-absent',
    title: 'Connector Action Absent',
    area: 'forbidden',
    readonly: true,
    requiredForPreEnable: false,
    canEnableStageC: false,
    actionAllowed: false,
    mutationAllowed: false,
    status: 'confirmed',
    evidenceRef: 'Forbidden actions contract item and center-access registry',
    description: 'No connector action performed. All connectors are readonly.',
  },
  {
    id: 'sidebar-boundary-confirmed',
    title: 'Sidebar Boundary Confirmed',
    area: 'safety',
    readonly: true,
    requiredForPreEnable: true,
    canEnableStageC: false,
    actionAllowed: false,
    mutationAllowed: false,
    status: 'confirmed',
    evidenceRef: 'Navigation exposure registry for all Stage C routes',
    description: 'All Stage C routes are hidden direct. Not in sidebar.',
  },
  {
    id: 'tag-release-not-performed',
    title: 'Tag/Release Not Performed',
    area: 'forbidden',
    readonly: true,
    requiredForPreEnable: false,
    canEnableStageC: false,
    actionAllowed: false,
    mutationAllowed: false,
    status: 'confirmed',
    evidenceRef: 'git tag output + GitHub releases check',
    description: 'No git tag or GitHub Release performed. Package is commit-only.',
  },
  {
    id: 'contract-v1-frozen',
    title: 'Readiness Contract V1 Frozen',
    area: 'contract',
    readonly: true,
    requiredForPreEnable: true,
    canEnableStageC: false,
    actionAllowed: false,
    mutationAllowed: false,
    status: 'confirmed',
    evidenceRef: 'AIP_STAGE_C_READINESS_CONTRACT_V1.md',
    description: '24 contract terms across 10 areas. All frozen.',
  },
  {
    id: 'forbidden-actions-contract',
    title: 'Forbidden Actions Contract',
    area: 'forbidden',
    readonly: true,
    requiredForPreEnable: true,
    canEnableStageC: false,
    actionAllowed: false,
    mutationAllowed: false,
    status: 'confirmed',
    evidenceRef: 'AIP_STAGE_C_FORBIDDEN_ACTIONS_CONTRACT.md',
    description: 'Forbidden actions contract documents all prohibited actions.',
  },
  {
    id: 'evidence-matrix',
    title: 'Evidence Matrix Documented',
    area: 'evidence',
    readonly: true,
    requiredForPreEnable: true,
    canEnableStageC: false,
    actionAllowed: false,
    mutationAllowed: false,
    status: 'confirmed',
    evidenceRef: 'AIP_STAGE_C_REQUIRED_EVIDENCE_MATRIX.md',
    description: 'Evidence matrix lists all required evidence by phase.',
  },
  {
    id: 'validator-matrix',
    title: 'Validator Matrix Documented',
    area: 'validator',
    readonly: true,
    requiredForPreEnable: true,
    canEnableStageC: false,
    actionAllowed: false,
    mutationAllowed: false,
    status: 'confirmed',
    evidenceRef: 'AIP_STAGE_C_REQUIRED_VALIDATORS_MATRIX.md',
    description: 'Validator matrix lists all required validators by phase.',
  },
  {
    id: 'smoke-matrix',
    title: 'Smoke Matrix Documented',
    area: 'smoke',
    readonly: true,
    requiredForPreEnable: true,
    canEnableStageC: false,
    actionAllowed: false,
    mutationAllowed: false,
    status: 'confirmed',
    evidenceRef: 'AIP_STAGE_C_REQUIRED_SMOKE_MATRIX.md',
    description: 'Smoke matrix lists all required smoke tests by phase.',
  },
  {
    id: 'final-seal-candidate-only',
    title: 'Final Seal Candidate Only',
    area: 'seal',
    readonly: true,
    requiredForPreEnable: false,
    canEnableStageC: false,
    actionAllowed: false,
    mutationAllowed: false,
    status: 'confirmed',
    evidenceRef: 'V7_34_P4_STAGE_C_PREENABLE_SEAL_CANDIDATE',
    description: 'This is a pre-enable seal candidate. Not a final enablement. Stage C remains disabled.',
  },
];
