// Stage C Human Approval Review Registry — static readonly human approval review items
// Does not execute API calls, modify state, write to databases, or control external tools.
// Stage C remains disabled.

export type HumanApprovalReviewArea =
  | 'role_boundary'
  | 'approval_gate'
  | 'denial_policy'
  | 'escalation'
  | 'decision_record'
  | 'evidence'
  | 'safety'
  | 'forbidden'
  | 'next_step';

export interface HumanApprovalReviewItem {
  id: string;
  title: string;
  area: HumanApprovalReviewArea;
  readonly: true;
  actionAllowed: false;
  mutationAllowed: false;
  canApprove: false;
  canDeny: false;
  canEnableStageC: false;
  required: boolean;
  status: 'ready' | 'deferred' | 'blocked' | 'not_applicable';
  evidenceRef: string;
  description: string;
}

export const STAGE_C_HUMAN_APPROVAL_REVIEW_REGISTRY: HumanApprovalReviewItem[] = [
  {
    id: 'human-owner-approval-required',
    title: 'Human Owner Approval Required',
    area: 'approval_gate',
    readonly: true,
    actionAllowed: false,
    mutationAllowed: false,
    canApprove: false,
    canDeny: false,
    canEnableStageC: false,
    required: true,
    status: 'ready',
    evidenceRef: 'V7_34_D1_STAGE_C_HUMAN_REVIEW_BLUEPRINT_READY',
    description: 'Stage C enablement requires explicit human owner approval. Assistant cannot approve.',
  },
  {
    id: 'operator-role-boundary',
    title: 'Operator Role Boundary',
    area: 'role_boundary',
    readonly: true,
    actionAllowed: false,
    mutationAllowed: false,
    canApprove: false,
    canDeny: false,
    canEnableStageC: false,
    required: true,
    status: 'ready',
    evidenceRef: 'D1 human review blueprint roles section',
    description: 'Operator prepares evidence and smoke results. Cannot approve Stage C. Cannot bypass human owner.',
  },
  {
    id: 'assistant-role-boundary',
    title: 'Assistant Role Boundary',
    area: 'role_boundary',
    readonly: true,
    actionAllowed: false,
    mutationAllowed: false,
    canApprove: false,
    canDeny: false,
    canEnableStageC: false,
    required: true,
    status: 'ready',
    evidenceRef: 'D1 human review blueprint roles section',
    description: 'Assistant provides readiness dashboards, contract terms, and validator results. Cannot approve Stage C, execute runtime, or modify system state.',
  },
  {
    id: 'stage-c-denied-by-default',
    title: 'Stage C Enablement Denied by Default',
    area: 'approval_gate',
    readonly: true,
    actionAllowed: false,
    mutationAllowed: false,
    canApprove: false,
    canDeny: false,
    canEnableStageC: false,
    required: true,
    status: 'ready',
    evidenceRef: 'D1 denial and blocker policy doc',
    description: 'Stage C is denied by default. Affirmative human owner decision required for enablement.',
  },
  {
    id: 'second-confirmation-required',
    title: 'Second Confirmation Required',
    area: 'approval_gate',
    readonly: true,
    actionAllowed: false,
    mutationAllowed: false,
    canApprove: false,
    canDeny: false,
    canEnableStageC: false,
    required: true,
    status: 'ready',
    evidenceRef: 'D1 human review blueprint — second confirmation section',
    description: 'Human owner must provide second confirmation after initial approval. Single-click cannot enable Stage C.',
  },
  {
    id: 'escalation-model-defined',
    title: 'Escalation Model Defined',
    area: 'escalation',
    readonly: true,
    actionAllowed: false,
    mutationAllowed: false,
    canApprove: false,
    canDeny: false,
    canEnableStageC: false,
    required: true,
    status: 'ready',
    evidenceRef: 'AIP_STAGE_C_APPROVAL_ESCALATION_MODEL.md',
    description: 'Escalation path defined for blocked or contested decisions. Senior human owner can override denial.',
  },
  {
    id: 'denial-blocker-policy',
    title: 'Denial / Blocker Policy',
    area: 'denial_policy',
    readonly: true,
    actionAllowed: false,
    mutationAllowed: false,
    canApprove: false,
    canDeny: false,
    canEnableStageC: false,
    required: true,
    status: 'ready',
    evidenceRef: 'AIP_STAGE_C_DENIAL_AND_BLOCKER_POLICY.md',
    description: 'Automatic blockers: missing evidence, stale smoke, validator failures, unresolved rollback docs. Denial requires documented reason.',
  },
  {
    id: 'decision-record-spec',
    title: 'Decision Record Spec',
    area: 'decision_record',
    readonly: true,
    actionAllowed: false,
    mutationAllowed: false,
    canApprove: false,
    canDeny: false,
    canEnableStageC: false,
    required: true,
    status: 'ready',
    evidenceRef: 'AIP_STAGE_C_OPERATOR_DECISION_RECORD_SPEC.md',
    description: 'Decision record captures: timestamp, decider identity, decision type, rationale, evidence references, expiry. Assistant records but does not decide.',
  },
  {
    id: 'pre-enable-evidence-requirements',
    title: 'Pre-Enable Evidence Requirements',
    area: 'evidence',
    readonly: true,
    actionAllowed: false,
    mutationAllowed: false,
    canApprove: false,
    canDeny: false,
    canEnableStageC: false,
    required: true,
    status: 'ready',
    evidenceRef: 'AIP_STAGE_C_PRE_ENABLE_EVIDENCE_REQUIREMENTS.md',
    description: 'All required evidence must be collected and confirmed before enablement. No evidence bypass.',
  },
  {
    id: 'required-validator-pass',
    title: 'Required Validator Pass',
    area: 'approval_gate',
    readonly: true,
    actionAllowed: false,
    mutationAllowed: false,
    canApprove: false,
    canDeny: false,
    canEnableStageC: false,
    required: true,
    status: 'ready',
    evidenceRef: 'AIP_STAGE_C_REQUIRED_VALIDATORS_MATRIX.md',
    description: 'All validators must pass (blocking=0) before human owner review.',
  },
  {
    id: 'required-smoke-pass',
    title: 'Required Smoke Pass',
    area: 'approval_gate',
    readonly: true,
    actionAllowed: false,
    mutationAllowed: false,
    canApprove: false,
    canDeny: false,
    canEnableStageC: false,
    required: true,
    status: 'ready',
    evidenceRef: 'AIP_STAGE_C_REQUIRED_SMOKE_MATRIX.md',
    description: 'All smoke tests must pass within 24h of enablement request.',
  },
  {
    id: 'required-rollback-docs',
    title: 'Required Rollback Docs',
    area: 'evidence',
    readonly: true,
    actionAllowed: false,
    mutationAllowed: false,
    canApprove: false,
    canDeny: false,
    canEnableStageC: false,
    required: true,
    status: 'ready',
    evidenceRef: 'Rollback docs in operator console seal candidate registry',
    description: 'Rollback procedure must be documented and reviewed before enablement.',
  },
  {
    id: 'required-recovery-docs',
    title: 'Required Recovery Docs',
    area: 'evidence',
    readonly: true,
    actionAllowed: false,
    mutationAllowed: false,
    canApprove: false,
    canDeny: false,
    canEnableStageC: false,
    required: true,
    status: 'ready',
    evidenceRef: 'Recovery plan in operator console seal candidate registry',
    description: 'Recovery plan must be documented for post-enablement failure scenarios.',
  },
  {
    id: 'no-db-write',
    title: 'No DB Write',
    area: 'safety',
    readonly: true,
    actionAllowed: false,
    mutationAllowed: false,
    canApprove: false,
    canDeny: false,
    canEnableStageC: false,
    required: true,
    status: 'ready',
    evidenceRef: 'Contract registry item db-write-blocked',
    description: 'No database write occurred in any preview phase. All registries enforce readonly.',
  },
  {
    id: 'no-post-action',
    title: 'No POST Action',
    area: 'safety',
    readonly: true,
    actionAllowed: false,
    mutationAllowed: false,
    canApprove: false,
    canDeny: false,
    canEnableStageC: false,
    required: true,
    status: 'ready',
    evidenceRef: 'Contract registry item post-blocked',
    description: 'No POST runtime endpoint implemented. All previews are frontend-only.',
  },
  {
    id: 'no-executor',
    title: 'No Executor',
    area: 'safety',
    readonly: true,
    actionAllowed: false,
    mutationAllowed: false,
    canApprove: false,
    canDeny: false,
    canEnableStageC: false,
    required: true,
    status: 'ready',
    evidenceRef: 'Contract registry item executor-absent',
    description: 'No runtime executor implemented. No action execution capability exists.',
  },
  {
    id: 'no-external-control',
    title: 'No External Control',
    area: 'safety',
    readonly: true,
    actionAllowed: false,
    mutationAllowed: false,
    canApprove: false,
    canDeny: false,
    canEnableStageC: false,
    required: true,
    status: 'ready',
    evidenceRef: 'Contract registry item external-control-blocked',
    description: 'No external tool control implemented. No connector actions.',
  },
  {
    id: 'no-connector-action',
    title: 'No Connector Action',
    area: 'forbidden',
    readonly: true,
    actionAllowed: false,
    mutationAllowed: false,
    canApprove: false,
    canDeny: false,
    canEnableStageC: false,
    required: true,
    status: 'ready',
    evidenceRef: 'Forbidden actions contract item',
    description: 'No connector action performed. All connectors are readonly.',
  },
  {
    id: 'no-release-tag',
    title: 'No Release/Tag',
    area: 'forbidden',
    readonly: true,
    actionAllowed: false,
    mutationAllowed: false,
    canApprove: false,
    canDeny: false,
    canEnableStageC: false,
    required: true,
    status: 'ready',
    evidenceRef: 'Forbidden actions contract item',
    description: 'No git tag or GitHub Release performed. Package is commit-only.',
  },
  {
    id: 'no-sidebar-exposure',
    title: 'No Sidebar Exposure',
    area: 'forbidden',
    readonly: true,
    actionAllowed: false,
    mutationAllowed: false,
    canApprove: false,
    canDeny: false,
    canEnableStageC: false,
    required: true,
    status: 'ready',
    evidenceRef: 'Navigation exposure registry stage_c_disabled gate',
    description: 'All Stage C preview routes are hidden direct only. Not in sidebar.',
  },
  {
    id: 'route-hidden-direct',
    title: 'Route Hidden Direct',
    area: 'safety',
    readonly: true,
    actionAllowed: false,
    mutationAllowed: false,
    canApprove: false,
    canDeny: false,
    canEnableStageC: false,
    required: true,
    status: 'ready',
    evidenceRef: 'App.tsx route /stage-c-human-approval-review-preview',
    description: 'Route is hidden direct. No sidebar entry. No menu-registry change.',
  },
  {
    id: 'next-step-p3-evidence-drill',
    title: 'Next Step: P3 Evidence Readiness Drill',
    area: 'next_step',
    readonly: true,
    actionAllowed: false,
    mutationAllowed: false,
    canApprove: false,
    canDeny: false,
    canEnableStageC: false,
    required: false,
    status: 'deferred',
    evidenceRef: 'V7_34_P3_EVIDENCE_READINESS_DRILL_PREVIEW',
    description: 'P3 preview planned after P2. Evidence readiness drill will verify all evidence items.',
  },
];
