// Stage C Safety Harness Contract Registry — static readonly safety harness contract terms
// Does not execute API calls, modify state, write to databases, or control external tools.
// Stage C remains disabled. This is a safety harness contract, not an implementation mechanism.

export type SafetyHarnessCategory =
  | 'authorization'
  | 'feature_flag'
  | 'kill_switch'
  | 'api_boundary'
  | 'audit'
  | 'rollback'
  | 'validation'
  | 'safety'
  | 'forbidden_action'
  | 'next_step';

export type HarnessStatus = 'required' | 'ready' | 'pending' | 'forbidden' | 'not_applicable';

export interface StageCSafetyHarnessContractItem {
  id: string;
  title: string;
  category: SafetyHarnessCategory;
  status: HarnessStatus;
  readonly: true;
  contractOnly: true;
  implementationAllowed: false;
  actionAllowed: false;
  mutationAllowed: false;
  canEnableStageC: false;
  evidenceRef: string;
  linkedDoc?: string;
  summary: string;
  forbiddenAction: string;
}

export const STAGE_C_SAFETY_HARNESS_CONTRACT_REGISTRY: StageCSafetyHarnessContractItem[] = [
  // Authorization
  {
    id: 'authorization-pending-blocker',
    title: 'Authorization Pending Blocker',
    category: 'authorization',
    status: 'pending',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AUTHORIZATION_PENDING — no real human owner auth',
    linkedDoc: 'AIP_V7_35_FINAL_SEAL_RECHECK.md',
    summary: 'Authorization state is PENDING. No enablement possible until resolved.',
    forbiddenAction: 'Do not enable Stage C with authorization PENDING.',
  },
  {
    id: 'human-authorization-artifact-required',
    title: 'Human Authorization Artifact Required',
    category: 'authorization',
    status: 'required',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_HUMAN_AUTHORIZATION_TEXT_SPEC.md',
    summary: 'Human owner must provide explicit authorization artifact before any enablement.',
    forbiddenAction: 'Do not proceed without committed authorization artifact.',
  },
  // Feature Flag
  {
    id: 'feature-flag-default-off',
    title: 'Feature Flag Default Off',
    category: 'feature_flag',
    status: 'required',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_FEATURE_FLAG_DESIGN.md',
    summary: 'stageC.enabled must default to false.',
    forbiddenAction: 'Do not implement enablement without feature flag defaulting to off.',
  },
  {
    id: 'feature-flag-no-preview-toggle',
    title: 'Feature Flag Cannot Be Toggled by Preview',
    category: 'feature_flag',
    status: 'required',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_FEATURE_FLAG_DESIGN.md',
    summary: 'Feature flag must not be toggleable from any hidden preview page.',
    forbiddenAction: 'Do not add enable button to any preview page.',
  },
  {
    id: 'feature-flag-no-ai-toggle',
    title: 'Feature Flag Cannot Be Changed by AI',
    category: 'feature_flag',
    status: 'required',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_FEATURE_FLAG_DESIGN.md',
    summary: 'AI assistant must not automatically toggle feature flag.',
    forbiddenAction: 'Do not implement AI-driven flag toggle.',
  },
  {
    id: 'feature-flag-server-side',
    title: 'Feature Flag Server-Side Only',
    category: 'feature_flag',
    status: 'required',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_FEATURE_FLAG_DESIGN.md',
    summary: 'Feature flag must be stored and verified server-side, not frontend.',
    forbiddenAction: 'Do not implement client-side-only flag.',
  },
  // Kill Switch
  {
    id: 'kill-switch-required',
    title: 'Kill Switch Required',
    category: 'kill_switch',
    status: 'required',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_KILL_SWITCH_DESIGN.md',
    summary: 'Kill switch must be present before any enablement.',
    forbiddenAction: 'Do not enable Stage C without kill switch.',
  },
  {
    id: 'kill-switch-no-db-destruct',
    title: 'Kill Switch No DB Destructive Operation',
    category: 'kill_switch',
    status: 'required',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_KILL_SWITCH_DESIGN.md',
    summary: 'Kill switch must not destroy database tables or data.',
    forbiddenAction: 'Do not implement destructive kill switch.',
  },
  {
    id: 'kill-switch-audit-note',
    title: 'Kill Switch Audit Note Required',
    category: 'kill_switch',
    status: 'required',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_KILL_SWITCH_DESIGN.md',
    summary: 'Kill switch requires human-provided reason in audit note.',
    forbiddenAction: 'Do not implement silent kill switch.',
  },
  {
    id: 'kill-switch-tested-dry-run',
    title: 'Kill Switch Must Be Tested in Dry-Run',
    category: 'kill_switch',
    status: 'required',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_KILL_SWITCH_DESIGN.md',
    summary: 'Kill switch must be tested in dry-run before production.',
    forbiddenAction: 'Do not deploy kill switch without dry-run test.',
  },
  // API Boundary
  {
    id: 'post-endpoint-placeholder-only',
    title: 'POST Endpoint Placeholder Only',
    category: 'api_boundary',
    status: 'forbidden',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_API_DESIGN_DRAFT.md',
    summary: 'POST endpoint for enablement is design placeholder only. Not implemented.',
    forbiddenAction: 'Do not implement POST enablement endpoint in current task.',
  },
  {
    id: 'db-migration-placeholder-only',
    title: 'DB Migration Placeholder Only',
    category: 'api_boundary',
    status: 'forbidden',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_IMPLEMENTATION_BLUEPRINT.md',
    summary: 'DB migration for Stage C is design placeholder only. Not implemented.',
    forbiddenAction: 'Do not implement DB migration in current task.',
  },
  {
    id: 'executor-placeholder-only',
    title: 'Executor Placeholder Only',
    category: 'api_boundary',
    status: 'forbidden',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_IMPLEMENTATION_BLUEPRINT.md',
    summary: 'Enablement executor is design placeholder only. Not implemented.',
    forbiddenAction: 'Do not implement executor in current task.',
  },
  {
    id: 'no-implementation-in-current-task',
    title: 'No Implementation in Current Task',
    category: 'api_boundary',
    status: 'forbidden',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_V7_36_D1_STAGE_C_ENABLEMENT_IMPLEMENTATION_BLUEPRINT.md',
    summary: 'Current v7.36 task produces blueprint and contract only. No runtime implementation.',
    forbiddenAction: 'Do not implement any POST/DB/executor in this task.',
  },
  // Audit
  {
    id: 'audit-event-design-required',
    title: 'Audit Event Design Required',
    category: 'audit',
    status: 'required',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_AUDIT_EVENT_DESIGN.md',
    summary: 'Audit event schema must be designed before enablement.',
    forbiddenAction: 'Do not implement enablement without audit event design.',
  },
  {
    id: 'evidence-redaction-required',
    title: 'Evidence Redaction Required',
    category: 'audit',
    status: 'required',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_AUDIT_EVENT_DESIGN.md',
    summary: 'Secrets/tokens must be redacted from evidence capture.',
    forbiddenAction: 'Do not capture evidence without redaction.',
  },
  {
    id: 'audit-append-only',
    title: 'Audit Events Append-Only',
    category: 'audit',
    status: 'required',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_AUDIT_EVENT_DESIGN.md',
    summary: 'Audit events must be append-only with no deletion capability.',
    forbiddenAction: 'Do not implement audit event deletion.',
  },
  // Rollback
  {
    id: 'rollback-plan-required',
    title: 'Rollback Plan Required',
    category: 'rollback',
    status: 'required',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_ROLLBACK_RECOVERY_DESIGN.md',
    summary: 'Rollback plan must exist before any enablement.',
    forbiddenAction: 'Do not enable without rollback plan.',
  },
  {
    id: 'recovery-plan-required',
    title: 'Recovery Plan Required',
    category: 'rollback',
    status: 'required',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_ROLLBACK_RECOVERY_DESIGN.md',
    summary: 'Recovery plan for failed enablement must exist.',
    forbiddenAction: 'Do not enable without recovery plan.',
  },
  {
    id: 'rollback-idempotent',
    title: 'Rollback Must Be Idempotent',
    category: 'rollback',
    status: 'required',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_ROLLBACK_RECOVERY_DESIGN.md',
    summary: 'Rollback must be safe to run multiple times.',
    forbiddenAction: 'Do not implement non-idempotent rollback.',
  },
  {
    id: 'idempotency-requirement',
    title: 'Idempotency Requirement',
    category: 'rollback',
    status: 'required',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_ROLLBACK_RECOVERY_DESIGN.md',
    summary: 'All enablement operations must be idempotent.',
    forbiddenAction: 'Do not implement non-idempotent enablement.',
  },
  {
    id: 'dry-run-first-requirement',
    title: 'Dry-Run First Requirement',
    category: 'rollback',
    status: 'required',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_IMPLEMENTATION_BLUEPRINT.md',
    summary: 'Dry-run mode must execute before any actual enablement state change.',
    forbiddenAction: 'Do not skip dry-run before enablement.',
  },
  {
    id: 'canary-requirement',
    title: 'Canary Requirement',
    category: 'rollback',
    status: 'required',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_TEST_AND_SMOKE_PLAN.md',
    summary: 'Canary deployment required for Stage C enablement.',
    forbiddenAction: 'Do not enable all instances without canary.',
  },
  {
    id: 'rate-limit-requirement',
    title: 'Rate Limit Requirement',
    category: 'rollback',
    status: 'required',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_KILL_SWITCH_DESIGN.md',
    summary: 'Rate limiting required on enable/disable/kill endpoints to prevent rapid toggle.',
    forbiddenAction: 'Do not implement enablement without rate limiting.',
  },
  // Validation
  {
    id: 'validation-gate-required',
    title: 'Validation Gate Required',
    category: 'validation',
    status: 'required',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'All validators: blocking=0',
    summary: 'All validators must pass (blocking=0) before enablement.',
    forbiddenAction: 'Do not enable with validator failures.',
  },
  {
    id: 'smoke-gate-required',
    title: 'Smoke Gate Required',
    category: 'validation',
    status: 'required',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'tests/smoke-v7.mjs',
    summary: 'Smoke tests must pass before and after enablement.',
    forbiddenAction: 'Do not enable with smoke test failures.',
  },
  {
    id: 'safety-search-gate-required',
    title: 'Safety Search Gate Required',
    category: 'validation',
    status: 'required',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'Safety search scan',
    summary: 'Safety search must pass (zero issues) before enablement.',
    forbiddenAction: 'Do not enable with safety search issues.',
  },
  {
    id: 'final-human-gate-required',
    title: 'Final Human Gate Required',
    category: 'validation',
    status: 'required',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_HUMAN_OWNER_FINAL_CONFIRMATION_POLICY.md',
    summary: 'A separate final human gate must confirm enablement readiness.',
    forbiddenAction: 'Do not skip final human gate.',
  },
  // Safety
  {
    id: 'hidden-route-boundary',
    title: 'Hidden Route Boundary',
    category: 'safety',
    status: 'ready',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'All Stage C routes: visibleInSidebar=false',
    summary: 'All Stage C routes are hidden direct. Not in sidebar.',
    forbiddenAction: 'Do not expose Stage C routes to sidebar.',
  },
  {
    id: 'sidebar-non-exposure',
    title: 'Sidebar Non-Exposure',
    category: 'safety',
    status: 'ready',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'center-access-registry.ts: visibleInSidebar=false',
    summary: 'Stage C routes must never be added to sidebar.',
    forbiddenAction: 'Do not add Stage C routes to sidebar.',
  },
  {
    id: 'no-external-control-by-default',
    title: 'No External Control by Default',
    category: 'safety',
    status: 'forbidden',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_FORBIDDEN_ACTIONS_CONTRACT.md',
    summary: 'External control must not be called during enablement without explicit approval.',
    forbiddenAction: 'Do not call external services during enablement.',
  },
  {
    id: 'no-connector-action-by-default',
    title: 'No Connector Action by Default',
    category: 'safety',
    status: 'forbidden',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_FORBIDDEN_ACTIONS_CONTRACT.md',
    summary: 'Connector actions must not fire during enablement without explicit approval.',
    forbiddenAction: 'Do not trigger connector actions during enablement.',
  },
  {
    id: 'secret-redaction-required',
    title: 'Secret Redaction Required',
    category: 'safety',
    status: 'required',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_AUDIT_EVENT_DESIGN.md',
    summary: 'All secrets/tokens/keys must be redacted from logs, evidence, and audit events.',
    forbiddenAction: 'Do not log secrets during enablement.',
  },
  // Forbidden Actions (V2)
  {
    id: 'release-tag-forbidden-v2',
    title: 'Release/Tag Forbidden (V2)',
    category: 'forbidden_action',
    status: 'forbidden',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_FORBIDDEN_ACTIONS_V2.md',
    summary: 'No git tag or GitHub Release without explicit human approval during enablement.',
    forbiddenAction: 'Do not create tag or release.',
  },
  {
    id: 'auto-approval-forbidden-v2',
    title: 'Auto-Approval Forbidden (V2)',
    category: 'forbidden_action',
    status: 'forbidden',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_FORBIDDEN_ACTIONS_V2.md',
    summary: 'No auto-approval of enablement steps.',
    forbiddenAction: 'Do not implement auto-approval.',
  },
  {
    id: 'auto-enable-forbidden-v2',
    title: 'Auto-Enable Forbidden (V2)',
    category: 'forbidden_action',
    status: 'forbidden',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_FORBIDDEN_ACTIONS_V2.md',
    summary: 'No automatic Stage C enablement after authorization.',
    forbiddenAction: 'Do not implement auto-enable.',
  },
  {
    id: 'ai-fake-auth-forbidden-v2',
    title: 'AI Fake Authorization Forbidden (V2)',
    category: 'forbidden_action',
    status: 'forbidden',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_FORBIDDEN_ACTIONS_V2.md',
    summary: 'AI must not generate, sign, or confirm authorization or enablement.',
    forbiddenAction: 'Do not accept AI-generated authorization.',
  },
  {
    id: 'simulation-written-as-real',
    title: 'Simulation Written as Real Execution',
    category: 'forbidden_action',
    status: 'forbidden',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_FORBIDDEN_ACTIONS_V2.md',
    summary: 'Simulation must not be described as real execution.',
    forbiddenAction: 'Do not conflate simulation with actual enablement.',
  },
  {
    id: 'blueprint-written-as-complete',
    title: 'Blueprint Written as Implementation Complete',
    category: 'forbidden_action',
    status: 'forbidden',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_FORBIDDEN_ACTIONS_V2.md',
    summary: 'Blueprint must not be described as implementation complete.',
    forbiddenAction: 'Do not claim implementation is done when only blueprint exists.',
  },
  {
    id: 'no-mutation-allowed-v2',
    title: 'No Mutation Allowed (V2)',
    category: 'forbidden_action',
    status: 'forbidden',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_FORBIDDEN_ACTIONS_V2.md',
    summary: 'Safety harness contract does not permit mutation.',
    forbiddenAction: 'Do not mutate safety harness contract.',
  },
  // Next Step
  {
    id: 'next-step-p2-p3-p4-safety',
    title: 'Next Step: P2/P3/P4 + Final Enablement Safety Acceleration',
    category: 'next_step',
    status: 'pending',
    readonly: true,
    contractOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'V7_36_D2_STAGE_C_SAFETY_HARNESS_CONTRACT_FROZEN_WITH_AUTHORIZATION_PENDING',
    summary: 'P2/P3/P4 planned after D1+D2+P1. Final enablement safety acceleration.',
    forbiddenAction: 'Do not skip safety acceleration before any enablement.',
  },
];
