// Stage C Authorization Artifact Review Registry — static readonly artifact review items
// Does not execute API calls, modify state, write to databases, or control external tools.
// Stage C remains disabled. This is an artifact review, not an authorization approval mechanism.

export type ArtifactReviewCategory =
  | 'baseline'
  | 'authorization_artifact'
  | 'required_field'
  | 'evidence'
  | 'blocker'
  | 'safety'
  | 'human_review'
  | 'next_step';

export type ArtifactStatus = 'ready' | 'present' | 'pending' | 'blocked' | 'forbidden' | 'not_applicable';

export interface StageCAuthorizationArtifactReviewItem {
  id: string;
  title: string;
  category: ArtifactReviewCategory;
  status: ArtifactStatus;
  readonly: true;
  requiredForHumanReview: boolean;
  actionAllowed: false;
  mutationAllowed: false;
  canAuthorize: false;
  canEnableStageC: false;
  evidenceRef: string;
  linkedDoc?: string;
  summary: string;
  forbiddenAction: string;
}

export const STAGE_C_AUTHORIZATION_ARTIFACT_REVIEW_REGISTRY: StageCAuthorizationArtifactReviewItem[] = [
  // === Baseline ===
  {
    id: 'v7-34-final-seal-baseline',
    title: 'v7.34 Final Seal Baseline',
    category: 'baseline',
    status: 'ready',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'V7_34_FINAL_SEAL_READY_WITH_ROUTE_SMOKE_DEFERRED',
    linkedDoc: 'AIP_V7_34_FINAL_SEAL_RECHECK.md',
    summary: 'v7.34 final seal completed. Stage C remains disabled. No POST, DB, executor, external control.',
    forbiddenAction: 'Do not skip v7.34 final seal baseline check.',
  },
  {
    id: 'v7-35-d1-authorization-package',
    title: 'v7.35 D1 Authorization Package',
    category: 'baseline',
    status: 'ready',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'V7_35_D1_STAGE_C_HUMAN_AUTHORIZATION_PACKAGE_READY',
    linkedDoc: 'AIP_V7_35_D1_STAGE_C_HUMAN_AUTHORIZATION_PACKAGE.md',
    summary: 'v7.35 D1 authorization package committed. 7 docs defining human authorization as docs-only policy.',
    forbiddenAction: 'Do not treat D1 docs as actual human authorization.',
  },
  {
    id: 'v7-35-d2-authorization-contract',
    title: 'v7.35 D2 Authorization Contract',
    category: 'baseline',
    status: 'ready',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'V7_35_D2_STAGE_C_AUTHORIZATION_CONTRACT_FROZEN',
    linkedDoc: 'AIP_STAGE_C_AUTHORIZATION_CONTRACT_V1.md',
    summary: 'v7.35 D2 authorization contract frozen. 28 items, 19 validators, 5 contract docs.',
    forbiddenAction: 'Do not skip D2 contract freeze before review.',
  },
  {
    id: 'v7-35-p1-review-console',
    title: 'v7.35 P1 Review Console Preview',
    category: 'baseline',
    status: 'ready',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'V7_35_P1_STAGE_C_AUTHORIZATION_REVIEW_CONSOLE_PREVIEW_READY',
    linkedDoc: 'AIP_V7_35_P1_STAGE_C_AUTHORIZATION_REVIEW_CONSOLE_PREVIEW.md',
    summary: 'v7.35 P1 review console preview committed. 12-section readonly page.',
    forbiddenAction: 'Do not bypass P1 review console.',
  },

  // === Authorization Artifact ===
  {
    id: 'authorization-text-spec',
    title: 'Authorization Text Spec',
    category: 'authorization_artifact',
    status: 'present',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_HUMAN_AUTHORIZATION_TEXT_SPEC.md',
    linkedDoc: 'AIP_STAGE_C_HUMAN_AUTHORIZATION_TEXT_SPEC.md',
    summary: 'Authorization text template spec exists. Actual authorization text is pending human owner.',
    forbiddenAction: 'Do not treat spec as actual authorization.',
  },
  {
    id: 'required-fields-matrix',
    title: 'Required Fields Matrix',
    category: 'authorization_artifact',
    status: 'present',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_AUTHORIZATION_REQUIRED_FIELDS_MATRIX.md',
    summary: 'Required fields matrix exists documenting signer, timestamp, scope requirements.',
    forbiddenAction: 'Do not skip required fields check.',
  },
  {
    id: 'blocker-matrix',
    title: 'Blocker Matrix',
    category: 'authorization_artifact',
    status: 'present',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_AUTHORIZATION_BLOCKER_MATRIX.md',
    summary: 'Blocker matrix exists documenting all blocking conditions.',
    forbiddenAction: 'Do not proceed without resolving all blockers.',
  },
  {
    id: 'evidence-requirements',
    title: 'Evidence Requirements',
    category: 'authorization_artifact',
    status: 'present',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_AUTHORIZATION_EVIDENCE_REQUIREMENTS.md',
    summary: 'Evidence requirements doc exists documenting all required evidence.',
    forbiddenAction: 'Do not skip evidence requirements.',
  },
  {
    id: 'forbidden-automation-contract',
    title: 'Forbidden Automation Contract',
    category: 'authorization_artifact',
    status: 'present',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_AUTHORIZATION_FORBIDDEN_AUTOMATION_CONTRACT.md',
    summary: 'Forbidden automation contract exists (10 items including AI fake auth, auto-approve, auto-enable).',
    forbiddenAction: 'Do not allow any forbidden automation item.',
  },
  {
    id: 'human-owner-confirmation-policy',
    title: 'Human Owner Final Confirmation Policy',
    category: 'authorization_artifact',
    status: 'present',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_HUMAN_OWNER_FINAL_CONFIRMATION_POLICY.md',
    summary: 'Human owner final confirmation policy exists.',
    forbiddenAction: 'Do not bypass human owner final confirmation.',
  },
  {
    id: 'authorization-not-execution-policy',
    title: 'Authorization Not Execution Policy',
    category: 'authorization_artifact',
    status: 'present',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_AUTHORIZATION_NOT_EXECUTION_POLICY.md',
    summary: 'Authorization != Execution policy documented. Auth to plan != auth to execute.',
    forbiddenAction: 'Do not conflate authorization with execution permission.',
  },
  {
    id: 'rollback-recovery-references',
    title: 'Rollback/Recovery References',
    category: 'authorization_artifact',
    status: 'present',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'Operator console seal candidate registry',
    summary: 'Rollback and recovery documentation available from operator console phase.',
    forbiddenAction: 'Do not authorize without rollback/recovery references.',
  },

  // === Required Field ===
  {
    id: 'authorization-text-presence',
    title: 'Authorization Text Presence',
    category: 'required_field',
    status: 'pending',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_HUMAN_AUTHORIZATION_TEXT_SPEC.md',
    summary: 'Actual authorization text from human owner is PENDING. Not yet provided.',
    forbiddenAction: 'Do not mark complete without real human owner authorization text.',
  },
  {
    id: 'authorization-signer-presence',
    title: 'Authorization Signer Presence',
    category: 'required_field',
    status: 'pending',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_HUMAN_OWNER_FINAL_CONFIRMATION_POLICY.md',
    summary: 'Named human owner signer is PENDING. No real name on record.',
    forbiddenAction: 'Do not generate fake signer name.',
  },
  {
    id: 'authorization-timestamp-presence',
    title: 'Authorization Timestamp Presence',
    category: 'required_field',
    status: 'pending',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_HUMAN_AUTHORIZATION_TEXT_SPEC.md',
    summary: 'Authorization timestamp is PENDING. Requires YYYY-MM-DD HH:MM TZ format.',
    forbiddenAction: 'Do not generate fake timestamp.',
  },
  {
    id: 'authorization-scope-presence',
    title: 'Authorization Scope Presence',
    category: 'required_field',
    status: 'pending',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_HUMAN_AUTHORIZATION_TEXT_SPEC.md',
    summary: 'Authorization scope is PENDING. Must specify planning only or planning + preparation.',
    forbiddenAction: 'Do not accept open-ended scope.',
  },
  {
    id: 'explicit-forbidden-action-acknowledgement',
    title: 'Explicit Forbidden Action Acknowledgement',
    category: 'required_field',
    status: 'pending',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_FORBIDDEN_ACTIONS_CONTRACT.md',
    summary: 'Human owner must explicitly acknowledge all forbidden action items. PENDING.',
    forbiddenAction: 'Do not assume implicit acknowledgement.',
  },

  // === Evidence ===
  {
    id: 'smoke-evidence-references',
    title: 'Smoke Evidence References',
    category: 'evidence',
    status: 'ready',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'tests/smoke-v7.mjs:9/9 PASS',
    summary: 'Smoke tests pass (9/9). References available from previous validation runs.',
    forbiddenAction: 'Do not skip smoke evidence check.',
  },
  {
    id: 'validator-evidence-references',
    title: 'Validator Evidence References',
    category: 'evidence',
    status: 'ready',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'stage-c-authorization-contract-validator.ts:blocking=0',
    summary: 'D2 contract validator passes (blocking=0). References available.',
    forbiddenAction: 'Do not skip validator evidence check.',
  },
  {
    id: 'report-receipt-references',
    title: 'Report/Receipt References',
    category: 'evidence',
    status: 'ready',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: '_AIP_REPORTS/ and _AIP_RECEIPTS/',
    summary: 'Reports and receipts for v7.35 D1/D2/P1 are available in _AIP_REPORTS and _AIP_RECEIPTS.',
    forbiddenAction: 'Do not skip report/receipt evidence.',
  },

  // === Blocker ===
  {
    id: 'dirty-tree-blocker',
    title: 'Dirty Tree Blocker',
    category: 'blocker',
    status: 'blocked',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'git status: working tree clean',
    summary: 'Working tree must be clean before review. Currently clean or dirty depending on build state.',
    forbiddenAction: 'Do not proceed with dirty working tree.',
  },
  {
    id: 'origin-drift-blocker',
    title: 'Origin Drift Blocker',
    category: 'blocker',
    status: 'blocked',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'git status: up to date with origin/main',
    summary: 'Origin/main must be synchronized. Check before review.',
    forbiddenAction: 'Do not proceed with origin drift.',
  },
  {
    id: 'validator-blocking-blocker',
    title: 'Validator Blocking > 0 Blocker',
    category: 'blocker',
    status: 'blocked',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'Validator result check',
    summary: 'Any validator with blocking>0 blocks the review.',
    forbiddenAction: 'Do not proceed with validator failures.',
  },
  {
    id: 'typecheck-test-build-blocker',
    title: 'Typecheck/Test/Build Failure Blocker',
    category: 'blocker',
    status: 'blocked',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'npm run typecheck && npm test && npm run build',
    summary: 'Typecheck, test, or build failure blocks review.',
    forbiddenAction: 'Do not proceed with CI/CD failures.',
  },
  {
    id: 'stage-c-enabled-blocker',
    title: 'Stage C Already Enabled Blocker',
    category: 'blocker',
    status: 'forbidden',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'Ensure Stage C not already enabled',
    summary: 'If Stage C is already enabled, this review is moot.',
    forbiddenAction: 'Do not review if Stage C already enabled.',
  },
  {
    id: 'post-implementation-blocker',
    title: 'POST Implementation Blocker',
    category: 'blocker',
    status: 'forbidden',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'Code scan: no POST runtime endpoint',
    summary: 'POST runtime endpoint must not exist.',
    forbiddenAction: 'Do not review if POST runtime implemented.',
  },
  {
    id: 'db-write-blocker',
    title: 'DB Write Blocker',
    category: 'blocker',
    status: 'forbidden',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'Code scan: no DB write',
    summary: 'DB write must not have occurred in any preview phase.',
    forbiddenAction: 'Do not review if DB write occurred.',
  },
  {
    id: 'executor-presence-blocker',
    title: 'Executor Presence Blocker',
    category: 'blocker',
    status: 'forbidden',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'Code scan: no executor',
    summary: 'Runtime executor must not exist.',
    forbiddenAction: 'Do not review if executor present.',
  },
  {
    id: 'external-control-blocker',
    title: 'External Control Blocker',
    category: 'blocker',
    status: 'forbidden',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'Code scan: no external control',
    summary: 'External control must not be implemented.',
    forbiddenAction: 'Do not review if external control active.',
  },
  {
    id: 'sidebar-exposure-blocker',
    title: 'Sidebar Exposure Blocker',
    category: 'blocker',
    status: 'forbidden',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'center-access-registry.ts: visibleInSidebar=false',
    summary: 'Stage C hidden routes must not be in sidebar.',
    forbiddenAction: 'Do not review if Stage C routes exposed to sidebar.',
  },
  {
    id: 'fake-human-authorization-blocker',
    title: 'Fake Human Authorization Blocker',
    category: 'blocker',
    status: 'forbidden',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_AUTHORIZATION_FORBIDDEN_AUTOMATION_CONTRACT.md',
    summary: 'No AI-generated or fake human authorization is permitted.',
    forbiddenAction: 'Do not create or accept fake human authorization.',
  },

  // === Safety ===
  {
    id: 'no-stage-c-enablement',
    title: 'No Stage C Enablement',
    category: 'safety',
    status: 'ready',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'All registry items: canEnableStageC=false',
    summary: 'Stage C remains disabled. No enablement capability in any registry item.',
    forbiddenAction: 'Do not enable Stage C during review.',
  },
  {
    id: 'no-post-db-executor-external-connector',
    title: 'No POST/DB/Executor/External/Connector',
    category: 'safety',
    status: 'ready',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'Code scan: no POST/DB/executor/external/connector',
    summary: 'No POST runtime, DB write, executor, external control, or connector action implemented.',
    forbiddenAction: 'Do not add these capabilities.',
  },
  {
    id: 'no-sidebar-exposure-safety',
    title: 'No Sidebar Exposure',
    category: 'safety',
    status: 'ready',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'center-access-registry.ts: visibleInSidebar=false',
    summary: 'All Stage C routes are hidden direct. Not in sidebar.',
    forbiddenAction: 'Do not expose Stage C routes to sidebar.',
  },

  // === Human Review ===
  {
    id: 'final-human-owner-review-pending',
    title: 'Final Human Owner Review Pending',
    category: 'human_review',
    status: 'pending',
    readonly: true,
    requiredForHumanReview: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'Actual human owner not yet engaged',
    summary: 'Final human owner review has not occurred. Authorization status is PENDING.',
    forbiddenAction: 'Do not mark human review complete without actual human engagement.',
  },
  {
    id: 'human-owner-notified',
    title: 'Human Owner Notified',
    category: 'human_review',
    status: 'pending',
    readonly: true,
    requiredForHumanReview: false,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'Communication channel',
    summary: 'Human owner notification is PENDING.',
    forbiddenAction: 'Do not proceed without notifying human owner.',
  },

  // === Next Step ===
  {
    id: 'next-step-p3-enablement-planning',
    title: 'Next Step: P3 Enablement Planning Preview',
    category: 'next_step',
    status: 'pending',
    readonly: true,
    requiredForHumanReview: false,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_V7_35_P3_STAGE_C_ENABLEMENT_IMPLEMENTATION_PLANNING_PREVIEW.md',
    summary: 'P3 planned after P2. Enablement implementation planning preview.',
    forbiddenAction: 'Do not skip P3 before gate seal.',
  },
];
