// Stage C Enablement Planning Registry — static readonly planning items
// Does not execute API calls, modify state, write to databases, or control external tools.
// Stage C remains disabled. This is a planning preview only, not an implementation.

export type PlanningCategory =
  | 'implementation_boundary'
  | 'future_implementation'
  | 'feature_flag'
  | 'kill_switch'
  | 'design_placeholder'
  | 'rollback_recovery'
  | 'testing_smoke'
  | 'safety'
  | 'next_step';

export interface StageCEnablementPlanningItem {
  id: string;
  title: string;
  category: PlanningCategory;
  readonly: true;
  planningOnly: true;
  implementationAllowed: false;
  actionAllowed: false;
  mutationAllowed: false;
  canEnableStageC: false;
  evidenceRef: string;
  linkedDoc?: string;
  summary: string;
  implementationStatus: 'placeholder' | 'planned' | 'not_applicable';
}

export const STAGE_C_ENABLEMENT_PLANNING_REGISTRY: StageCEnablementPlanningItem[] = [
  // Implementation Boundary
  {
    id: 'implementation-phase-boundary',
    title: 'Implementation Phase Boundary',
    category: 'implementation_boundary',
    readonly: true,
    planningOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_V7_35_P3_STAGE_C_ENABLEMENT_IMPLEMENTATION_PLANNING_PREVIEW.md',
    summary: 'This phase produces planning artifacts only. No implementation occurs.',
    implementationStatus: 'not_applicable',
  },
  {
    id: 'human-authorization-requirement',
    title: 'Human Authorization Requirement',
    category: 'implementation_boundary',
    readonly: true,
    planningOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_HUMAN_AUTHORIZATION_TEXT_SPEC.md',
    summary: 'Human owner authorization must be provided before any implementation.',
    implementationStatus: 'not_applicable',
  },
  {
    id: 'read-only-default',
    title: 'Read-Only Default',
    category: 'implementation_boundary',
    readonly: true,
    planningOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'All Stage C registry items: readonly=true',
    summary: 'All Stage C preview pages must remain readonly by default. No mutation endpoints.',
    implementationStatus: 'not_applicable',
  },

  // Future Implementation
  {
    id: 'post-endpoint-placeholder',
    title: 'POST Endpoint Design Placeholder',
    category: 'future_implementation',
    readonly: true,
    planningOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_IMPLEMENTATION_PLAN_DRAFT.md',
    summary: 'POST endpoint required for Stage C enablement. Not implemented yet. Placeholder only.',
    implementationStatus: 'placeholder',
  },
  {
    id: 'db-migration-placeholder',
    title: 'DB Migration Placeholder',
    category: 'future_implementation',
    readonly: true,
    planningOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_IMPLEMENTATION_PLAN_DRAFT.md',
    summary: 'DB schema migration required for Stage C. Not implemented yet. Placeholder only.',
    implementationStatus: 'placeholder',
  },
  {
    id: 'audit-event-design-placeholder',
    title: 'Audit Event Design Placeholder',
    category: 'future_implementation',
    readonly: true,
    planningOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_IMPLEMENTATION_PLAN_DRAFT.md',
    summary: 'Audit event schema for Stage C actions. Not implemented. Placeholder only.',
    implementationStatus: 'placeholder',
  },
  {
    id: 'evidence-capture-design-placeholder',
    title: 'Evidence Capture Design Placeholder',
    category: 'future_implementation',
    readonly: true,
    planningOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_IMPLEMENTATION_PLAN_DRAFT.md',
    summary: 'Evidence capture mechanism for enablement audit trail. Placeholder only.',
    implementationStatus: 'placeholder',
  },
  {
    id: 'executor-design-placeholder',
    title: 'Executor Design Placeholder',
    category: 'future_implementation',
    readonly: true,
    planningOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_IMPLEMENTATION_PLAN_DRAFT.md',
    summary: 'Runtime executor for Stage C enablement actions. Not implemented. Placeholder only.',
    implementationStatus: 'placeholder',
  },
  {
    id: 'enablement-api-design-placeholder',
    title: 'Enablement API Design Placeholder',
    category: 'future_implementation',
    readonly: true,
    planningOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_IMPLEMENTATION_PLAN_DRAFT.md',
    summary: 'API endpoint for Stage C enablement. Not implemented. Placeholder only.',
    implementationStatus: 'placeholder',
  },

  // Feature Flag
  {
    id: 'feature-flag-requirement',
    title: 'Feature Flag Requirement',
    category: 'feature_flag',
    readonly: true,
    planningOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_IMPLEMENTATION_PLAN_DRAFT.md',
    summary: 'Stage C enablement must be gated by a feature flag. Default off.',
    implementationStatus: 'placeholder',
  },
  {
    id: 'feature-flag-default-off',
    title: 'Feature Flag Default Off',
    category: 'feature_flag',
    readonly: true,
    planningOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_IMPLEMENTATION_PLAN_DRAFT.md',
    summary: 'Feature flag must default to OFF. Requires explicit human action to enable.',
    implementationStatus: 'placeholder',
  },

  // Kill Switch
  {
    id: 'kill-switch-requirement',
    title: 'Kill Switch Requirement',
    category: 'kill_switch',
    readonly: true,
    planningOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_IMPLEMENTATION_PLAN_DRAFT.md',
    summary: 'Kill switch mechanism required for emergency disablement of Stage C.',
    implementationStatus: 'placeholder',
  },
  {
    id: 'kill-switch-design',
    title: 'Kill Switch Design Placeholder',
    category: 'kill_switch',
    readonly: true,
    planningOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_IMPLEMENTATION_PLAN_DRAFT.md',
    summary: 'Kill switch design not yet implemented. Placeholder only.',
    implementationStatus: 'placeholder',
  },
  {
    id: 'idempotency-requirement',
    title: 'Idempotency Requirement',
    category: 'kill_switch',
    readonly: true,
    planningOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_IMPLEMENTATION_PLAN_DRAFT.md',
    summary: 'Enable/disable operations must be idempotent. No double-enable risk.',
    implementationStatus: 'placeholder',
  },
  {
    id: 'rate-limit-requirement',
    title: 'Rate Limit Requirement',
    category: 'kill_switch',
    readonly: true,
    planningOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_IMPLEMENTATION_PLAN_DRAFT.md',
    summary: 'Rate limiting required for enablement endpoint to prevent rapid toggle.',
    implementationStatus: 'placeholder',
  },

  // Design Placeholder
  {
    id: 'secret-redaction-requirement',
    title: 'Secret Redaction Requirement',
    category: 'design_placeholder',
    readonly: true,
    planningOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_IMPLEMENTATION_PLAN_DRAFT.md',
    summary: 'All secrets/tokens/keys must be redacted from logs and outputs during enablement.',
    implementationStatus: 'placeholder',
  },
  {
    id: 'dry-run-first-requirement',
    title: 'Dry-Run-First Requirement',
    category: 'design_placeholder',
    readonly: true,
    planningOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_IMPLEMENTATION_PLAN_DRAFT.md',
    summary: 'Dry-run mode must be executed before actual enablement.',
    implementationStatus: 'placeholder',
  },
  {
    id: 'canary-requirement',
    title: 'Canary Requirement',
    category: 'design_placeholder',
    readonly: true,
    planningOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_IMPLEMENTATION_PLAN_DRAFT.md',
    summary: 'Canary deployment strategy required for Stage C enablement.',
    implementationStatus: 'placeholder',
  },

  // Rollback / Recovery
  {
    id: 'rollback-design-placeholder',
    title: 'Rollback Design Placeholder',
    category: 'rollback_recovery',
    readonly: true,
    planningOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_ROLLBACK_DESIGN_DRAFT.md',
    summary: 'Rollback procedure for Stage C enablement. Not implemented. Drafted in plan doc.',
    implementationStatus: 'placeholder',
  },
  {
    id: 'recovery-design-placeholder',
    title: 'Recovery Design Placeholder',
    category: 'rollback_recovery',
    readonly: true,
    planningOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_ROLLBACK_DESIGN_DRAFT.md',
    summary: 'Recovery procedure for failed enablement. Not implemented. Drafted in plan doc.',
    implementationStatus: 'placeholder',
  },
  {
    id: 'monitoring-requirement',
    title: 'Monitoring Requirement',
    category: 'rollback_recovery',
    readonly: true,
    planningOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_IMPLEMENTATION_PLAN_DRAFT.md',
    summary: 'Monitoring and alerting required during and after enablement.',
    implementationStatus: 'placeholder',
  },

  // Testing / Smoke
  {
    id: 'smoke-test-requirement',
    title: 'Smoke Test Requirement',
    category: 'testing_smoke',
    readonly: true,
    planningOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'tests/smoke-v7.mjs',
    summary: 'Smoke tests must pass before and after enablement.',
    implementationStatus: 'placeholder',
  },
  {
    id: 'integration-test-requirement',
    title: 'Integration Test Requirement',
    category: 'testing_smoke',
    readonly: true,
    planningOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_ENABLEMENT_IMPLEMENTATION_PLAN_DRAFT.md',
    summary: 'Integration tests required for enablement flow.',
    implementationStatus: 'placeholder',
  },

  // Safety
  {
    id: 'no-auto-execution',
    title: 'No Auto Execution',
    category: 'safety',
    readonly: true,
    planningOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_AUTHORIZATION_NOT_EXECUTION_POLICY.md',
    summary: 'No automatic execution. Every enablement action requires explicit human trigger.',
    implementationStatus: 'not_applicable',
  },
  {
    id: 'no-connector-action-without-approval',
    title: 'No Connector Action Without Approval',
    category: 'safety',
    readonly: true,
    planningOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_FORBIDDEN_ACTIONS_CONTRACT.md',
    summary: 'Connector actions must not execute without separate human approval.',
    implementationStatus: 'not_applicable',
  },
  {
    id: 'no-external-control-without-approval',
    title: 'No External Control Without Approval',
    category: 'safety',
    readonly: true,
    planningOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_FORBIDDEN_ACTIONS_CONTRACT.md',
    summary: 'External control actions must not execute without separate human approval.',
    implementationStatus: 'not_applicable',
  },
  {
    id: 'no-production-enablement',
    title: 'No Production Enablement',
    category: 'safety',
    readonly: true,
    planningOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'All planning items: implementationStatus=placeholder',
    summary: 'No production enablement is implemented. All items are planning-only.',
    implementationStatus: 'not_applicable',
  },
  {
    id: 'final-human-gate-required',
    title: 'Final Human Gate Required',
    category: 'safety',
    readonly: true,
    planningOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_HUMAN_OWNER_FINAL_CONFIRMATION_POLICY.md',
    summary: 'A separate final human gate is required before any production enablement.',
    implementationStatus: 'not_applicable',
  },

  // Next Step
  {
    id: 'next-step-p4-gate-seal',
    title: 'Next Step: P4 Authorization Gate Seal Candidate',
    category: 'next_step',
    readonly: true,
    planningOnly: true,
    implementationAllowed: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_V7_35_P4_STAGE_C_AUTHORIZATION_GATE_SEAL_CANDIDATE.md',
    summary: 'P4 planned after P3. Combine P2+P3 into authorization gate seal candidate.',
    implementationStatus: 'not_applicable',
  },
];
