export type DryTrialCategory =
  | 'authorization'
  | 'dry_trial'
  | 'feature_flag'
  | 'stage_c'
  | 'smoke'
  | 'rollback'
  | 'safety'
  | 'route'
  | 'next_gate';

export interface StageCFeatureFlagDryTrialItem {
  id: string;
  title: string;
  category: DryTrialCategory;
  status: 'ready' | 'trial_only' | 'blocked' | 'forbidden' | 'not_applicable';
  readonly: true;
  dryTrialOnly: true;
  featureFlagOfficiallyEnabled: false;
  stageCEnabled: false;
  actionAllowed: false;
  mutationAllowed: false;
  canEnableStageC: false;
  evidenceRef: string;
  summary: string;
  forbiddenAction: string;
}

export const DRY_TRIAL_REGISTRY: StageCFeatureFlagDryTrialItem[] = [
  {
    id: 'dt-authorization-captured',
    title: 'Human approval captured',
    category: 'authorization',
    status: 'ready',
    readonly: true,
    dryTrialOnly: true,
    featureFlagOfficiallyEnabled: false,
    stageCEnabled: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'docs/product/AIP_V7_40_P3_LOCAL_FEATURE_FLAG_TOGGLE_DRY_TRIAL_AUTHORIZATION.md',
    summary: 'Human owner explicitly authorized the local dry trial. Authorization text captured in evidence doc.',
    forbiddenAction: 'Exceed authorization scope',
  },
  {
    id: 'dt-dry-trial-requested',
    title: 'Dry trial requested',
    category: 'dry_trial',
    status: 'ready',
    readonly: true,
    dryTrialOnly: true,
    featureFlagOfficiallyEnabled: false,
    stageCEnabled: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP v7.40-P3 task execution',
    summary: 'Dry trial has been initiated with human approval.',
    forbiddenAction: 'Skip authorization before trial',
  },
  {
    id: 'dt-dry-trial-reviewed',
    title: 'Dry trial reviewed',
    category: 'dry_trial',
    status: 'ready',
    readonly: true,
    dryTrialOnly: true,
    featureFlagOfficiallyEnabled: false,
    stageCEnabled: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'Smoke results, validator results, safety search results',
    summary: 'Dry trial review completed. All static checks pass. Runtime smoke verified.',
    forbiddenAction: 'Skip review',
  },
  {
    id: 'dt-dry-trial-completed',
    title: 'Dry trial completed',
    category: 'dry_trial',
    status: 'ready',
    readonly: true,
    dryTrialOnly: true,
    featureFlagOfficiallyEnabled: false,
    stageCEnabled: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP v7.40-P3 report',
    summary: 'Dry trial execution completed. Report generated with results and next steps.',
    forbiddenAction: 'Claim dry trial = Stage C enabled',
  },
  {
    id: 'dt-flag-remains-off',
    title: 'Feature flag remains off',
    category: 'feature_flag',
    status: 'ready',
    readonly: true,
    dryTrialOnly: true,
    featureFlagOfficiallyEnabled: false,
    stageCEnabled: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'GET /api/stage-c/status → featureFlag.currentState = off',
    summary: 'Feature flag stage_c_enablement officially remains off. Dry trial does not change this.',
    forbiddenAction: 'Toggle flag to on during dry trial',
  },
  {
    id: 'dt-stage-c-disabled',
    title: 'Stage C remains disabled',
    category: 'stage_c',
    status: 'ready',
    readonly: true,
    dryTrialOnly: true,
    featureFlagOfficiallyEnabled: false,
    stageCEnabled: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'GET /api/stage-c/status → stageCEnabled = false, canEnableStageC = false',
    summary: 'Stage C remains disabled throughout the dry trial. Dry trial does not enable Stage C.',
    forbiddenAction: 'Enable Stage C',
  },
  {
    id: 'dt-status-api-confirms',
    title: 'Status API confirms disabled state',
    category: 'smoke',
    status: 'ready',
    readonly: true,
    dryTrialOnly: true,
    featureFlagOfficiallyEnabled: false,
    stageCEnabled: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'GET /api/stage-c/status → 200',
    summary: 'Status API returns 200 confirming Stage C disabled, feature flag off, all safety boundaries intact.',
    forbiddenAction: 'Ignore status API result',
  },
  {
    id: 'dt-post-blocked',
    title: 'POST remains blocked',
    category: 'smoke',
    status: 'ready',
    readonly: true,
    dryTrialOnly: true,
    featureFlagOfficiallyEnabled: false,
    stageCEnabled: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'POST /api/stage-c/status → blocked',
    summary: 'POST /api/stage-c/status remains blocked during dry trial.',
    forbiddenAction: 'Allow POST during dry trial',
  },
  {
    id: 'dt-db-write-forbidden',
    title: 'DB write forbidden',
    category: 'safety',
    status: 'forbidden',
    readonly: true,
    dryTrialOnly: true,
    featureFlagOfficiallyEnabled: false,
    stageCEnabled: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'safetyBoundary.dbWriteAllowed = false',
    summary: 'DB write remains forbidden during and after dry trial.',
    forbiddenAction: 'Write to database',
  },
  {
    id: 'dt-executor-forbidden',
    title: 'Executor forbidden',
    category: 'safety',
    status: 'forbidden',
    readonly: true,
    dryTrialOnly: true,
    featureFlagOfficiallyEnabled: false,
    stageCEnabled: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'safetyBoundary.executorAllowed = false',
    summary: 'Executor remains forbidden during and after dry trial.',
    forbiddenAction: 'Execute runtime actions',
  },
  {
    id: 'dt-external-control-forbidden',
    title: 'External control forbidden',
    category: 'safety',
    status: 'forbidden',
    readonly: true,
    dryTrialOnly: true,
    featureFlagOfficiallyEnabled: false,
    stageCEnabled: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'safetyBoundary.externalControlAllowed = false',
    summary: 'External control remains forbidden during and after dry trial.',
    forbiddenAction: 'Control external tools',
  },
  {
    id: 'dt-connector-action-forbidden',
    title: 'Connector action forbidden',
    category: 'safety',
    status: 'forbidden',
    readonly: true,
    dryTrialOnly: true,
    featureFlagOfficiallyEnabled: false,
    stageCEnabled: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'safetyBoundary.connectorActionAllowed = false',
    summary: 'Connector action remains forbidden during and after dry trial.',
    forbiddenAction: 'Execute connector actions',
  },
  {
    id: 'dt-kill-switch-non-executable',
    title: 'Kill switch non-executable',
    category: 'safety',
    status: 'ready',
    readonly: true,
    dryTrialOnly: true,
    featureFlagOfficiallyEnabled: false,
    stageCEnabled: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'GET /api/stage-c/status → killSwitch.executableFromUi = false',
    summary: 'Kill switch remains available but non-executable from UI during dry trial.',
    forbiddenAction: 'Make kill switch executable',
  },
  {
    id: 'dt-rollback-plan-available',
    title: 'Rollback plan available',
    category: 'rollback',
    status: 'ready',
    readonly: true,
    dryTrialOnly: true,
    featureFlagOfficiallyEnabled: false,
    stageCEnabled: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'docs/product/AIP_STAGE_C_FEATURE_FLAG_TOGGLE_ROLLBACK_PLAN.md',
    summary: 'Rollback plan exists and is available for the dry trial.',
    forbiddenAction: 'Execute rollback during dry trial',
  },
  {
    id: 'dt-smoke-plan-available',
    title: 'Smoke plan available',
    category: 'smoke',
    status: 'ready',
    readonly: true,
    dryTrialOnly: true,
    featureFlagOfficiallyEnabled: false,
    stageCEnabled: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'docs/product/AIP_STAGE_C_FEATURE_FLAG_TOGGLE_SMOKE_PLAN.md',
    summary: 'Smoke plan exists and smoke results are captured.',
    forbiddenAction: 'Skip smoke during dry trial',
  },
  {
    id: 'dt-failure-stop-available',
    title: 'Failure stop policy available',
    category: 'rollback',
    status: 'ready',
    readonly: true,
    dryTrialOnly: true,
    featureFlagOfficiallyEnabled: false,
    stageCEnabled: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'docs/product/AIP_STAGE_C_FEATURE_FLAG_TOGGLE_FAILURE_STOP_POLICY.md',
    summary: 'Failure stop policy exists and defines conditions to stop the trial.',
    forbiddenAction: 'Ignore failure conditions',
  },
  {
    id: 'dt-hidden-direct-route',
    title: 'Hidden direct route',
    category: 'route',
    status: 'ready',
    readonly: true,
    dryTrialOnly: true,
    featureFlagOfficiallyEnabled: false,
    stageCEnabled: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'App.tsx + center-access + navigation-exposure registries',
    summary: 'Dry trial preview page is registered as hidden direct route, not in sidebar.',
    forbiddenAction: 'Add dry trial page to sidebar',
  },
  {
    id: 'dt-not-in-sidebar',
    title: 'Not in sidebar',
    category: 'route',
    status: 'ready',
    readonly: true,
    dryTrialOnly: true,
    featureFlagOfficiallyEnabled: false,
    stageCEnabled: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'center-access → visibleInSidebar=false, sidebarState=hidden_direct',
    summary: 'Dry trial preview page is not visible in sidebar.',
    forbiddenAction: 'Add to sidebar',
  },
  {
    id: 'dt-no-tag-release',
    title: 'No tag/release',
    category: 'safety',
    status: 'forbidden',
    readonly: true,
    dryTrialOnly: true,
    featureFlagOfficiallyEnabled: false,
    stageCEnabled: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP governance policy',
    summary: 'No git tag or GitHub release associated with dry trial.',
    forbiddenAction: 'Create tag/release',
  },
  {
    id: 'dt-next-gate-auth-required',
    title: 'Next gate requires new authorization',
    category: 'next_gate',
    status: 'trial_only',
    readonly: true,
    dryTrialOnly: true,
    featureFlagOfficiallyEnabled: false,
    stageCEnabled: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'v7.40 Final Seal Recheck',
    summary: 'After dry trial, next step is v7.40 Final Seal Recheck. Any feature flag toggle beyond dry trial requires new human authorization.',
    forbiddenAction: 'Skip to production toggle',
  },
];
