export type ToggleTrialCategory =
  | 'current_state'
  | 'human_approval'
  | 'rollback'
  | 'smoke'
  | 'safety'
  | 'forbidden_action'
  | 'trial_boundary'
  | 'next_gate';

export interface StageCFeatureFlagToggleTrialItem {
  id: string;
  title: string;
  category: ToggleTrialCategory;
  status: 'ready' | 'required' | 'pending' | 'blocked' | 'forbidden' | 'not_applicable';
  readonly: true;
  trialPlanOnly: true;
  toggleExecuted: false;
  toggleAllowedNow: false;
  actionAllowed: false;
  mutationAllowed: false;
  canEnableStageC: false;
  evidenceRef: string;
  summary: string;
  forbiddenAction: string;
}

export const TOGGLE_TRIAL_REGISTRY: StageCFeatureFlagToggleTrialItem[] = [
  {
    id: 'tt-current-flag-off',
    title: 'Current feature flag is off',
    category: 'current_state',
    status: 'ready',
    readonly: true,
    trialPlanOnly: true,
    toggleExecuted: false,
    toggleAllowedNow: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'GET /api/stage-c/status → featureFlag.currentState = off',
    summary: 'Feature flag stage_c_enablement is currently off. Confirmed via live smoke in v7.39-P2.',
    forbiddenAction: 'Toggle flag without authorization',
  },
  {
    id: 'tt-current-toggle-not-executed',
    title: 'Toggle trial not executed in this task',
    category: 'current_state',
    status: 'ready',
    readonly: true,
    trialPlanOnly: true,
    toggleExecuted: false,
    toggleAllowedNow: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'Task definition: v7.40-P2 is docs-only trial plan',
    summary: 'This task creates the trial plan only. No toggle is executed at this stage.',
    forbiddenAction: 'Execute toggle during plan creation',
  },
  {
    id: 'tt-human-approval-required',
    title: 'Human approval required before toggle',
    category: 'human_approval',
    status: 'required',
    readonly: true,
    trialPlanOnly: true,
    toggleExecuted: false,
    toggleAllowedNow: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'docs/product/AIP_STAGE_C_FEATURE_FLAG_TOGGLE_HUMAN_APPROVAL_TEMPLATE.md',
    summary: 'Toggle must not proceed without explicit human owner authorization using the approval template.',
    forbiddenAction: 'Toggle without human approval',
  },
  {
    id: 'tt-rollback-plan-required',
    title: 'Rollback plan required',
    category: 'rollback',
    status: 'required',
    readonly: true,
    trialPlanOnly: true,
    toggleExecuted: false,
    toggleAllowedNow: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'docs/product/AIP_STAGE_C_FEATURE_FLAG_TOGGLE_ROLLBACK_PLAN.md',
    summary: 'A pre-approved rollback plan must exist before any toggle trial.',
    forbiddenAction: 'Toggle without rollback plan',
  },
  {
    id: 'tt-kill-switch-required',
    title: 'Kill switch required',
    category: 'rollback',
    status: 'required',
    readonly: true,
    trialPlanOnly: true,
    toggleExecuted: false,
    toggleAllowedNow: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'GET /api/stage-c/status → killSwitch.available = true',
    summary: 'Kill switch is available and must be tested before toggle. It must remain non-executable from UI.',
    forbiddenAction: 'Toggle without kill switch readiness',
  },
  {
    id: 'tt-smoke-plan-required',
    title: 'Smoke plan required',
    category: 'smoke',
    status: 'required',
    readonly: true,
    trialPlanOnly: true,
    toggleExecuted: false,
    toggleAllowedNow: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'docs/product/AIP_STAGE_C_FEATURE_FLAG_TOGGLE_SMOKE_PLAN.md',
    summary: 'Pre and post toggle smoke verification must be defined and passing.',
    forbiddenAction: 'Toggle without smoke verification',
  },
  {
    id: 'tt-safety-search-required',
    title: 'Safety search required',
    category: 'safety',
    status: 'required',
    readonly: true,
    trialPlanOnly: true,
    toggleExecuted: false,
    toggleAllowedNow: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'v7.40-P2 safety search results',
    summary: 'Safety search must pass with 0 blocking issues before any toggle.',
    forbiddenAction: 'Toggle with unresolved safety issues',
  },
  {
    id: 'tt-status-api-required',
    title: 'Status API verification required',
    category: 'smoke',
    status: 'required',
    readonly: true,
    trialPlanOnly: true,
    toggleExecuted: false,
    toggleAllowedNow: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'GET /api/stage-c/status',
    summary: 'GET /api/stage-c/status must return 200 with expected fields before and after toggle.',
    forbiddenAction: 'Skip status API verification',
  },
  {
    id: 'tt-post-blocked-required',
    title: 'POST blocked required',
    category: 'smoke',
    status: 'required',
    readonly: true,
    trialPlanOnly: true,
    toggleExecuted: false,
    toggleAllowedNow: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'POST /api/stage-c/status → blocked',
    summary: 'POST /api/stage-c/status must remain blocked after toggle.',
    forbiddenAction: 'Allow POST after toggle',
  },
  {
    id: 'tt-db-write-forbidden',
    title: 'DB write forbidden',
    category: 'forbidden_action',
    status: 'forbidden',
    readonly: true,
    trialPlanOnly: true,
    toggleExecuted: false,
    toggleAllowedNow: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'safetyBoundary.dbWriteAllowed = false',
    summary: 'Database write remains forbidden before and after toggle trial.',
    forbiddenAction: 'Write to database',
  },
  {
    id: 'tt-executor-forbidden',
    title: 'Executor forbidden',
    category: 'forbidden_action',
    status: 'forbidden',
    readonly: true,
    trialPlanOnly: true,
    toggleExecuted: false,
    toggleAllowedNow: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'safetyBoundary.executorAllowed = false',
    summary: 'Executor remains forbidden before and after toggle trial.',
    forbiddenAction: 'Execute runtime actions',
  },
  {
    id: 'tt-external-control-forbidden',
    title: 'External control forbidden',
    category: 'forbidden_action',
    status: 'forbidden',
    readonly: true,
    trialPlanOnly: true,
    toggleExecuted: false,
    toggleAllowedNow: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'safetyBoundary.externalControlAllowed = false',
    summary: 'External control remains forbidden before and after toggle trial.',
    forbiddenAction: 'Control external tools',
  },
  {
    id: 'tt-connector-action-forbidden',
    title: 'Connector action forbidden',
    category: 'forbidden_action',
    status: 'forbidden',
    readonly: true,
    trialPlanOnly: true,
    toggleExecuted: false,
    toggleAllowedNow: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'safetyBoundary.connectorActionAllowed = false',
    summary: 'Connector action remains forbidden before and after toggle trial.',
    forbiddenAction: 'Execute connector actions',
  },
  {
    id: 'tt-sidebar-exposure-forbidden',
    title: 'Sidebar exposure forbidden',
    category: 'forbidden_action',
    status: 'forbidden',
    readonly: true,
    trialPlanOnly: true,
    toggleExecuted: false,
    toggleAllowedNow: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'center-access + navigation-exposure registries',
    summary: 'Toggle trial pages must not be added to sidebar.',
    forbiddenAction: 'Add toggle trial page to sidebar',
  },
  {
    id: 'tt-no-tag-release',
    title: 'No tag/release',
    category: 'forbidden_action',
    status: 'forbidden',
    readonly: true,
    trialPlanOnly: true,
    toggleExecuted: false,
    toggleAllowedNow: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'AIP governance policy',
    summary: 'No git tag or GitHub release associated with toggle trial.',
    forbiddenAction: 'Create tag/release during toggle trial',
  },
  {
    id: 'tt-canary-local-only',
    title: 'Canary / local-only trial boundary',
    category: 'trial_boundary',
    status: 'required',
    readonly: true,
    trialPlanOnly: true,
    toggleExecuted: false,
    toggleAllowedNow: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'v7.40-P2 trial boundary definition',
    summary: 'Feature flag toggle trial must be limited to local/dev environment. No production toggle.',
    forbiddenAction: 'Toggle in production',
  },
  {
    id: 'tt-auto-rollback-condition',
    title: 'Auto rollback condition',
    category: 'rollback',
    status: 'required',
    readonly: true,
    trialPlanOnly: true,
    toggleExecuted: false,
    toggleAllowedNow: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'docs/product/AIP_STAGE_C_FEATURE_FLAG_TOGGLE_ROLLBACK_PLAN.md',
    summary: 'Define conditions that trigger automatic rollback (e.g. unexpected POST endpoint, DB write attempt).',
    forbiddenAction: 'Ignore rollback triggers',
  },
  {
    id: 'tt-failure-stop-condition',
    title: 'Failure stop condition',
    category: 'trial_boundary',
    status: 'required',
    readonly: true,
    trialPlanOnly: true,
    toggleExecuted: false,
    toggleAllowedNow: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'docs/product/AIP_STAGE_C_FEATURE_FLAG_TOGGLE_FAILURE_STOP_POLICY.md',
    summary: 'Define conditions that stop the trial (e.g. smoke fails, safety violation).',
    forbiddenAction: 'Continue trial after failure condition met',
  },
  {
    id: 'tt-reporting-required',
    title: 'Reporting requirement',
    category: 'trial_boundary',
    status: 'required',
    readonly: true,
    trialPlanOnly: true,
    toggleExecuted: false,
    toggleAllowedNow: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'v7.40-P2 trial report template',
    summary: 'Toggle trial must produce a report documenting results, deviations, and next steps.',
    forbiddenAction: 'Skip reporting',
  },
  {
    id: 'tt-next-authorization-gate',
    title: 'Next authorization gate',
    category: 'next_gate',
    status: 'required',
    readonly: true,
    trialPlanOnly: true,
    toggleExecuted: false,
    toggleAllowedNow: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'v7.40-P3 definition',
    summary: 'After trial plan is approved, next step is v7.40-P3 (if human approves).',
    forbiddenAction: 'Skip to production toggle',
  },
  {
    id: 'tt-stage-c-disabled',
    title: 'Stage C remains disabled',
    category: 'current_state',
    status: 'forbidden',
    readonly: true,
    trialPlanOnly: true,
    toggleExecuted: false,
    toggleAllowedNow: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'GET /api/stage-c/status → stageCEnabled = false',
    summary: 'Stage C remains disabled throughout toggle trial. Toggle does not enable Stage C.',
    forbiddenAction: 'Enable Stage C',
  },
  {
    id: 'tt-post-runtime-forbidden',
    title: 'POST runtime forbidden',
    category: 'forbidden_action',
    status: 'forbidden',
    readonly: true,
    trialPlanOnly: true,
    toggleExecuted: false,
    toggleAllowedNow: false,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    evidenceRef: 'allowedMethods=[GET], blockedMethods=[POST,PUT,PATCH,DELETE]',
    summary: 'POST runtime remains forbidden before and after toggle trial.',
    forbiddenAction: 'Implement POST runtime',
  },
];
