// Stage C Authorization Contract Registry — static readonly authorization contract terms
// Does not execute API calls, modify state, write to databases, or control external tools.
// Stage C remains disabled. This is not an authorization execution mechanism.

export type AuthorizationCategory =
  | 'authorization'
  | 'required_field'
  | 'evidence'
  | 'blocker'
  | 'safety'
  | 'forbidden_automation'
  | 'next_step';

export type AuthorizationStatus = 'required' | 'ready' | 'blocked' | 'forbidden' | 'not_applicable';

export interface StageCAuthorizationContractItem {
  id: string;
  title: string;
  category: AuthorizationCategory;
  status: AuthorizationStatus;
  readonly: true;
  requiredForAuthorization: boolean;
  actionAllowed: false;
  mutationAllowed: false;
  canAuthorize: false;
  canEnableStageC: false;
  evidenceRef: string;
  linkedDoc?: string;
  summary: string;
  forbiddenAction: string;
}

export const STAGE_C_AUTHORIZATION_CONTRACT_REGISTRY: StageCAuthorizationContractItem[] = [
  // Authorization
  {
    id: 'human-owner-explicit-authorization',
    title: 'Human Owner Explicit Authorization Required',
    category: 'authorization',
    status: 'required',
    readonly: true,
    requiredForAuthorization: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_HUMAN_AUTHORIZATION_TEXT_SPEC.md',
    linkedDoc: 'AIP_STAGE_C_HUMAN_AUTHORIZATION_TEXT_SPEC.md',
    summary: 'Named human owner must provide explicit written authorization using the spec template.',
    forbiddenAction: 'Do not authorize without explicit human owner written statement.',
  },
  {
    id: 'authorization-text-template-required',
    title: 'Authorization Text Template Required',
    category: 'required_field',
    status: 'required',
    readonly: true,
    requiredForAuthorization: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_HUMAN_AUTHORIZATION_TEXT_SPEC.md',
    summary: 'Authorization must follow the strict template with all fields filled.',
    forbiddenAction: 'Do not use non-template authorization text.',
  },
  {
    id: 'authorization-signer-required',
    title: 'Authorization Signer Required',
    category: 'required_field',
    status: 'required',
    readonly: true,
    requiredForAuthorization: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_HUMAN_OWNER_FINAL_CONFIRMATION_POLICY.md',
    summary: 'Authorization must name the human owner who signs it.',
    forbiddenAction: 'Do not accept anonymous authorization.',
  },
  {
    id: 'authorization-timestamp-required',
    title: 'Authorization Timestamp Required',
    category: 'required_field',
    status: 'required',
    readonly: true,
    requiredForAuthorization: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_HUMAN_AUTHORIZATION_TEXT_SPEC.md',
    summary: 'Authorization must include timestamp in YYYY-MM-DD HH:MM TZ format.',
    forbiddenAction: 'Do not accept authorization without timestamp.',
  },
  {
    id: 'authorization-scope-required',
    title: 'Authorization Scope Required',
    category: 'required_field',
    status: 'required',
    readonly: true,
    requiredForAuthorization: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_HUMAN_AUTHORIZATION_TEXT_SPEC.md',
    summary: 'Authorization must specify scope (planning only / planning + preparation / other).',
    forbiddenAction: 'Do not accept open-ended authorization.',
  },
  {
    id: 'forbidden-actions-acknowledged',
    title: 'Forbidden Actions Acknowledged',
    category: 'authorization',
    status: 'required',
    readonly: true,
    requiredForAuthorization: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_FORBIDDEN_ACTIONS_CONTRACT.md',
    summary: 'Human owner must acknowledge all 19 forbidden action items.',
    forbiddenAction: 'Do not proceed unless forbidden actions are acknowledged.',
  },
  // Evidence
  {
    id: 'v7-34-final-seal-required',
    title: 'v7.34 Final Seal Required',
    category: 'evidence',
    status: 'ready',
    readonly: true,
    requiredForAuthorization: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'V7_34_FINAL_SEAL_READY_WITH_ROUTE_SMOKE_DEFERRED',
    linkedDoc: 'AIP_V7_34_FINAL_SEAL_RECHECK.md',
    summary: 'v7.34 final seal recheck must be completed and confirmed.',
    forbiddenAction: 'Do not authorize without v7.34 final seal.',
  },
  {
    id: 'readiness-contract-required',
    title: 'Readiness Contract Required',
    category: 'evidence',
    status: 'ready',
    readonly: true,
    requiredForAuthorization: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_READINESS_CONTRACT_V1.md',
    summary: 'Stage C readiness contract v1 must be available and frozen.',
    forbiddenAction: 'Do not authorize without readiness contract.',
  },
  {
    id: 'human-review-policy-required',
    title: 'Human Review Policy Required',
    category: 'evidence',
    status: 'ready',
    readonly: true,
    requiredForAuthorization: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'V7_34_D1_STAGE_C_HUMAN_REVIEW_BLUEPRINT_READY',
    summary: 'Human review policy (roles, escalation, denial) must be documented.',
    forbiddenAction: 'Do not authorize without human review policy.',
  },
  {
    id: 'evidence-requirements-doc',
    title: 'Evidence Requirements Doc Required',
    category: 'evidence',
    status: 'ready',
    readonly: true,
    requiredForAuthorization: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_AUTHORIZATION_EVIDENCE_REQUIREMENTS.md',
    summary: 'Authorization evidence requirements document must exist.',
    forbiddenAction: 'Do not authorize without evidence requirements doc.',
  },
  {
    id: 'rollback-recovery-policy',
    title: 'Rollback/Recovery Policy Required',
    category: 'evidence',
    status: 'ready',
    readonly: true,
    requiredForAuthorization: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'Operator console seal candidate registry',
    summary: 'Rollback and recovery documentation must be available.',
    forbiddenAction: 'Do not authorize without rollback/recovery policy.',
  },
  // Blockers
  {
    id: 'dirty-tree-blocker',
    title: 'Dirty Working Tree Blocker',
    category: 'blocker',
    status: 'required',
    readonly: true,
    requiredForAuthorization: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_AUTHORIZATION_BLOCKER_CHECKLIST.md',
    summary: 'Dirty working tree blocks authorization.',
    forbiddenAction: 'Do not authorize with uncommitted changes.',
  },
  {
    id: 'origin-drift-blocker',
    title: 'Origin Drift Blocker',
    category: 'blocker',
    status: 'required',
    readonly: true,
    requiredForAuthorization: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_AUTHORIZATION_BLOCKER_CHECKLIST.md',
    summary: 'Origin/main not synchronized blocks authorization.',
    forbiddenAction: 'Do not authorize with origin drift.',
  },
  {
    id: 'validator-blocking-blocker',
    title: 'Validator Blocking > 0 Blocker',
    category: 'blocker',
    status: 'required',
    readonly: true,
    requiredForAuthorization: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_AUTHORIZATION_BLOCKER_CHECKLIST.md',
    summary: 'Any validator with blocking>0 blocks authorization.',
    forbiddenAction: 'Do not authorize with validator failures.',
  },
  {
    id: 'typecheck-test-build-blocker',
    title: 'Typecheck/Test/Build Failure Blocker',
    category: 'blocker',
    status: 'required',
    readonly: true,
    requiredForAuthorization: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_AUTHORIZATION_BLOCKER_CHECKLIST.md',
    summary: 'typecheck, test, or build failure blocks authorization.',
    forbiddenAction: 'Do not authorize with CI/CD failures.',
  },
  {
    id: 'stage-c-enabled-blocker',
    title: 'Stage C Already Enabled Blocker',
    category: 'blocker',
    status: 'required',
    readonly: true,
    requiredForAuthorization: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_AUTHORIZATION_BLOCKER_CHECKLIST.md',
    summary: 'If Stage C is already enabled, authorization is moot.',
    forbiddenAction: 'Do not authorize if Stage C already enabled.',
  },
  {
    id: 'post-implementation-blocker',
    title: 'POST Implementation Blocker',
    category: 'blocker',
    status: 'forbidden',
    readonly: true,
    requiredForAuthorization: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_AUTHORIZATION_BLOCKER_CHECKLIST.md',
    summary: 'POST runtime endpoint must not exist.',
    forbiddenAction: 'Do not authorize if POST runtime implemented.',
  },
  {
    id: 'db-write-blocker',
    title: 'DB Write Blocker',
    category: 'blocker',
    status: 'forbidden',
    readonly: true,
    requiredForAuthorization: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_AUTHORIZATION_BLOCKER_CHECKLIST.md',
    summary: 'DB write must not have occurred in any preview phase.',
    forbiddenAction: 'Do not authorize if DB write occurred.',
  },
  {
    id: 'executor-presence-blocker',
    title: 'Executor Presence Blocker',
    category: 'blocker',
    status: 'forbidden',
    readonly: true,
    requiredForAuthorization: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_AUTHORIZATION_BLOCKER_CHECKLIST.md',
    summary: 'Runtime executor must not exist.',
    forbiddenAction: 'Do not authorize if executor present.',
  },
  {
    id: 'external-control-blocker',
    title: 'External Control Blocker',
    category: 'blocker',
    status: 'forbidden',
    readonly: true,
    requiredForAuthorization: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_AUTHORIZATION_BLOCKER_CHECKLIST.md',
    summary: 'External control must not be implemented.',
    forbiddenAction: 'Do not authorize if external control active.',
  },
  {
    id: 'sidebar-exposure-blocker',
    title: 'Sidebar Exposure Blocker',
    category: 'blocker',
    status: 'forbidden',
    readonly: true,
    requiredForAuthorization: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_AUTHORIZATION_BLOCKER_CHECKLIST.md',
    summary: 'Stage C hidden routes must not be in sidebar.',
    forbiddenAction: 'Do not authorize if Stage C routes exposed to sidebar.',
  },
  // Safety
  {
    id: 'missing-evidence-blocker',
    title: 'Missing Evidence Blocker',
    category: 'safety',
    status: 'required',
    readonly: true,
    requiredForAuthorization: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_REQUIRED_EVIDENCE_MATRIX.md',
    summary: 'Required evidence must be available.',
    forbiddenAction: 'Do not authorize if evidence missing.',
  },
  {
    id: 'missing-rollback-docs-blocker',
    title: 'Missing Rollback Docs Blocker',
    category: 'safety',
    status: 'required',
    readonly: true,
    requiredForAuthorization: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_AUTHORIZATION_BLOCKER_CHECKLIST.md',
    summary: 'Rollback and recovery docs must be available.',
    forbiddenAction: 'Do not authorize if rollback docs missing.',
  },
  {
    id: 'missing-human-owner-blocker',
    title: 'Missing Human Owner Blocker',
    category: 'safety',
    status: 'required',
    readonly: true,
    requiredForAuthorization: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_HUMAN_OWNER_FINAL_CONFIRMATION_POLICY.md',
    summary: 'Named human owner must be assigned.',
    forbiddenAction: 'Do not authorize without assigned human owner.',
  },
  // Forbidden automation
  {
    id: 'ai-generated-fake-authorization',
    title: 'AI-Generated Fake Authorization Blocker',
    category: 'forbidden_automation',
    status: 'forbidden',
    readonly: true,
    requiredForAuthorization: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_AUTHORIZATION_FORBIDDEN_AUTOMATION_CONTRACT.md',
    summary: 'AI (Assistant) cannot generate, sign, or confirm authorization.',
    forbiddenAction: 'Do not accept AI-generated authorization.',
  },
  {
    id: 'release-tag-forbidden',
    title: 'Release/Tag Forbidden',
    category: 'forbidden_automation',
    status: 'forbidden',
    readonly: true,
    requiredForAuthorization: false,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_FORBIDDEN_ACTIONS_CONTRACT.md',
    summary: 'No git tag or GitHub Release without explicit human approval.',
    forbiddenAction: 'Do not create tag or release.',
  },
  {
    id: 'no-automatic-enablement',
    title: 'No Automatic Enablement',
    category: 'forbidden_automation',
    status: 'forbidden',
    readonly: true,
    requiredForAuthorization: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_AUTHORIZATION_NOT_EXECUTION_POLICY.md',
    summary: 'Authorization does not automatically enable Stage C.',
    forbiddenAction: 'Do not implement automatic Stage C enablement.',
  },
  {
    id: 'no-mutation-allowed',
    title: 'No Mutation Allowed',
    category: 'forbidden_automation',
    status: 'forbidden',
    readonly: true,
    requiredForAuthorization: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_AUTHORIZATION_NOT_EXECUTION_POLICY.md',
    summary: 'Authorization contract does not permit mutation.',
    forbiddenAction: 'Do not mutate authorization contract.',
  },
  {
    id: 'no-approve-deny-mutation',
    title: 'No Approve/Deny Mutation',
    category: 'forbidden_automation',
    status: 'forbidden',
    readonly: true,
    requiredForAuthorization: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'AIP_STAGE_C_AUTHORIZATION_FORBIDDEN_AUTOMATION_CONTRACT.md',
    summary: 'No approve/deny capability in authorization contract.',
    forbiddenAction: 'Do not implement approve/deny in authorization contract.',
  },
  {
    id: 'next-step-p2-artifact-review',
    title: 'Next Step: P2 Authorization Artifact Review',
    category: 'next_step',
    status: 'required',
    readonly: true,
    requiredForAuthorization: false,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    evidenceRef: 'V7_35_P2_STAGE_C_AUTHORIZATION_ARTIFACT_REVIEW_PACK',
    summary: 'P2 planned after D2+P1. Artifact review pack for authorization commit.',
    forbiddenAction: 'Do not skip artifact review before authorization commit.',
  },
];
