// Stage C First Slice Registry — minimal safe implementation shell
// Stage C remains disabled. No POST, DB write, executor, external control, or connector action.

export type StageCFirstSliceCategory =
  | 'authorization'
  | 'status_api'
  | 'feature_flag'
  | 'kill_switch'
  | 'audit'
  | 'safety'
  | 'validation'
  | 'route'
  | 'release_boundary';

export type StageCFirstSliceStatus = 'ready' | 'implemented' | 'blocked' | 'forbidden' | 'not_applicable';

export interface StageCFirstSliceRegistryItem {
  id: string;
  title: string;
  category: StageCFirstSliceCategory;
  status: StageCFirstSliceStatus;
  readonly: true;
  firstSlice: true;
  actionAllowed: false;
  mutationAllowed: false;
  canEnableStageC: false;
  implementationScope: 'readonly' | 'ui_shell' | 'schema_only' | 'blocked';
  evidenceRef: string;
  summary: string;
  forbiddenAction: string;
}

export const STAGE_C_FIRST_SLICE_REGISTRY: StageCFirstSliceRegistryItem[] = [
  {
    id: 'authorization-granted-for-review',
    title: 'Authorization Granted for First Slice Review',
    category: 'authorization',
    status: 'ready',
    readonly: true,
    firstSlice: true,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    implementationScope: 'readonly',
    evidenceRef: 'AIP_v7.38_D2_AUTHORIZATION_STATE_RECONCILIATION.md',
    summary: 'Human owner granted authorization for first slice implementation review. Stage C remains disabled.',
    forbiddenAction: 'Cannot interpret as Stage C enablement.',
  },
  {
    id: 'stage-c-disabled',
    title: 'Stage C Disabled',
    category: 'authorization',
    status: 'implemented',
    readonly: true,
    firstSlice: true,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    implementationScope: 'readonly',
    evidenceRef: 'STATUS_API',
    summary: 'Stage C is disabled. Status API returns stageCEnabled=false.',
    forbiddenAction: 'Cannot enable Stage C through any UI or API path.',
  },
  {
    id: 'readonly-status-api',
    title: 'Readonly Stage C Status API',
    category: 'status_api',
    status: 'implemented',
    readonly: true,
    firstSlice: true,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    implementationScope: 'readonly',
    evidenceRef: 'apps/local-api/src/stage-c/status.ts',
    summary: 'GET /api/stage-c/status returns Stage C safety state. No POST/PUT/DELETE.',
    forbiddenAction: 'Cannot add POST/PUT/DELETE to status endpoint.',
  },
  {
    id: 'status-api-get-only',
    title: 'Status API GET Only',
    category: 'status_api',
    status: 'implemented',
    readonly: true,
    firstSlice: true,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    implementationScope: 'readonly',
    evidenceRef: 'apps/local-api/src/stage-c/status.ts',
    summary: 'Only GET method allowed. POST, PUT, PATCH, DELETE explicitly blocked.',
    forbiddenAction: 'Cannot add mutation methods to status API.',
  },
  {
    id: 'status-api-no-db-write',
    title: 'Status API Does Not Write DB',
    category: 'status_api',
    status: 'implemented',
    readonly: true,
    firstSlice: true,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    implementationScope: 'readonly',
    evidenceRef: 'apps/local-api/src/stage-c/status.ts',
    summary: 'Status API returns static contract data. No database interaction.',
    forbiddenAction: 'Cannot add DB write to status API.',
  },
  {
    id: 'feature-flag-default-off',
    title: 'Feature Flag Default Off',
    category: 'feature_flag',
    status: 'implemented',
    readonly: true,
    firstSlice: true,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    implementationScope: 'readonly',
    evidenceRef: 'apps/local-api/src/stage-c/status.ts',
    summary: 'featureFlag.defaultState=off, featureFlag.currentState=off. Not mutable from UI.',
    forbiddenAction: 'Cannot flip feature flag via UI or API.',
  },
  {
    id: 'feature-flag-not-mutable',
    title: 'Feature Flag Not Mutable From UI',
    category: 'feature_flag',
    status: 'implemented',
    readonly: true,
    firstSlice: true,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    implementationScope: 'readonly',
    evidenceRef: 'StageCFirstSliceImplementationPreview.tsx',
    summary: 'UI shows toggle in disabled state. No mutation handler. Readonly preview only.',
    forbiddenAction: 'Cannot make feature flag mutable from UI in first slice.',
  },
  {
    id: 'kill-switch-available',
    title: 'Kill Switch UI Shell Available',
    category: 'kill_switch',
    status: 'implemented',
    readonly: true,
    firstSlice: true,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    implementationScope: 'ui_shell',
    evidenceRef: 'StageCFirstSliceImplementationPreview.tsx',
    summary: 'Kill switch UI shell displayed. Shows readiness state. Not executable.',
    forbiddenAction: 'Cannot execute kill switch from first slice UI.',
  },
  {
    id: 'kill-switch-not-executable',
    title: 'Kill Switch Not Executable From UI',
    category: 'kill_switch',
    status: 'implemented',
    readonly: true,
    firstSlice: true,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    implementationScope: 'ui_shell',
    evidenceRef: 'StageCFirstSliceImplementationPreview.tsx',
    summary: 'killSwitch.executableFromUi=false. No click handler, no POST, no mutation.',
    forbiddenAction: 'Cannot execute kill switch from preview UI.',
  },
  {
    id: 'audit-event-schema-defined',
    title: 'Audit Event Schema Defined',
    category: 'audit',
    status: 'implemented',
    readonly: true,
    firstSlice: true,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    implementationScope: 'schema_only',
    evidenceRef: 'apps/web-ui/src/registry/stage-c-audit-event-schema.ts',
    summary: 'Audit event schema defined for Stage C first slice. No persistent write.',
    forbiddenAction: 'Cannot enable persistent audit write in first slice.',
  },
  {
    id: 'audit-no-persistent-write',
    title: 'Audit Persistent Write Disabled',
    category: 'audit',
    status: 'implemented',
    readonly: true,
    firstSlice: true,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    implementationScope: 'schema_only',
    evidenceRef: 'stage-c-audit-event-schema.ts',
    summary: 'Audit schema only. persistentWriteEnabled=false. externalUploadEnabled=false.',
    forbiddenAction: 'Cannot write audit events to persistent store in first slice.',
  },
  {
    id: 'post-runtime-blocked',
    title: 'POST Runtime Blocked',
    category: 'safety',
    status: 'implemented',
    readonly: true,
    firstSlice: true,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    implementationScope: 'blocked',
    evidenceRef: 'safetyBoundary',
    summary: 'postRuntimeAllowed=false. No POST endpoints for Stage C in first slice.',
    forbiddenAction: 'Cannot create POST endpoints for Stage C.',
  },
  {
    id: 'db-write-blocked',
    title: 'DB Write Blocked',
    category: 'safety',
    status: 'implemented',
    readonly: true,
    firstSlice: true,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    implementationScope: 'blocked',
    evidenceRef: 'safetyBoundary',
    summary: 'dbWriteAllowed=false. No database writes in first slice.',
    forbiddenAction: 'Cannot write to database from any first slice component.',
  },
  {
    id: 'executor-blocked',
    title: 'Executor Blocked',
    category: 'safety',
    status: 'implemented',
    readonly: true,
    firstSlice: true,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    implementationScope: 'blocked',
    evidenceRef: 'safetyBoundary',
    summary: 'executorAllowed=false. No runtime executor in first slice.',
    forbiddenAction: 'Cannot execute runtime operations.',
  },
  {
    id: 'external-control-blocked',
    title: 'External Control Blocked',
    category: 'safety',
    status: 'implemented',
    readonly: true,
    firstSlice: true,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    implementationScope: 'blocked',
    evidenceRef: 'safetyBoundary',
    summary: 'externalControlAllowed=false. No external tool control in first slice.',
    forbiddenAction: 'Cannot control external tools or services.',
  },
  {
    id: 'connector-action-blocked',
    title: 'Connector Action Blocked',
    category: 'safety',
    status: 'implemented',
    readonly: true,
    firstSlice: true,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    implementationScope: 'blocked',
    evidenceRef: 'safetyBoundary',
    summary: 'connectorActionAllowed=false. No connector actions in first slice.',
    forbiddenAction: 'Cannot execute connector actions.',
  },
  {
    id: 'validation-gates',
    title: 'Validation Gates Defined',
    category: 'validation',
    status: 'ready',
    readonly: true,
    firstSlice: true,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    implementationScope: 'readonly',
    evidenceRef: 'AIP_V7_39_FIRST_SLICE_VALIDATION_AND_SAFETY_PLAN.md',
    summary: 'Validation gates: typecheck, tests, build, safety search, git diff, authorization.',
    forbiddenAction: 'Cannot bypass validation gates before merge.',
  },
  {
    id: 'safety-search-gates',
    title: 'Safety Search Gates Defined',
    category: 'validation',
    status: 'ready',
    readonly: true,
    firstSlice: true,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    implementationScope: 'readonly',
    evidenceRef: 'AIP_V7_39_FIRST_SLICE_VALIDATION_AND_SAFETY_PLAN.md',
    summary: 'Safety search must pass with 0 issues before any merge.',
    forbiddenAction: 'Cannot merge with safety issues.',
  },
  {
    id: 'hidden-direct-route',
    title: 'Hidden Direct Route for First Slice Preview',
    category: 'route',
    status: 'implemented',
    readonly: true,
    firstSlice: true,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    implementationScope: 'readonly',
    evidenceRef: 'App.tsx, center-access-registry.ts, navigation-exposure-registry.ts',
    summary: 'Route /stage-c-minimal-first-slice-v7-39-preview is hidden direct. Not in sidebar.',
    forbiddenAction: 'Cannot add to sidebar or expose in navigation menu.',
  },
  {
    id: 'sidebar-non-exposure',
    title: 'Sidebar Non-Exposure',
    category: 'route',
    status: 'implemented',
    readonly: true,
    firstSlice: true,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    implementationScope: 'readonly',
    evidenceRef: 'center-access-registry.ts, navigation-exposure-registry.ts',
    summary: 'visibleInSidebar=false, sidebarState=hidden_direct. Not in navigation menu.',
    forbiddenAction: 'Cannot change sidebar state to visible.',
  },
  {
    id: 'no-tag-release',
    title: 'No Tag or Release in First Slice',
    category: 'release_boundary',
    status: 'implemented',
    readonly: true,
    firstSlice: true,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    implementationScope: 'blocked',
    evidenceRef: 'AIP_V7_39_FIRST_SLICE_VALIDATION_AND_SAFETY_PLAN.md',
    summary: 'No git tag or GitHub release in first slice implementation.',
    forbiddenAction: 'Cannot create tags or releases.',
  },
  {
    id: 'rollback-docs',
    title: 'Rollback Documentation',
    category: 'validation',
    status: 'ready',
    readonly: true,
    firstSlice: true,
    actionAllowed: false,
    mutationAllowed: false,
    canEnableStageC: false,
    implementationScope: 'readonly',
    evidenceRef: 'AIP_V7_39_FIRST_SLICE_VALIDATION_AND_SAFETY_PLAN.md',
    summary: 'Rollback plan documented: set kill switch, verify disable, review audit, revert flag.',
    forbiddenAction: 'Cannot execute automated rollback in first slice.',
  },
];

export function getFirstSliceRegistryItemCount(): number {
  return STAGE_C_FIRST_SLICE_REGISTRY.length;
}
