import { CenterAccessKind, CenterAccessStatus, CenterAccessRisk, CenterAccessReadiness, CenterAccessExposureRecommendation, CenterAccessSidebarState, CenterAccessOperationalMode, CenterAccessGroup, AccessLevel, ExposureStage, ExposureDecision, CenterMaturity, CenterAccessQualityGate, CenterAccessItem } from './center-access-registry';

export const FEATURE_FLAG_CONTROL_REGISTRY: (Omit<CenterAccessItem, 'qualityGate'> & { qualityGate: CenterAccessQualityGate & { noToggle: boolean; noMutation: boolean } })[] = [
  {
    id: 'stage-c-feature-flag-control-preview',
    name: 'Stage C Feature Flag Control Preview',
    kind: 'governance' as CenterAccessKind,
    route: '/stage-c-feature-flag-control-preview',
    status: 'hidden_direct' as CenterAccessStatus,
    risk: 'medium' as CenterAccessRisk,
    readiness: 'preview_ready' as CenterAccessReadiness,
    exposureRecommendation: 'keep_hidden_direct' as CenterAccessExposureRecommendation,
    visibleInSidebar: false,
    allowedNow: true,
    safetyBoundary: [
      'readonly',
      'no_toggle',
      'no_mutation',
      'no_db_write',
      'no_external_control',
      'no_stage_c',
    ],
    allowedActions: ['view_control_preview', 'view_flag_status', 'view_requirements'],
    blockedActions: [
      'enable_stage_c',
      'toggle_feature_flag',
      'write_database',
      'modify_sidebar',
      'control_external_tools',
      'call_external_api',
      'release',
      'approve',
      'reject',
    ],
    requiredBeforeExposure: [
      'readonly_only',
      'no_toggle',
      'no_db_write',
      'validator_pass',
    ],
    releaseGate: [],
    displayOrder: 999,
    group: 'governance' as CenterAccessGroup,
    sidebarState: 'hidden_direct' as CenterAccessSidebarState,
    operationalMode: 'readonly' as CenterAccessOperationalMode,
    readinessScore: 90,
    qualityGate: {
      readonly: true,
      noDbWrite: true,
      noExternalControl: true,
      noStageC: true,
      noDangerousActions: true,
      noToggle: true,
      noMutation: true,
    },
    statusBadges: ['未入菜单', '控制台只读预览', 'toggle_disabled'],
    description: 'Stage C Feature Flag Control Console Preview — 28 项只读控制台条目。toggleEnabled=false, actionAllowed=false, mutationAllowed=false。未入左侧菜单。hidden direct route。',
    notes: 'v7.40-P1 Feature Flag Control Console Preview。28 items，全部 readonly/controlPreviewOnly/toggleEnabled=false/actionAllowed=false/mutationAllowed=false。不入 sidebar。不启用 Stage C。不写 DB。不控制外部工具。',
    accessLevel: 'direct_url_only' as AccessLevel,
    recommendedAccessLevel: 'direct_url_only' as AccessLevel,
    launchpadVisible: true,
    advancedHubVisible: true,
    directUrlAllowed: true,
    exposureStage: 'design' as ExposureStage,
    exposureDecision: 'hold' as ExposureDecision,
    exposureReason: 'v7.40-P1 Feature Flag Control Console Preview — readonly/disabled control preview. Keep hidden direct. Not in sidebar. Toggle disabled.',
    targetContainer: 'launchpad',
    rollbackPlan: 'No sidebar entry to revert. Remove route from App.tsx if needed.',
    userImpact: 'Low — readonly disabled control preview page. No toggle, no mutation, no POST.',
    maturity: 'preview' as CenterMaturity,
    owner: 'governance',
  },
];
