// Stage C Authorization Gate Seal Registry — static readonly gate seal candidate items
// Does not execute API calls, modify state, write to databases, or control external tools.
// Stage C remains disabled. Authorization gate seal candidate only.

export type GateSealCategory =
  | 'seal_baseline'
  | 'authorization_layer'
  | 'required_for_gate'
  | 'evidence_matrix'
  | 'blocker_matrix'
  | 'safety_boundary'
  | 'validator_status'
  | 'next_step';

export type AuthorizationState = 'pending' | 'provided_for_review' | 'blocked';

export interface StageCAuthorizationGateSealItem {
  id: string;
  title: string;
  category: GateSealCategory;
  readonly: true;
  requiredForGateSeal: boolean;
  actionAllowed: false;
  mutationAllowed: false;
  canAuthorize: false;
  canEnableStageC: false;
  authorizationState: AuthorizationState;
  evidenceRef: string;
  linkedDoc?: string;
  summary: string;
  forbiddenAction: string;
}

export const STAGE_C_AUTHORIZATION_GATE_SEAL_REGISTRY: StageCAuthorizationGateSealItem[] = [
  // Seal Baseline
  {
    id: 'v7-34-final-seal',
    title: 'v7.34 Final Seal',
    category: 'seal_baseline',
    readonly: true,
    requiredForGateSeal: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'provided_for_review',
    evidenceRef: 'V7_34_FINAL_SEAL_READY_WITH_ROUTE_SMOKE_DEFERRED',
    linkedDoc: 'AIP_V7_34_FINAL_SEAL_RECHECK.md',
    summary: 'v7.34 final seal completed. Stage C disabled. No POST/DB/executor/external.',
    forbiddenAction: 'Do not gate seal without v7.34 final seal.',
  },
  {
    id: 'v7-35-d1-authorization',
    title: 'v7.35 D1 Authorization Package',
    category: 'seal_baseline',
    readonly: true,
    requiredForGateSeal: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'provided_for_review',
    evidenceRef: 'V7_35_D1_STAGE_C_HUMAN_AUTHORIZATION_PACKAGE_READY',
    linkedDoc: 'AIP_V7_35_D1_STAGE_C_HUMAN_AUTHORIZATION_PACKAGE.md',
    summary: 'v7.35 D1 authorization package committed. 7 docs.',
    forbiddenAction: 'Do not treat D1 as actual human authorization.',
  },
  {
    id: 'v7-35-d2-contract',
    title: 'v7.35 D2 Authorization Contract',
    category: 'seal_baseline',
    readonly: true,
    requiredForGateSeal: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'provided_for_review',
    evidenceRef: 'V7_35_D2_STAGE_C_AUTHORIZATION_CONTRACT_FROZEN',
    linkedDoc: 'AIP_STAGE_C_AUTHORIZATION_CONTRACT_V1.md',
    summary: 'v7.35 D2 authorization contract frozen. 28 items, 19 validators.',
    forbiddenAction: 'Do not skip D2 contract freeze.',
  },
  {
    id: 'v7-35-p1-review-console',
    title: 'v7.35 P1 Review Console Preview',
    category: 'seal_baseline',
    readonly: true,
    requiredForGateSeal: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'provided_for_review',
    evidenceRef: 'V7_35_P1_STAGE_C_AUTHORIZATION_REVIEW_CONSOLE_PREVIEW_READY',
    linkedDoc: 'AIP_V7_35_P1_STAGE_C_AUTHORIZATION_REVIEW_CONSOLE_PREVIEW.md',
    summary: 'v7.35 P1 review console committed. 12-section readonly page.',
    forbiddenAction: 'Do not bypass P1 review console.',
  },
  {
    id: 'v7-35-p2-artifact-review',
    title: 'v7.35 P2 Authorization Artifact Review',
    category: 'seal_baseline',
    readonly: true,
    requiredForGateSeal: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'provided_for_review',
    evidenceRef: 'V7_35_P2_STAGE_C_AUTHORIZATION_ARTIFACT_REVIEW_READY_WITH_AUTHORIZATION_PENDING',
    linkedDoc: 'AIP_V7_35_P2_STAGE_C_AUTHORIZATION_ARTIFACT_REVIEW_PACK.md',
    summary: 'v7.35 P2 artifact review committed. 32 items, authorization state: PENDING.',
    forbiddenAction: 'Do not gate seal without P2 artifact review.',
  },
  {
    id: 'v7-35-p3-enablement-planning',
    title: 'v7.35 P3 Enablement Planning Preview',
    category: 'seal_baseline',
    readonly: true,
    requiredForGateSeal: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'provided_for_review',
    evidenceRef: 'V7_35_P3_STAGE_C_ENABLEMENT_IMPLEMENTATION_PLANNING_PREVIEW_READY',
    linkedDoc: 'AIP_V7_35_P3_STAGE_C_ENABLEMENT_IMPLEMENTATION_PLANNING_PREVIEW.md',
    summary: 'v7.35 P3 enablement planning preview committed. Planning only, no implementation.',
    forbiddenAction: 'Do not mistake planning for implementation.',
  },

  // Authorization Layer
  {
    id: 'auth-state-pending',
    title: 'Authorization State: PENDING',
    category: 'authorization_layer',
    readonly: true,
    requiredForGateSeal: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'pending',
    evidenceRef: 'No real human authorization text provided',
    summary: 'Current authorization state is PENDING. No real human owner authorization text has been committed.',
    forbiddenAction: 'Do not change authorization state without real human authorization.',
  },
  {
    id: 'human-owner-status',
    title: 'Human Owner Status: NOT_NOTIFIED',
    category: 'authorization_layer',
    readonly: true,
    requiredForGateSeal: false,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'pending',
    evidenceRef: 'No human owner engagement recorded',
    summary: 'Human owner has not been notified or engaged.',
    forbiddenAction: 'Do not proceed without human owner notification.',
  },

  // Required for Gate
  {
    id: 'required-fields-complete',
    title: 'Required Fields Complete',
    category: 'required_for_gate',
    readonly: true,
    requiredForGateSeal: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'pending',
    evidenceRef: 'AIP_STAGE_C_AUTHORIZATION_REQUIRED_FIELDS_MATRIX.md',
    summary: 'All 5 required fields are PENDING. No real authorization text/signer/timestamp/scope.',
    forbiddenAction: 'Do not gate seal with missing required fields.',
  },
  {
    id: 'blocker-matrix-pass',
    title: 'Blocker Matrix PASS',
    category: 'required_for_gate',
    readonly: true,
    requiredForGateSeal: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'pending',
    evidenceRef: 'AIP_STAGE_C_AUTHORIZATION_BLOCKER_MATRIX.md',
    summary: 'Blocker matrix exists with all blockers documented.',
    forbiddenAction: 'Do not skip blocker matrix check.',
  },
  {
    id: 'evidence-matrix-pass',
    title: 'Evidence Matrix PASS',
    category: 'required_for_gate',
    readonly: true,
    requiredForGateSeal: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'pending',
    evidenceRef: 'AIP_STAGE_C_AUTHORIZATION_EVIDENCE_REQUIREMENTS.md',
    summary: 'Evidence requirements documented.',
    forbiddenAction: 'Do not skip evidence matrix check.',
  },
  {
    id: 'forbidden-automation-acknowledged',
    title: 'Forbidden Automation Acknowledged',
    category: 'required_for_gate',
    readonly: true,
    requiredForGateSeal: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'pending',
    evidenceRef: 'AIP_STAGE_C_AUTHORIZATION_FORBIDDEN_AUTOMATION_CONTRACT.md',
    summary: 'Forbidden automation contract exists. 10 items. Pending human acknowledgement.',
    forbiddenAction: 'Do not gate seal without forbidden automation acknowledgement.',
  },

  // Evidence Matrix
  {
    id: 'evidence-readiness-docs',
    title: 'Evidence Readiness Docs',
    category: 'evidence_matrix',
    readonly: true,
    requiredForGateSeal: false,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'provided_for_review',
    evidenceRef: 'Evidence requirements, blocker matrix, required fields matrix',
    summary: 'All evidence documentation is present (requirements, matrix, blocker checklist).',
    forbiddenAction: 'Do not skip evidence readiness check.',
  },
  {
    id: 'smoke-test-evidence',
    title: 'Smoke Test Evidence',
    category: 'evidence_matrix',
    readonly: true,
    requiredForGateSeal: false,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'provided_for_review',
    evidenceRef: 'tests/smoke-v7.mjs:9/9 PASS',
    summary: 'Smoke tests pass (9/9).',
    forbiddenAction: 'Do not skip smoke evidence.',
  },
  {
    id: 'validator-evidence',
    title: 'Validator Evidence',
    category: 'evidence_matrix',
    readonly: true,
    requiredForGateSeal: false,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'provided_for_review',
    evidenceRef: 'All validators: blocking=0, pass=true',
    summary: 'All validators pass with blocking=0.',
    forbiddenAction: 'Do not skip validator evidence.',
  },

  // Blocker Matrix
  {
    id: 'dirty-tree',
    title: 'Dirty Tree Blocker',
    category: 'blocker_matrix',
    readonly: true,
    requiredForGateSeal: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'pending',
    evidenceRef: 'git status: working tree clean',
    summary: 'Working tree must be clean before gate seal.',
    forbiddenAction: 'Do not seal with dirty tree.',
  },
  {
    id: 'origin-drift',
    title: 'Origin Drift Blocker',
    category: 'blocker_matrix',
    readonly: true,
    requiredForGateSeal: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'pending',
    evidenceRef: 'git status: up to date',
    summary: 'Origin/main must be synchronized.',
    forbiddenAction: 'Do not seal with origin drift.',
  },
  {
    id: 'validator-failure',
    title: 'Validator Failure Blocker',
    category: 'blocker_matrix',
    readonly: true,
    requiredForGateSeal: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'pending',
    evidenceRef: 'All validators pass',
    summary: 'All validators must pass before gate seal.',
    forbiddenAction: 'Do not seal with validator failures.',
  },
  {
    id: 'stage-c-enabled-seal',
    title: 'Stage C Already Enabled Blocker',
    category: 'blocker_matrix',
    readonly: true,
    requiredForGateSeal: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'blocked',
    evidenceRef: 'Stage C remains disabled',
    summary: 'Stage C must remain disabled for this gate seal.',
    forbiddenAction: 'Do not seal if Stage C already enabled.',
  },
  {
    id: 'post-implemented',
    title: 'POST Implemented Blocker',
    category: 'blocker_matrix',
    readonly: true,
    requiredForGateSeal: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'blocked',
    evidenceRef: 'Code scan: no POST',
    summary: 'POST runtime must not exist.',
    forbiddenAction: 'Do not seal with POST implemented.',
  },
  {
    id: 'db-write-occurred',
    title: 'DB Write Occurred Blocker',
    category: 'blocker_matrix',
    readonly: true,
    requiredForGateSeal: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'blocked',
    evidenceRef: 'Code scan: no DB write',
    summary: 'DB write must not have occurred.',
    forbiddenAction: 'Do not seal with DB write occurred.',
  },
  {
    id: 'executor-present-seal',
    title: 'Executor Present Blocker',
    category: 'blocker_matrix',
    readonly: true,
    requiredForGateSeal: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'blocked',
    evidenceRef: 'Code scan: no executor',
    summary: 'Executor must not exist.',
    forbiddenAction: 'Do not seal with executor present.',
  },
  {
    id: 'external-control-active',
    title: 'External Control Active Blocker',
    category: 'blocker_matrix',
    readonly: true,
    requiredForGateSeal: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'blocked',
    evidenceRef: 'Code scan: no external control',
    summary: 'External control must not be active.',
    forbiddenAction: 'Do not seal with external control active.',
  },
  {
    id: 'sidebar-exposed',
    title: 'Sidebar Exposed Blocker',
    category: 'blocker_matrix',
    readonly: true,
    requiredForGateSeal: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'blocked',
    evidenceRef: 'All Stage C routes: visibleInSidebar=false',
    summary: 'Stage C routes must not be in sidebar.',
    forbiddenAction: 'Do not seal with sidebar exposure.',
  },
  {
    id: 'fake-auth-blocker-seal',
    title: 'Fake Authorization Blocker',
    category: 'blocker_matrix',
    readonly: true,
    requiredForGateSeal: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'blocked',
    evidenceRef: 'No fake authorization found',
    summary: 'No fake AI-generated or human authorization.',
    forbiddenAction: 'Do not seal with fake authorization.',
  },

  // Safety Boundary
  {
    id: 'stage-c-disabled-seal',
    title: 'Stage C Disabled (Safety)',
    category: 'safety_boundary',
    readonly: true,
    requiredForGateSeal: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'provided_for_review',
    evidenceRef: 'All registry items: canEnableStageC=false',
    summary: 'Stage C remains disabled across all registries.',
    forbiddenAction: 'Do not seal if Stage C can be enabled.',
  },
  {
    id: 'no-post-db-executor-seal',
    title: 'No POST/DB/Executor/External/Connector (Safety)',
    category: 'safety_boundary',
    readonly: true,
    requiredForGateSeal: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'provided_for_review',
    evidenceRef: 'Code scan across all registries',
    summary: 'No POST/DB/executor/external/connector implementation exists.',
    forbiddenAction: 'Do not seal if these exist.',
  },
  {
    id: 'no-approve-deny-seal',
    title: 'No Approve/Deny Mutation (Safety)',
    category: 'safety_boundary',
    readonly: true,
    requiredForGateSeal: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'provided_for_review',
    evidenceRef: 'All registries: mutationAllowed=false',
    summary: 'No approve/deny mutation capability exists.',
    forbiddenAction: 'Do not add approve/deny mutation.',
  },
  {
    id: 'no-tag-release-seal',
    title: 'No Tag/Release (Safety)',
    category: 'safety_boundary',
    readonly: true,
    requiredForGateSeal: false,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'provided_for_review',
    evidenceRef: 'No git tag or GitHub release created',
    summary: 'No tag or release has been created.',
    forbiddenAction: 'Do not create tag/release without human approval.',
  },

  // Validator Status
  {
    id: 'contract-validator-pass',
    title: 'Authorization Contract Validator PASS',
    category: 'validator_status',
    readonly: true,
    requiredForGateSeal: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'provided_for_review',
    evidenceRef: 'stage-c-authorization-contract-validator.ts: blocking=0',
    summary: 'D2 contract validator passes with blocking=0.',
    forbiddenAction: 'Do not seal with contract validator failures.',
  },
  {
    id: 'artifact-review-validator-pass',
    title: 'Artifact Review Validator PASS',
    category: 'validator_status',
    readonly: true,
    requiredForGateSeal: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'provided_for_review',
    evidenceRef: 'stage-c-authorization-artifact-review-validator.ts: blocking=0',
    summary: 'P2 artifact review validator passes with blocking=0.',
    forbiddenAction: 'Do not seal with artifact review validator failures.',
  },
  {
    id: 'planning-validator-pass',
    title: 'Enablement Planning Validator PASS',
    category: 'validator_status',
    readonly: true,
    requiredForGateSeal: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'provided_for_review',
    evidenceRef: 'stage-c-enablement-planning-validator.ts: blocking=0',
    summary: 'P3 planning validator passes with blocking=0.',
    forbiddenAction: 'Do not seal with planning validator failures.',
  },
  {
    id: 'gate-seal-validator-pass',
    title: 'Gate Seal Validator PASS',
    category: 'validator_status',
    readonly: true,
    requiredForGateSeal: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'provided_for_review',
    evidenceRef: 'stage-c-authorization-gate-seal-validator.ts: blocking=0',
    summary: 'P4 gate seal validator passes with blocking=0.',
    forbiddenAction: 'Do not seal with gate seal validator failures.',
  },
  {
    id: 'typecheck-test-build-seal',
    title: 'Typecheck/Test/Build PASS',
    category: 'validator_status',
    readonly: true,
    requiredForGateSeal: true,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'pending',
    evidenceRef: 'npm run typecheck && npm test && npm run build',
    summary: 'Typecheck, test, and build must all pass.',
    forbiddenAction: 'Do not seal with CI/CD failures.',
  },

  // Next Step
  {
    id: 'next-step-final-seal-recheck',
    title: 'Next Step: v7.35 Final Seal Recheck',
    category: 'next_step',
    readonly: true,
    requiredForGateSeal: false,
    actionAllowed: false,
    mutationAllowed: false,
    canAuthorize: false,
    canEnableStageC: false,
    authorizationState: 'pending',
    evidenceRef: 'AIP_V7_35_FINAL_SEAL_RECHECK.md',
    summary: 'After P4, perform final seal recheck across all v7.35 layers.',
    forbiddenAction: 'Do not skip final seal recheck.',
  },
];
