// Stage C Evidence Readiness Drill Registry — static readonly evidence readiness items
// Does not collect evidence, write to evidence store, upload files, or generate audit records.
// Stage C remains disabled.

export type EvidenceReadinessArea =
  | 'baseline'
  | 'seal'
  | 'human_review'
  | 'contract'
  | 'dashboard'
  | 'validator'
  | 'smoke'
  | 'safety'
  | 'forbidden';

export interface EvidenceReadinessItem {
  id: string;
  title: string;
  area: EvidenceReadinessArea;
  readonly: true;
  evidenceWriteAllowed: false;
  auditWriteAllowed: false;
  uploadAllowed: false;
  sourceOfTruth: boolean;
  required: boolean;
  status: 'ready' | 'deferred' | 'blocked' | 'missing';
  sourceRef: string;
  description: string;
}

export const STAGE_C_EVIDENCE_READINESS_DRILL_REGISTRY: EvidenceReadinessItem[] = [
  {
    id: 'v7-32-productization-evidence',
    title: 'v7.32 Final Productization Evidence',
    area: 'baseline',
    readonly: true,
    evidenceWriteAllowed: false,
    auditWriteAllowed: false,
    uploadAllowed: false,
    sourceOfTruth: true,
    required: true,
    status: 'ready',
    sourceRef: 'V7_32_PRODUCTIZATION_SEAL_READY verdict doc',
    description: 'v7.32 baseline sealed. Productization docs serve as evidence.',
  },
  {
    id: 'v7-33-final-seal-evidence',
    title: 'v7.33 Final Seal Evidence',
    area: 'seal',
    readonly: true,
    evidenceWriteAllowed: false,
    auditWriteAllowed: false,
    uploadAllowed: false,
    sourceOfTruth: true,
    required: true,
    status: 'ready',
    sourceRef: 'AIP_V7_33_FINAL_SEAL_RECHECK.md',
    description: 'v7.33 final seal recheck completed. All 5 phases verified.',
  },
  {
    id: 'v7-33-operator-console-evidence',
    title: 'v7.33 Operator Console Final Evidence',
    area: 'seal',
    readonly: true,
    evidenceWriteAllowed: false,
    auditWriteAllowed: false,
    uploadAllowed: false,
    sourceOfTruth: true,
    required: true,
    status: 'ready',
    sourceRef: 'AIP_V7_33_OPERATOR_CONSOLE_FINAL_BASELINE.md',
    description: 'Operator console sealed baseline. P1-P4 registry and preview pages.',
  },
  {
    id: 'v7-34-d1-human-review-evidence',
    title: 'v7.34 D1 Human Review Evidence',
    area: 'human_review',
    readonly: true,
    evidenceWriteAllowed: false,
    auditWriteAllowed: false,
    uploadAllowed: false,
    sourceOfTruth: true,
    required: true,
    status: 'ready',
    sourceRef: 'AIP_V7_34_D1_STAGE_C_HUMAN_REVIEW_EXPANSION_BLUEPRINT.md',
    description: '6 D1 docs: blueprint, roles, escalation, denial, decision record, evidence requirements.',
  },
  {
    id: 'v7-34-d2-contract-evidence',
    title: 'v7.34 D2 Contract Evidence',
    area: 'contract',
    readonly: true,
    evidenceWriteAllowed: false,
    auditWriteAllowed: false,
    uploadAllowed: false,
    sourceOfTruth: true,
    required: true,
    status: 'ready',
    sourceRef: 'AIP_V7_34_D2_STAGE_C_READINESS_CONTRACT_FREEZE.md',
    description: 'D2 contract freeze doc. 24 contract terms frozen.',
  },
  {
    id: 'v7-34-p1-dashboard-evidence',
    title: 'v7.34 P1 Dashboard Evidence',
    area: 'dashboard',
    readonly: true,
    evidenceWriteAllowed: false,
    auditWriteAllowed: false,
    uploadAllowed: false,
    sourceOfTruth: true,
    required: true,
    status: 'ready',
    sourceRef: 'AIP_V7_34_P1_STAGE_C_READINESS_DASHBOARD_PREVIEW.md',
    description: 'P1 readiness dashboard. 10 sections, hidden route. Stage C disabled.',
  },
  {
    id: 'v7-34-p2-approval-review-evidence',
    title: 'P2 Human Approval Review Evidence',
    area: 'human_review',
    readonly: true,
    evidenceWriteAllowed: false,
    auditWriteAllowed: false,
    uploadAllowed: false,
    sourceOfTruth: true,
    required: true,
    status: 'ready',
    sourceRef: 'AIP_V7_34_P2_STAGE_C_HUMAN_APPROVAL_REVIEW_CONSOLE_PREVIEW.md',
    description: 'P2 human approval review console preview. 22 review items, 18 validator checks.',
  },
  {
    id: 'validator-matrix-evidence',
    title: 'Validator Matrix Evidence',
    area: 'validator',
    readonly: true,
    evidenceWriteAllowed: false,
    auditWriteAllowed: false,
    uploadAllowed: false,
    sourceOfTruth: true,
    required: true,
    status: 'ready',
    sourceRef: 'AIP_STAGE_C_REQUIRED_VALIDATORS_MATRIX.md',
    description: 'Validators matrix doc lists all required validators across all phases.',
  },
  {
    id: 'smoke-matrix-evidence',
    title: 'Smoke Matrix Evidence',
    area: 'smoke',
    readonly: true,
    evidenceWriteAllowed: false,
    auditWriteAllowed: false,
    uploadAllowed: false,
    sourceOfTruth: true,
    required: true,
    status: 'ready',
    sourceRef: 'AIP_STAGE_C_REQUIRED_SMOKE_MATRIX.md',
    description: 'Smoke matrix doc lists all required smoke tests across all phases.',
  },
  {
    id: 'forbidden-actions-contract-evidence',
    title: 'Forbidden Actions Contract Evidence',
    area: 'forbidden',
    readonly: true,
    evidenceWriteAllowed: false,
    auditWriteAllowed: false,
    uploadAllowed: false,
    sourceOfTruth: true,
    required: true,
    status: 'ready',
    sourceRef: 'AIP_STAGE_C_FORBIDDEN_ACTIONS_CONTRACT.md',
    description: 'Forbidden actions contract doc explicitly lists all forbidden actions.',
  },
  {
    id: 'rollback-docs-evidence',
    title: 'Rollback Docs Evidence',
    area: 'safety',
    readonly: true,
    evidenceWriteAllowed: false,
    auditWriteAllowed: false,
    uploadAllowed: false,
    sourceOfTruth: true,
    required: true,
    status: 'ready',
    sourceRef: 'Operator console seal candidate registry rollback items',
    description: 'Rollback documentation exists in operator console seal candidate registry.',
  },
  {
    id: 'recovery-docs-evidence',
    title: 'Recovery Docs Evidence',
    area: 'safety',
    readonly: true,
    evidenceWriteAllowed: false,
    auditWriteAllowed: false,
    uploadAllowed: false,
    sourceOfTruth: true,
    required: true,
    status: 'ready',
    sourceRef: 'Recovery plan in operator console seal candidate registry',
    description: 'Recovery plan documented for post-enablement failure scenarios.',
  },
  {
    id: 'human-restart-policy-evidence',
    title: 'Human Restart Policy Evidence',
    area: 'safety',
    readonly: true,
    evidenceWriteAllowed: false,
    auditWriteAllowed: false,
    uploadAllowed: false,
    sourceOfTruth: true,
    required: true,
    status: 'ready',
    sourceRef: 'Contract registry item human-restart-policy',
    description: 'Server restart requires human approval and smoke checklist. No auto-restart.',
  },
  {
    id: 'route-sidebar-boundary-evidence',
    title: 'Route/Sidebar Boundary Evidence',
    area: 'safety',
    readonly: true,
    evidenceWriteAllowed: false,
    auditWriteAllowed: false,
    uploadAllowed: false,
    sourceOfTruth: true,
    required: true,
    status: 'ready',
    sourceRef: 'Navigation exposure registry entries for all Stage C routes',
    description: 'All Stage C routes are hidden direct. Not in sidebar. Not in menu-registry.',
  },
  {
    id: 'stage-c-disabled-evidence',
    title: 'Stage C Disabled Evidence',
    area: 'safety',
    readonly: true,
    evidenceWriteAllowed: false,
    auditWriteAllowed: false,
    uploadAllowed: false,
    sourceOfTruth: true,
    required: true,
    status: 'ready',
    sourceRef: 'Contract registry item stage-c-disabled',
    description: 'Stage C disabled confirmed across all registries. No enable button. No enable action.',
  },
  {
    id: 'post-blocked-evidence',
    title: 'POST Blocked Evidence',
    area: 'forbidden',
    readonly: true,
    evidenceWriteAllowed: false,
    auditWriteAllowed: false,
    uploadAllowed: false,
    sourceOfTruth: true,
    required: true,
    status: 'ready',
    sourceRef: 'Contract registry item post-blocked',
    description: 'No POST runtime endpoint implemented. All previews are frontend-only.',
  },
  {
    id: 'db-write-not-occurred-evidence',
    title: 'DB Write Not Occurred Evidence',
    area: 'forbidden',
    readonly: true,
    evidenceWriteAllowed: false,
    auditWriteAllowed: false,
    uploadAllowed: false,
    sourceOfTruth: true,
    required: true,
    status: 'ready',
    sourceRef: 'Contract registry item db-write-blocked',
    description: 'No database write has occurred in any preview phase.',
  },
  {
    id: 'external-control-not-occurred-evidence',
    title: 'External Control Not Occurred Evidence',
    area: 'forbidden',
    readonly: true,
    evidenceWriteAllowed: false,
    auditWriteAllowed: false,
    uploadAllowed: false,
    sourceOfTruth: true,
    required: true,
    status: 'ready',
    sourceRef: 'Contract registry item external-control-blocked',
    description: 'No external tool control has been implemented.',
  },
  {
    id: 'executor-absent-evidence',
    title: 'Executor Absent Evidence',
    area: 'forbidden',
    readonly: true,
    evidenceWriteAllowed: false,
    auditWriteAllowed: false,
    uploadAllowed: false,
    sourceOfTruth: true,
    required: true,
    status: 'ready',
    sourceRef: 'Contract registry item executor-absent',
    description: 'No runtime executor has been implemented.',
  },
  {
    id: 'security-scan-evidence',
    title: 'Security Scan Evidence',
    area: 'validator',
    readonly: true,
    evidenceWriteAllowed: false,
    auditWriteAllowed: false,
    uploadAllowed: false,
    sourceOfTruth: true,
    required: true,
    status: 'deferred',
    sourceRef: 'Security scan tool output',
    description: 'Security scan deferred. Required before Stage C enablement.',
  },
  {
    id: 'git-origin-sync-evidence',
    title: 'Git/Origin Sync Evidence',
    area: 'safety',
    readonly: true,
    evidenceWriteAllowed: false,
    auditWriteAllowed: false,
    uploadAllowed: false,
    sourceOfTruth: true,
    required: false,
    status: 'ready',
    sourceRef: 'git status and git log output',
    description: 'Working tree clean. Pushed to origin/main. No uncommitted changes.',
  },
  {
    id: 'readiness-contract-v1-evidence',
    title: 'Readiness Contract V1 Evidence',
    area: 'contract',
    readonly: true,
    evidenceWriteAllowed: false,
    auditWriteAllowed: false,
    uploadAllowed: false,
    sourceOfTruth: true,
    required: true,
    status: 'ready',
    sourceRef: 'AIP_STAGE_C_READINESS_CONTRACT_V1.md',
    description: '24 contract terms across 10 areas. All frozen.',
  },
  {
    id: 'evidence-matrix-evidence',
    title: 'Evidence Matrix Evidence',
    area: 'validator',
    readonly: true,
    evidenceWriteAllowed: false,
    auditWriteAllowed: false,
    uploadAllowed: false,
    sourceOfTruth: true,
    required: true,
    status: 'ready',
    sourceRef: 'AIP_STAGE_C_REQUIRED_EVIDENCE_MATRIX.md',
    description: 'Evidence matrix doc lists all required evidence across all phases.',
  },
  {
    id: 'next-step-p4-seal-candidate',
    title: 'Next Step: P4 Pre-Enable Seal Candidate',
    area: 'seal',
    readonly: true,
    evidenceWriteAllowed: false,
    auditWriteAllowed: false,
    uploadAllowed: false,
    sourceOfTruth: false,
    required: false,
    status: 'deferred',
    sourceRef: 'V7_34_P4_STAGE_C_PREENABLE_SEAL_CANDIDATE',
    description: 'P4 planned after P3. Pre-enable seal candidate will aggregate all readiness.',
  },
];
